apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - services.yaml
  - httproutes.yaml
  - grpcroute.yaml
  - securitypolicy-http.yaml
  - securitypolicy-grpc.yaml
  - clienttrafficpolicy.yaml
