apiVersion: v1
kind: Service
metadata:
  name: aisphere-hub
  namespace: aisphere
  labels:
    app.kubernetes.io/name: aisphere-hub
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: aisphere-hub
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 18001
      targetPort: http
      appProtocol: http
    - name: grpc
      port: 19001
      targetPort: grpc
      appProtocol: kubernetes.io/h2c
    - name: metrics
      port: 19090
      targetPort: metrics
      appProtocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: aisphere-hub-frontend
  namespace: aisphere
  labels:
    app.kubernetes.io/name: aisphere-hub
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: aisphere-hub
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      appProtocol: http
