// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skill/v1/release.proto

package skillv1

import (
	_ "github.com/aisphereio/kernel/api/aisphere/access/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSkillReleaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Accepts SemVer with or without the leading v; the server canonicalizes it.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Defaults to refs/heads/main when omitted.
	SourceRef string `protobuf:"bytes,3,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	// Compare-and-swap guard: publication fails when source_ref moved.
	ExpectedCommitSha string `protobuf:"bytes,4,opt,name=expected_commit_sha,json=expectedCommitSha,proto3" json:"expected_commit_sha,omitempty"`
	ReleaseNotes      string `protobuf:"bytes,5,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSkillReleaseRequest) Reset() {
	*x = CreateSkillReleaseRequest{}
	mi := &file_skill_v1_release_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillReleaseRequest) ProtoMessage() {}

func (x *CreateSkillReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_release_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillReleaseRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillReleaseRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_release_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSkillReleaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSkillReleaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateSkillReleaseRequest) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *CreateSkillReleaseRequest) GetExpectedCommitSha() string {
	if x != nil {
		return x.ExpectedCommitSha
	}
	return ""
}

func (x *CreateSkillReleaseRequest) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

type CreateSkillReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *SkillRelease          `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillReleaseResponse) Reset() {
	*x = CreateSkillReleaseResponse{}
	mi := &file_skill_v1_release_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillReleaseResponse) ProtoMessage() {}

func (x *CreateSkillReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_release_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillReleaseResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillReleaseResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_release_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkillReleaseResponse) GetRelease() *SkillRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

type GetSkillReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillReleaseRequest) Reset() {
	*x = GetSkillReleaseRequest{}
	mi := &file_skill_v1_release_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillReleaseRequest) ProtoMessage() {}

func (x *GetSkillReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_release_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillReleaseRequest.ProtoReflect.Descriptor instead.
func (*GetSkillReleaseRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_release_proto_rawDescGZIP(), []int{2}
}

func (x *GetSkillReleaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSkillReleaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetSkillReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *SkillRelease          `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillReleaseResponse) Reset() {
	*x = GetSkillReleaseResponse{}
	mi := &file_skill_v1_release_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillReleaseResponse) ProtoMessage() {}

func (x *GetSkillReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_release_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillReleaseResponse.ProtoReflect.Descriptor instead.
func (*GetSkillReleaseResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_release_proto_rawDescGZIP(), []int{3}
}

func (x *GetSkillReleaseResponse) GetRelease() *SkillRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

type ResolveSkillReleaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Exact SemVer only; ranges, branches and channels are not accepted.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSkillReleaseRequest) Reset() {
	*x = ResolveSkillReleaseRequest{}
	mi := &file_skill_v1_release_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSkillReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSkillReleaseRequest) ProtoMessage() {}

func (x *ResolveSkillReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_release_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSkillReleaseRequest.ProtoReflect.Descriptor instead.
func (*ResolveSkillReleaseRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_release_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveSkillReleaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveSkillReleaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ResolveSkillReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *SkillRelease          `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSkillReleaseResponse) Reset() {
	*x = ResolveSkillReleaseResponse{}
	mi := &file_skill_v1_release_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSkillReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSkillReleaseResponse) ProtoMessage() {}

func (x *ResolveSkillReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_release_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSkillReleaseResponse.ProtoReflect.Descriptor instead.
func (*ResolveSkillReleaseResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_release_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveSkillReleaseResponse) GetRelease() *SkillRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

var File_skill_v1_release_proto protoreflect.FileDescriptor

const file_skill_v1_release_proto_rawDesc = "" +
	"\n" +
	"\x16skill/v1/release.proto\x12\bskill.v1\x1a\x1faisphere/access/v1/access.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x14skill/v1/skill.proto\"\xcc\x01\n" +
	"\x19CreateSkillReleaseRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tB\x03\xe0A\x02R\aversion\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x03 \x01(\tR\tsourceRef\x123\n" +
	"\x13expected_commit_sha\x18\x04 \x01(\tB\x03\xe0A\x02R\x11expectedCommitSha\x12#\n" +
	"\rrelease_notes\x18\x05 \x01(\tR\freleaseNotes\"N\n" +
	"\x1aCreateSkillReleaseResponse\x120\n" +
	"\arelease\x18\x01 \x01(\v2\x16.skill.v1.SkillReleaseR\arelease\"P\n" +
	"\x16GetSkillReleaseRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tB\x03\xe0A\x02R\aversion\"K\n" +
	"\x17GetSkillReleaseResponse\x120\n" +
	"\arelease\x18\x01 \x01(\v2\x16.skill.v1.SkillReleaseR\arelease\"T\n" +
	"\x1aResolveSkillReleaseRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tB\x03\xe0A\x02R\aversion\"O\n" +
	"\x1bResolveSkillReleaseResponse\x120\n" +
	"\arelease\x18\x01 \x01(\v2\x16.skill.v1.SkillReleaseR\arelease2\xca\x05\n" +
	"\x13SkillReleaseService\x12\xe2\x01\n" +
	"\x12CreateSkillRelease\x12#.skill.v1.CreateSkillReleaseRequest\x1a$.skill.v1.CreateSkillReleaseResponse\"\x80\x01\x92\xf4\x18N\b\x03\x12&\n" +
	"\apublish\x12\fskill:{name}\x1a\vhub-service \x01\x1a\"\b\x01\x12\x18hub.skill.release.create\x1a\x04high\x82\xd3\xe4\x93\x02(:\x01*b\arelease\"\x1a/v1/skills/{name}/releases\x12\xd9\x01\n" +
	"\x0fGetSkillRelease\x12 .skill.v1.GetSkillReleaseRequest\x1a!.skill.v1.GetSkillReleaseResponse\"\x80\x01\x92\xf4\x18G\b\x03\x12#\n" +
	"\x04view\x12\fskill:{name}\x1a\vhub-service \x01\x1a\x1e\b\x01\x12\x15hub.skill.release.get\x1a\x03low\x82\xd3\xe4\x93\x02/b\arelease\x12$/v1/skills/{name}/releases/{version}\x12\xf1\x01\n" +
	"\x13ResolveSkillRelease\x12$.skill.v1.ResolveSkillReleaseRequest\x1a%.skill.v1.ResolveSkillReleaseResponse\"\x8c\x01\x92\xf4\x18K\b\x03\x12#\n" +
	"\x04view\x12\fskill:{name}\x1a\vhub-service \x01\x1a\"\b\x01\x12\x19hub.skill.release.resolve\x1a\x03low\x82\xd3\xe4\x93\x027b\arelease\x12,/v1/skills/{name}/releases/{version}:resolveB9Z7github.com/aisphereio/aisphere-hub/api/skill/v1;skillv1b\x06proto3"

var (
	file_skill_v1_release_proto_rawDescOnce sync.Once
	file_skill_v1_release_proto_rawDescData []byte
)

func file_skill_v1_release_proto_rawDescGZIP() []byte {
	file_skill_v1_release_proto_rawDescOnce.Do(func() {
		file_skill_v1_release_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_v1_release_proto_rawDesc), len(file_skill_v1_release_proto_rawDesc)))
	})
	return file_skill_v1_release_proto_rawDescData
}

var file_skill_v1_release_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_skill_v1_release_proto_goTypes = []any{
	(*CreateSkillReleaseRequest)(nil),   // 0: skill.v1.CreateSkillReleaseRequest
	(*CreateSkillReleaseResponse)(nil),  // 1: skill.v1.CreateSkillReleaseResponse
	(*GetSkillReleaseRequest)(nil),      // 2: skill.v1.GetSkillReleaseRequest
	(*GetSkillReleaseResponse)(nil),     // 3: skill.v1.GetSkillReleaseResponse
	(*ResolveSkillReleaseRequest)(nil),  // 4: skill.v1.ResolveSkillReleaseRequest
	(*ResolveSkillReleaseResponse)(nil), // 5: skill.v1.ResolveSkillReleaseResponse
	(*SkillRelease)(nil),                // 6: skill.v1.SkillRelease
}
var file_skill_v1_release_proto_depIdxs = []int32{
	6, // 0: skill.v1.CreateSkillReleaseResponse.release:type_name -> skill.v1.SkillRelease
	6, // 1: skill.v1.GetSkillReleaseResponse.release:type_name -> skill.v1.SkillRelease
	6, // 2: skill.v1.ResolveSkillReleaseResponse.release:type_name -> skill.v1.SkillRelease
	0, // 3: skill.v1.SkillReleaseService.CreateSkillRelease:input_type -> skill.v1.CreateSkillReleaseRequest
	2, // 4: skill.v1.SkillReleaseService.GetSkillRelease:input_type -> skill.v1.GetSkillReleaseRequest
	4, // 5: skill.v1.SkillReleaseService.ResolveSkillRelease:input_type -> skill.v1.ResolveSkillReleaseRequest
	1, // 6: skill.v1.SkillReleaseService.CreateSkillRelease:output_type -> skill.v1.CreateSkillReleaseResponse
	3, // 7: skill.v1.SkillReleaseService.GetSkillRelease:output_type -> skill.v1.GetSkillReleaseResponse
	5, // 8: skill.v1.SkillReleaseService.ResolveSkillRelease:output_type -> skill.v1.ResolveSkillReleaseResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_skill_v1_release_proto_init() }
func file_skill_v1_release_proto_init() {
	if File_skill_v1_release_proto != nil {
		return
	}
	file_skill_v1_skill_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_v1_release_proto_rawDesc), len(file_skill_v1_release_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skill_v1_release_proto_goTypes,
		DependencyIndexes: file_skill_v1_release_proto_depIdxs,
		MessageInfos:      file_skill_v1_release_proto_msgTypes,
	}.Build()
	File_skill_v1_release_proto = out.File
	file_skill_v1_release_proto_goTypes = nil
	file_skill_v1_release_proto_depIdxs = nil
}
