// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.2.1
// - protoc             (unknown)
// source: skill/v1/skill.proto

package skillv1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSkillServiceCreateSkill = "/skill.v1.SkillService/CreateSkill"
const OperationSkillServiceCreateSkillShare = "/skill.v1.SkillService/CreateSkillShare"
const OperationSkillServiceDeleteSkill = "/skill.v1.SkillService/DeleteSkill"
const OperationSkillServiceDeleteSkillShare = "/skill.v1.SkillService/DeleteSkillShare"
const OperationSkillServiceDownloadSkillVersion = "/skill.v1.SkillService/DownloadSkillVersion"
const OperationSkillServiceGetSkill = "/skill.v1.SkillService/GetSkill"
const OperationSkillServiceGetSkillVersion = "/skill.v1.SkillService/GetSkillVersion"
const OperationSkillServiceGetSkillVersionFile = "/skill.v1.SkillService/GetSkillVersionFile"
const OperationSkillServiceListSkillShares = "/skill.v1.SkillService/ListSkillShares"
const OperationSkillServiceListSkillVersionFiles = "/skill.v1.SkillService/ListSkillVersionFiles"
const OperationSkillServiceListSkillVersions = "/skill.v1.SkillService/ListSkillVersions"
const OperationSkillServiceListSkills = "/skill.v1.SkillService/ListSkills"
const OperationSkillServiceOfflineSkillVersion = "/skill.v1.SkillService/OfflineSkillVersion"
const OperationSkillServiceOnlineSkillVersion = "/skill.v1.SkillService/OnlineSkillVersion"
const OperationSkillServicePublishSkillVersion = "/skill.v1.SkillService/PublishSkillVersion"
const OperationSkillServiceSubmitSkillVersion = "/skill.v1.SkillService/SubmitSkillVersion"
const OperationSkillServiceUpdateSkill = "/skill.v1.SkillService/UpdateSkill"
const OperationSkillServiceUpdateSkillVisibility = "/skill.v1.SkillService/UpdateSkillVisibility"
const OperationSkillServiceUploadSkillPackage = "/skill.v1.SkillService/UploadSkillPackage"

type SkillServiceHTTPServer interface {
	// CreateSkill CreateSkill creates one canonical skill. The caller becomes the owner.
	CreateSkill(context.Context, *CreateSkillRequest) (*CreateSkillResponse, error)
	// CreateSkillShare CreateSkillShare grants a viewer or editor relation on the named
	// skill to a subject. Requires skill.edit. The relation field accepts
	// "viewer" or "editor"; passing "owner" returns INVALID_ARGUMENT.
	CreateSkillShare(context.Context, *CreateSkillShareRequest) (*SkillShare, error)
	// DeleteSkill DeleteSkill soft-deletes one canonical skill by name. Cascades to
	// versions and files. S3 objects are purged best-effort after the DB
	// transaction commits.
	DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillResponse, error)
	// DeleteSkillShare DeleteSkillShare revokes ALL relations between the named skill and
	// the named subject. Requires skill.edit.
	DeleteSkillShare(context.Context, *DeleteSkillShareRequest) (*DeleteSkillShareResponse, error)
	// DownloadSkillVersion DownloadSkillVersion returns the version package bytes. Use
	// if_none_match to leverage ETag-based 304 Not Modified.
	DownloadSkillVersion(context.Context, *DownloadSkillVersionRequest) (*SkillPackageDownload, error)
	// GetSkill GetSkill returns one canonical skill by name.
	GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error)
	// GetSkillVersion GetSkillVersion returns one version metadata record.
	GetSkillVersion(context.Context, *GetSkillVersionRequest) (*GetSkillVersionResponse, error)
	// GetSkillVersionFile GetSkillVersionFile returns one text or base64-encoded file content.
	GetSkillVersionFile(context.Context, *GetSkillVersionFileRequest) (*SkillFile, error)
	// ListSkillShares ListSkillShares lists subjects that have any relation on the named
	// skill. Requires skill.read (with ownership + public fallback).
	ListSkillShares(context.Context, *ListSkillSharesRequest) (*ListSkillSharesResponse, error)
	// ListSkillVersionFiles ListSkillVersionFiles lists files stored for one skill version.
	ListSkillVersionFiles(context.Context, *ListSkillVersionFilesRequest) (*ListSkillVersionFilesResponse, error)
	// ListSkillVersions ListSkillVersions lists versions of one canonical skill, oldest first.
	ListSkillVersions(context.Context, *ListSkillVersionsRequest) (*ListSkillVersionsResponse, error)
	// ListSkills ListSkills lists canonical skills visible to the caller. Visibility
	// rules: caller sees (a) skills they own, (b) skills shared with them
	// via accessx grants, (c) skills with visibility=public.
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	// OfflineSkillVersion OfflineSkillVersion removes one online version from catalog/runtime use.
	OfflineSkillVersion(context.Context, *OfflineSkillVersionRequest) (*OfflineSkillVersionResponse, error)
	// OnlineSkillVersion OnlineSkillVersion makes one published version consumable by
	// catalog/runtime. Any previously-online version of the same skill is
	// automatically demoted to published.
	OnlineSkillVersion(context.Context, *OnlineSkillVersionRequest) (*OnlineSkillVersionResponse, error)
	// PublishSkillVersion PublishSkillVersion marks a submitted version as published.
	PublishSkillVersion(context.Context, *PublishSkillVersionRequest) (*PublishSkillVersionResponse, error)
	// SubmitSkillVersion SubmitSkillVersion marks a draft version ready for publish.
	SubmitSkillVersion(context.Context, *SubmitSkillVersionRequest) (*SubmitSkillVersionResponse, error)
	// UpdateSkill UpdateSkill updates mutable fields of one canonical skill. owner_id /
	// visibility / status are NOT updated by this RPC — they require
	// separate lifecycle endpoints.
	UpdateSkill(context.Context, *UpdateSkillRequest) (*UpdateSkillResponse, error)
	// UpdateSkillVisibility UpdateSkillVisibility changes the access visibility of one canonical
	// skill. This endpoint is the contract-backed path for public/private
	// toggles; subject-specific sharing remains under Skill share RPCs.
	UpdateSkillVisibility(context.Context, *UpdateSkillVisibilityRequest) (*UpdateSkillVisibilityResponse, error)
	// UploadSkillPackage UploadSkillPackage imports a zipped Skill package into a new or
	// existing version. The zip must contain SKILL.md with YAML front-matter
	// declaring name, description, version. Other files become version
	// files; binary files are base64-encoded in the DB content column.
	UploadSkillPackage(context.Context, *UploadSkillPackageRequest) (*UploadSkillPackageResponse, error)
}

func RegisterSkillServiceHTTPServer(s *http.Server, srv SkillServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("DELETE", "/v1/skills/{name}", _SkillService_DeleteSkill0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/skills/{name}/shares/{subject_type}/{subject_id}", _SkillService_DeleteSkillShare0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/skills", _SkillService_ListSkills0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/skills/{name}/shares", _SkillService_ListSkillShares0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/skills/{name}/versions", _SkillService_ListSkillVersions0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/skills/{name}", _SkillService_GetSkill0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/skills/{name}/versions/{version}/download", _SkillService_DownloadSkillVersion0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/skills/{name}/versions/{version}/file", _SkillService_GetSkillVersionFile0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/skills/{name}/versions/{version}/files", _SkillService_ListSkillVersionFiles0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/skills/{name}/versions/{version}", _SkillService_GetSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/skills", _SkillService_CreateSkill0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/skills:upload", _SkillService_UploadSkillPackage0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/skills/{name}/shares", _SkillService_CreateSkillShare0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/skills/{name}:visibility", _SkillService_UpdateSkillVisibility0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/skills/{name}/versions/{version}:offline", _SkillService_OfflineSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/skills/{name}/versions/{version}:online", _SkillService_OnlineSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/skills/{name}/versions/{version}:publish", _SkillService_PublishSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/skills/{name}/versions/{version}:submit", _SkillService_SubmitSkillVersion0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/skills/{name}", _SkillService_UpdateSkill0_HTTP_Handler(srv))
}

func _SkillService_DeleteSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSkillRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceDeleteSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSkill(ctx, req.(*DeleteSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSkillResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_DeleteSkillShare0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSkillShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceDeleteSkillShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSkillShare(ctx, req.(*DeleteSkillShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSkillShareResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListSkills0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListSkills)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkills(ctx, req.(*ListSkillsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillsResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListSkillShares0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillSharesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListSkillShares)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkillShares(ctx, req.(*ListSkillSharesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillSharesResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListSkillVersions0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillVersionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListSkillVersions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkillVersions(ctx, req.(*ListSkillVersionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillVersionsResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_GetSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSkillRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGetSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSkill(ctx, req.(*GetSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSkillResponse)
		return ctx.Result(200, reply.Skill)
	}
}

func _SkillService_DownloadSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DownloadSkillVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceDownloadSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DownloadSkillVersion(ctx, req.(*DownloadSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillPackageDownload)
		return ctx.Result(200, reply)
	}
}

func _SkillService_GetSkillVersionFile0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSkillVersionFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGetSkillVersionFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSkillVersionFile(ctx, req.(*GetSkillVersionFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillFile)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListSkillVersionFiles0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillVersionFilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListSkillVersionFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkillVersionFiles(ctx, req.(*ListSkillVersionFilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillVersionFilesResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_GetSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSkillVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGetSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSkillVersion(ctx, req.(*GetSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSkillVersionResponse)
		return ctx.Result(200, reply.Version)
	}
}

func _SkillService_CreateSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSkillRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceCreateSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSkill(ctx, req.(*CreateSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSkillResponse)
		return ctx.Result(200, reply.Skill)
	}
}

func _SkillService_UploadSkillPackage0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadSkillPackageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceUploadSkillPackage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadSkillPackage(ctx, req.(*UploadSkillPackageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadSkillPackageResponse)
		return ctx.Result(200, reply.Version)
	}
}

func _SkillService_CreateSkillShare0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSkillShareRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceCreateSkillShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSkillShare(ctx, req.(*CreateSkillShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillShare)
		return ctx.Result(200, reply)
	}
}

func _SkillService_UpdateSkillVisibility0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSkillVisibilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceUpdateSkillVisibility)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSkillVisibility(ctx, req.(*UpdateSkillVisibilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSkillVisibilityResponse)
		return ctx.Result(200, reply.Skill)
	}
}

func _SkillService_OfflineSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OfflineSkillVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceOfflineSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OfflineSkillVersion(ctx, req.(*OfflineSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OfflineSkillVersionResponse)
		return ctx.Result(200, reply.Version)
	}
}

func _SkillService_OnlineSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OnlineSkillVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceOnlineSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OnlineSkillVersion(ctx, req.(*OnlineSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OnlineSkillVersionResponse)
		return ctx.Result(200, reply.Version)
	}
}

func _SkillService_PublishSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishSkillVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServicePublishSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishSkillVersion(ctx, req.(*PublishSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishSkillVersionResponse)
		return ctx.Result(200, reply.Version)
	}
}

func _SkillService_SubmitSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitSkillVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceSubmitSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitSkillVersion(ctx, req.(*SubmitSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitSkillVersionResponse)
		return ctx.Result(200, reply.Version)
	}
}

func _SkillService_UpdateSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSkillRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceUpdateSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSkill(ctx, req.(*UpdateSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSkillResponse)
		return ctx.Result(200, reply.Skill)
	}
}

type SkillServiceHTTPClient interface {
	// CreateSkill CreateSkill creates one canonical skill. The caller becomes the owner.
	CreateSkill(ctx context.Context, req *CreateSkillRequest, opts ...http.CallOption) (rsp *CreateSkillResponse, err error)
	// CreateSkillShare CreateSkillShare grants a viewer or editor relation on the named
	// skill to a subject. Requires skill.edit. The relation field accepts
	// "viewer" or "editor"; passing "owner" returns INVALID_ARGUMENT.
	CreateSkillShare(ctx context.Context, req *CreateSkillShareRequest, opts ...http.CallOption) (rsp *SkillShare, err error)
	// DeleteSkill DeleteSkill soft-deletes one canonical skill by name. Cascades to
	// versions and files. S3 objects are purged best-effort after the DB
	// transaction commits.
	DeleteSkill(ctx context.Context, req *DeleteSkillRequest, opts ...http.CallOption) (rsp *DeleteSkillResponse, err error)
	// DeleteSkillShare DeleteSkillShare revokes ALL relations between the named skill and
	// the named subject. Requires skill.edit.
	DeleteSkillShare(ctx context.Context, req *DeleteSkillShareRequest, opts ...http.CallOption) (rsp *DeleteSkillShareResponse, err error)
	// DownloadSkillVersion DownloadSkillVersion returns the version package bytes. Use
	// if_none_match to leverage ETag-based 304 Not Modified.
	DownloadSkillVersion(ctx context.Context, req *DownloadSkillVersionRequest, opts ...http.CallOption) (rsp *SkillPackageDownload, err error)
	// GetSkill GetSkill returns one canonical skill by name.
	GetSkill(ctx context.Context, req *GetSkillRequest, opts ...http.CallOption) (rsp *GetSkillResponse, err error)
	// GetSkillVersion GetSkillVersion returns one version metadata record.
	GetSkillVersion(ctx context.Context, req *GetSkillVersionRequest, opts ...http.CallOption) (rsp *GetSkillVersionResponse, err error)
	// GetSkillVersionFile GetSkillVersionFile returns one text or base64-encoded file content.
	GetSkillVersionFile(ctx context.Context, req *GetSkillVersionFileRequest, opts ...http.CallOption) (rsp *SkillFile, err error)
	// ListSkillShares ListSkillShares lists subjects that have any relation on the named
	// skill. Requires skill.read (with ownership + public fallback).
	ListSkillShares(ctx context.Context, req *ListSkillSharesRequest, opts ...http.CallOption) (rsp *ListSkillSharesResponse, err error)
	// ListSkillVersionFiles ListSkillVersionFiles lists files stored for one skill version.
	ListSkillVersionFiles(ctx context.Context, req *ListSkillVersionFilesRequest, opts ...http.CallOption) (rsp *ListSkillVersionFilesResponse, err error)
	// ListSkillVersions ListSkillVersions lists versions of one canonical skill, oldest first.
	ListSkillVersions(ctx context.Context, req *ListSkillVersionsRequest, opts ...http.CallOption) (rsp *ListSkillVersionsResponse, err error)
	// ListSkills ListSkills lists canonical skills visible to the caller. Visibility
	// rules: caller sees (a) skills they own, (b) skills shared with them
	// via accessx grants, (c) skills with visibility=public.
	ListSkills(ctx context.Context, req *ListSkillsRequest, opts ...http.CallOption) (rsp *ListSkillsResponse, err error)
	// OfflineSkillVersion OfflineSkillVersion removes one online version from catalog/runtime use.
	OfflineSkillVersion(ctx context.Context, req *OfflineSkillVersionRequest, opts ...http.CallOption) (rsp *OfflineSkillVersionResponse, err error)
	// OnlineSkillVersion OnlineSkillVersion makes one published version consumable by
	// catalog/runtime. Any previously-online version of the same skill is
	// automatically demoted to published.
	OnlineSkillVersion(ctx context.Context, req *OnlineSkillVersionRequest, opts ...http.CallOption) (rsp *OnlineSkillVersionResponse, err error)
	// PublishSkillVersion PublishSkillVersion marks a submitted version as published.
	PublishSkillVersion(ctx context.Context, req *PublishSkillVersionRequest, opts ...http.CallOption) (rsp *PublishSkillVersionResponse, err error)
	// SubmitSkillVersion SubmitSkillVersion marks a draft version ready for publish.
	SubmitSkillVersion(ctx context.Context, req *SubmitSkillVersionRequest, opts ...http.CallOption) (rsp *SubmitSkillVersionResponse, err error)
	// UpdateSkill UpdateSkill updates mutable fields of one canonical skill. owner_id /
	// visibility / status are NOT updated by this RPC — they require
	// separate lifecycle endpoints.
	UpdateSkill(ctx context.Context, req *UpdateSkillRequest, opts ...http.CallOption) (rsp *UpdateSkillResponse, err error)
	// UpdateSkillVisibility UpdateSkillVisibility changes the access visibility of one canonical
	// skill. This endpoint is the contract-backed path for public/private
	// toggles; subject-specific sharing remains under Skill share RPCs.
	UpdateSkillVisibility(ctx context.Context, req *UpdateSkillVisibilityRequest, opts ...http.CallOption) (rsp *UpdateSkillVisibilityResponse, err error)
	// UploadSkillPackage UploadSkillPackage imports a zipped Skill package into a new or
	// existing version. The zip must contain SKILL.md with YAML front-matter
	// declaring name, description, version. Other files become version
	// files; binary files are base64-encoded in the DB content column.
	UploadSkillPackage(ctx context.Context, req *UploadSkillPackageRequest, opts ...http.CallOption) (rsp *UploadSkillPackageResponse, err error)
}

type SkillServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSkillServiceHTTPClient(client *http.Client) SkillServiceHTTPClient {
	return &SkillServiceHTTPClientImpl{client}
}

// CreateSkill CreateSkill creates one canonical skill. The caller becomes the owner.
func (c *SkillServiceHTTPClientImpl) CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...http.CallOption) (*CreateSkillResponse, error) {
	var out CreateSkillResponse
	pattern := "/v1/skills"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceCreateSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Skill, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSkillShare CreateSkillShare grants a viewer or editor relation on the named
// skill to a subject. Requires skill.edit. The relation field accepts
// "viewer" or "editor"; passing "owner" returns INVALID_ARGUMENT.
func (c *SkillServiceHTTPClientImpl) CreateSkillShare(ctx context.Context, in *CreateSkillShareRequest, opts ...http.CallOption) (*SkillShare, error) {
	var out SkillShare
	pattern := "/v1/skills/{name}/shares"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceCreateSkillShare),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSkill DeleteSkill soft-deletes one canonical skill by name. Cascades to
// versions and files. S3 objects are purged best-effort after the DB
// transaction commits.
func (c *SkillServiceHTTPClientImpl) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...http.CallOption) (*DeleteSkillResponse, error) {
	var out DeleteSkillResponse
	pattern := "/v1/skills/{name}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceDeleteSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSkillShare DeleteSkillShare revokes ALL relations between the named skill and
// the named subject. Requires skill.edit.
func (c *SkillServiceHTTPClientImpl) DeleteSkillShare(ctx context.Context, in *DeleteSkillShareRequest, opts ...http.CallOption) (*DeleteSkillShareResponse, error) {
	var out DeleteSkillShareResponse
	pattern := "/v1/skills/{name}/shares/{subject_type}/{subject_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceDeleteSkillShare),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DownloadSkillVersion DownloadSkillVersion returns the version package bytes. Use
// if_none_match to leverage ETag-based 304 Not Modified.
func (c *SkillServiceHTTPClientImpl) DownloadSkillVersion(ctx context.Context, in *DownloadSkillVersionRequest, opts ...http.CallOption) (*SkillPackageDownload, error) {
	var out SkillPackageDownload
	pattern := "/v1/skills/{name}/versions/{version}/download"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceDownloadSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSkill GetSkill returns one canonical skill by name.
func (c *SkillServiceHTTPClientImpl) GetSkill(ctx context.Context, in *GetSkillRequest, opts ...http.CallOption) (*GetSkillResponse, error) {
	var out GetSkillResponse
	pattern := "/v1/skills/{name}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceGetSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out.Skill, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSkillVersion GetSkillVersion returns one version metadata record.
func (c *SkillServiceHTTPClientImpl) GetSkillVersion(ctx context.Context, in *GetSkillVersionRequest, opts ...http.CallOption) (*GetSkillVersionResponse, error) {
	var out GetSkillVersionResponse
	pattern := "/v1/skills/{name}/versions/{version}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceGetSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out.Version, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSkillVersionFile GetSkillVersionFile returns one text or base64-encoded file content.
func (c *SkillServiceHTTPClientImpl) GetSkillVersionFile(ctx context.Context, in *GetSkillVersionFileRequest, opts ...http.CallOption) (*SkillFile, error) {
	var out SkillFile
	pattern := "/v1/skills/{name}/versions/{version}/file"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceGetSkillVersionFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkillShares ListSkillShares lists subjects that have any relation on the named
// skill. Requires skill.read (with ownership + public fallback).
func (c *SkillServiceHTTPClientImpl) ListSkillShares(ctx context.Context, in *ListSkillSharesRequest, opts ...http.CallOption) (*ListSkillSharesResponse, error) {
	var out ListSkillSharesResponse
	pattern := "/v1/skills/{name}/shares"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListSkillShares),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkillVersionFiles ListSkillVersionFiles lists files stored for one skill version.
func (c *SkillServiceHTTPClientImpl) ListSkillVersionFiles(ctx context.Context, in *ListSkillVersionFilesRequest, opts ...http.CallOption) (*ListSkillVersionFilesResponse, error) {
	var out ListSkillVersionFilesResponse
	pattern := "/v1/skills/{name}/versions/{version}/files"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListSkillVersionFiles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkillVersions ListSkillVersions lists versions of one canonical skill, oldest first.
func (c *SkillServiceHTTPClientImpl) ListSkillVersions(ctx context.Context, in *ListSkillVersionsRequest, opts ...http.CallOption) (*ListSkillVersionsResponse, error) {
	var out ListSkillVersionsResponse
	pattern := "/v1/skills/{name}/versions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListSkillVersions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkills ListSkills lists canonical skills visible to the caller. Visibility
// rules: caller sees (a) skills they own, (b) skills shared with them
// via accessx grants, (c) skills with visibility=public.
func (c *SkillServiceHTTPClientImpl) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...http.CallOption) (*ListSkillsResponse, error) {
	var out ListSkillsResponse
	pattern := "/v1/skills"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListSkills),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// OfflineSkillVersion OfflineSkillVersion removes one online version from catalog/runtime use.
func (c *SkillServiceHTTPClientImpl) OfflineSkillVersion(ctx context.Context, in *OfflineSkillVersionRequest, opts ...http.CallOption) (*OfflineSkillVersionResponse, error) {
	var out OfflineSkillVersionResponse
	pattern := "/v1/skills/{name}/versions/{version}:offline"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceOfflineSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Version, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// OnlineSkillVersion OnlineSkillVersion makes one published version consumable by
// catalog/runtime. Any previously-online version of the same skill is
// automatically demoted to published.
func (c *SkillServiceHTTPClientImpl) OnlineSkillVersion(ctx context.Context, in *OnlineSkillVersionRequest, opts ...http.CallOption) (*OnlineSkillVersionResponse, error) {
	var out OnlineSkillVersionResponse
	pattern := "/v1/skills/{name}/versions/{version}:online"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceOnlineSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Version, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PublishSkillVersion PublishSkillVersion marks a submitted version as published.
func (c *SkillServiceHTTPClientImpl) PublishSkillVersion(ctx context.Context, in *PublishSkillVersionRequest, opts ...http.CallOption) (*PublishSkillVersionResponse, error) {
	var out PublishSkillVersionResponse
	pattern := "/v1/skills/{name}/versions/{version}:publish"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServicePublishSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Version, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitSkillVersion SubmitSkillVersion marks a draft version ready for publish.
func (c *SkillServiceHTTPClientImpl) SubmitSkillVersion(ctx context.Context, in *SubmitSkillVersionRequest, opts ...http.CallOption) (*SubmitSkillVersionResponse, error) {
	var out SubmitSkillVersionResponse
	pattern := "/v1/skills/{name}/versions/{version}:submit"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceSubmitSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Version, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSkill UpdateSkill updates mutable fields of one canonical skill. owner_id /
// visibility / status are NOT updated by this RPC — they require
// separate lifecycle endpoints.
func (c *SkillServiceHTTPClientImpl) UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...http.CallOption) (*UpdateSkillResponse, error) {
	var out UpdateSkillResponse
	pattern := "/v1/skills/{name}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceUpdateSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out.Skill, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSkillVisibility UpdateSkillVisibility changes the access visibility of one canonical
// skill. This endpoint is the contract-backed path for public/private
// toggles; subject-specific sharing remains under Skill share RPCs.
func (c *SkillServiceHTTPClientImpl) UpdateSkillVisibility(ctx context.Context, in *UpdateSkillVisibilityRequest, opts ...http.CallOption) (*UpdateSkillVisibilityResponse, error) {
	var out UpdateSkillVisibilityResponse
	pattern := "/v1/skills/{name}:visibility"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceUpdateSkillVisibility),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Skill, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadSkillPackage UploadSkillPackage imports a zipped Skill package into a new or
// existing version. The zip must contain SKILL.md with YAML front-matter
// declaring name, description, version. Other files become version
// files; binary files are base64-encoded in the DB content column.
func (c *SkillServiceHTTPClientImpl) UploadSkillPackage(ctx context.Context, in *UploadSkillPackageRequest, opts ...http.CallOption) (*UploadSkillPackageResponse, error) {
	var out UploadSkillPackageResponse
	pattern := "/v1/skills:upload"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceUploadSkillPackage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Version, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
