// Code generated by protoc-gen-go-gateway. DO NOT EDIT.
// versions:
// - protoc-gen-go-gateway v0.4.18
// source: skill/v1/skill.proto

package skillv1

import (
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
)

func SkillServiceGatewayManifest() gatewayx.Manifest {
	return gatewayx.Manifest{
		Service:   "skill-service",
		Namespace: "aisphere",
		Routes: []gatewayx.GatewayRoute{
			{
				ID:       "skill.create.skill",
				Method:   "POST",
				Path:     "/v1/skills",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/CreateSkill"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.import.skill.archive",
				Method:   "POST",
				Path:     "/v1/skills:importArchive",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ImportSkillArchive"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.list.skills",
				Method:   "GET",
				Path:     "/v1/skills",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ListSkills"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.get.skill",
				Method:   "GET",
				Path:     "/v1/skills/{name}",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/GetSkill"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.update.skill",
				Method:   "PUT",
				Path:     "/v1/skills/{name}",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/UpdateSkill"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.update.skill.visibility",
				Method:   "POST",
				Path:     "/v1/skills/{name}:visibility",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/UpdateSkillVisibility"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.delete.skill",
				Method:   "DELETE",
				Path:     "/v1/skills/{name}",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/DeleteSkill"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.list.skill.shares",
				Method:   "GET",
				Path:     "/v1/skills/{name}/shares",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ListSkillShares"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.create.skill.share",
				Method:   "POST",
				Path:     "/v1/skills/{name}/shares",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/CreateSkillShare"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.delete.skill.share",
				Method:   "DELETE",
				Path:     "/v1/skills/{name}/shares/{relation}/{subject_type}/{subject_id}",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/DeleteSkillShare"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.create.pull.request",
				Method:   "POST",
				Path:     "/v1/skills/{name}/pull-requests",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/CreatePullRequest"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.list.pull.requests",
				Method:   "GET",
				Path:     "/v1/skills/{name}/pull-requests",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ListPullRequests"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.get.pull.request",
				Method:   "GET",
				Path:     "/v1/skills/{name}/pull-requests/{id}",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/GetPullRequest"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.review.pull.request",
				Method:   "POST",
				Path:     "/v1/skills/{name}/pull-requests/{id}:review",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ReviewPullRequest"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.close.pull.request",
				Method:   "POST",
				Path:     "/v1/skills/{name}/pull-requests/{id}:close",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ClosePullRequest"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.merge.pull.request",
				Method:   "POST",
				Path:     "/v1/skills/{name}/pull-requests/{id}:merge",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/MergePullRequest"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.list.skill.releases",
				Method:   "GET",
				Path:     "/v1/skills/{name}/releases",
				Upstream: gatewayx.UpstreamRef{Service: "hub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ListSkillReleases"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
		},
	}
}

func SkillServiceGatewayBindCreateSkill(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*CreateSkillRequest, error) {
	out := &CreateSkillRequest{}
	if v, ok := req.Body.(*CreateSkillRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(CreateSkillRequest); ok {
		out = &v
	}
	return out, nil
}

func SkillServiceGatewayBindImportSkillArchive(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ImportSkillArchiveRequest, error) {
	out := &ImportSkillArchiveRequest{}
	if v, ok := req.Body.(*ImportSkillArchiveRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ImportSkillArchiveRequest); ok {
		out = &v
	}
	return out, nil
}

func SkillServiceGatewayBindListSkills(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListSkillsRequest, error) {
	out := &ListSkillsRequest{}
	if v, ok := req.Body.(*ListSkillsRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListSkillsRequest); ok {
		out = &v
	}
	return out, nil
}

func SkillServiceGatewayBindGetSkill(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetSkillRequest, error) {
	out := &GetSkillRequest{}
	if v, ok := req.Body.(*GetSkillRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetSkillRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func SkillServiceGatewayBindUpdateSkill(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UpdateSkillRequest, error) {
	out := &UpdateSkillRequest{}
	if v, ok := req.Body.(*UpdateSkillRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UpdateSkillRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func SkillServiceGatewayBindUpdateSkillVisibility(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UpdateSkillVisibilityRequest, error) {
	out := &UpdateSkillVisibilityRequest{}
	if v, ok := req.Body.(*UpdateSkillVisibilityRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UpdateSkillVisibilityRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func SkillServiceGatewayBindDeleteSkill(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*DeleteSkillRequest, error) {
	out := &DeleteSkillRequest{}
	if v, ok := req.Body.(*DeleteSkillRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(DeleteSkillRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func SkillServiceGatewayBindListSkillShares(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListSkillSharesRequest, error) {
	out := &ListSkillSharesRequest{}
	if v, ok := req.Body.(*ListSkillSharesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListSkillSharesRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func SkillServiceGatewayBindCreateSkillShare(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*CreateSkillShareRequest, error) {
	out := &CreateSkillShareRequest{}
	if v, ok := req.Body.(*CreateSkillShareRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(CreateSkillShareRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func SkillServiceGatewayBindDeleteSkillShare(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*DeleteSkillShareRequest, error) {
	out := &DeleteSkillShareRequest{}
	if v, ok := req.Body.(*DeleteSkillShareRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(DeleteSkillShareRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["relation"]; v != "" {
		out.Relation = v
	}
	if v := match.Params["subject_type"]; v != "" {
		out.SubjectType = v
	}
	if v := match.Params["subject_id"]; v != "" {
		out.SubjectId = v
	}
	return out, nil
}

func SkillServiceGatewayBindCreatePullRequest(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*CreatePullRequestRequest, error) {
	out := &CreatePullRequestRequest{}
	if v, ok := req.Body.(*CreatePullRequestRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(CreatePullRequestRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func SkillServiceGatewayBindListPullRequests(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListPullRequestsRequest, error) {
	out := &ListPullRequestsRequest{}
	if v, ok := req.Body.(*ListPullRequestsRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListPullRequestsRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func SkillServiceGatewayBindGetPullRequest(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetPullRequestRequest, error) {
	out := &GetPullRequestRequest{}
	if v, ok := req.Body.(*GetPullRequestRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetPullRequestRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["id"]; v != "" {
		out.Id = v
	}
	return out, nil
}

func SkillServiceGatewayBindReviewPullRequest(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ReviewPullRequestRequest, error) {
	out := &ReviewPullRequestRequest{}
	if v, ok := req.Body.(*ReviewPullRequestRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ReviewPullRequestRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["id"]; v != "" {
		out.Id = v
	}
	return out, nil
}

func SkillServiceGatewayBindClosePullRequest(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ClosePullRequestRequest, error) {
	out := &ClosePullRequestRequest{}
	if v, ok := req.Body.(*ClosePullRequestRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ClosePullRequestRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["id"]; v != "" {
		out.Id = v
	}
	return out, nil
}

func SkillServiceGatewayBindMergePullRequest(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*MergePullRequestRequest, error) {
	out := &MergePullRequestRequest{}
	if v, ok := req.Body.(*MergePullRequestRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(MergePullRequestRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["id"]; v != "" {
		out.Id = v
	}
	return out, nil
}

func SkillServiceGatewayBindListSkillReleases(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListSkillReleasesRequest, error) {
	out := &ListSkillReleasesRequest{}
	if v, ok := req.Body.(*ListSkillReleasesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListSkillReleasesRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

func RegisterSkillServiceGatewayInvokers(registry *gatewayx.InvokerRegistry, client SkillServiceClient) error {
	if err := registry.Register("/skill.v1.SkillService/CreateSkill", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindCreateSkill, client.CreateSkill)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ImportSkillArchive", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindImportSkillArchive, client.ImportSkillArchive)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ListSkills", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindListSkills, client.ListSkills)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/GetSkill", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindGetSkill, client.GetSkill)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/UpdateSkill", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindUpdateSkill, client.UpdateSkill)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/UpdateSkillVisibility", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindUpdateSkillVisibility, client.UpdateSkillVisibility)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/DeleteSkill", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindDeleteSkill, client.DeleteSkill)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ListSkillShares", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindListSkillShares, client.ListSkillShares)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/CreateSkillShare", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindCreateSkillShare, client.CreateSkillShare)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/DeleteSkillShare", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindDeleteSkillShare, client.DeleteSkillShare)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/CreatePullRequest", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindCreatePullRequest, client.CreatePullRequest)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ListPullRequests", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindListPullRequests, client.ListPullRequests)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/GetPullRequest", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindGetPullRequest, client.GetPullRequest)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ReviewPullRequest", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindReviewPullRequest, client.ReviewPullRequest)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ClosePullRequest", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindClosePullRequest, client.ClosePullRequest)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/MergePullRequest", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindMergePullRequest, client.MergePullRequest)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ListSkillReleases", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindListSkillReleases, client.ListSkillReleases)); err != nil {
		return err
	}
	return nil
}
