// Code generated by protoc-gen-go-gateway. DO NOT EDIT.
// versions:
// - protoc-gen-go-gateway v0.2.1
// source: skill/v1/skill.proto

package skillv1

import (
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
)

// SkillServiceGatewayManifest returns the generated Gateway route manifest for skill.v1.SkillService.
func SkillServiceGatewayManifest() gatewayx.Manifest {
	return gatewayx.Manifest{
		Service:   "skill-service",
		Namespace: "aisphere",
		Routes: []gatewayx.GatewayRoute{
			{
				ID:       "skill.create.skill",
				Method:   "POST",
				Path:     "/v1/skills",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/CreateSkill"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.update.skill",
				Method:   "PUT",
				Path:     "/v1/skills/{name}",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/UpdateSkill"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.update.skill.visibility",
				Method:   "POST",
				Path:     "/v1/skills/{name}:visibility",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/UpdateSkillVisibility"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.list.skills",
				Method:   "GET",
				Path:     "/v1/skills",
				Upstream: gatewayx.UpstreamRef{Service: "skill-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ListSkills"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.get.skill",
				Method:   "GET",
				Path:     "/v1/skills/{name}",
				Upstream: gatewayx.UpstreamRef{Service: "skill-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/GetSkill"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.delete.skill",
				Method:   "DELETE",
				Path:     "/v1/skills/{name}",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/DeleteSkill"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.upload.skill.package",
				Method:   "POST",
				Path:     "/v1/skills:upload",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/UploadSkillPackage"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.list.skill.versions",
				Method:   "GET",
				Path:     "/v1/skills/{name}/versions",
				Upstream: gatewayx.UpstreamRef{Service: "skill-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ListSkillVersions"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.get.skill.version",
				Method:   "GET",
				Path:     "/v1/skills/{name}/versions/{version}",
				Upstream: gatewayx.UpstreamRef{Service: "skill-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/GetSkillVersion"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.submit.skill.version",
				Method:   "POST",
				Path:     "/v1/skills/{name}/versions/{version}:submit",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/SubmitSkillVersion"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.publish.skill.version",
				Method:   "POST",
				Path:     "/v1/skills/{name}/versions/{version}:publish",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/PublishSkillVersion"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.online.skill.version",
				Method:   "POST",
				Path:     "/v1/skills/{name}/versions/{version}:online",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/OnlineSkillVersion"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.offline.skill.version",
				Method:   "POST",
				Path:     "/v1/skills/{name}/versions/{version}:offline",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/OfflineSkillVersion"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.download.skill.version",
				Method:   "GET",
				Path:     "/v1/skills/{name}/versions/{version}/download",
				Upstream: gatewayx.UpstreamRef{Service: "skill-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/DownloadSkillVersion"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.list.skill.version.files",
				Method:   "GET",
				Path:     "/v1/skills/{name}/versions/{version}/files",
				Upstream: gatewayx.UpstreamRef{Service: "skill-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ListSkillVersionFiles"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.get.skill.version.file",
				Method:   "GET",
				Path:     "/v1/skills/{name}/versions/{version}/file",
				Upstream: gatewayx.UpstreamRef{Service: "skill-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/GetSkillVersionFile"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.list.skill.shares",
				Method:   "GET",
				Path:     "/v1/skills/{name}/shares",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/ListSkillShares"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.create.skill.share",
				Method:   "POST",
				Path:     "/v1/skills/{name}/shares",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/CreateSkillShare"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "skill.delete.skill.share",
				Method:   "DELETE",
				Path:     "/v1/skills/{name}/shares/{subject_type}/{subject_id}",
				Upstream: gatewayx.UpstreamRef{Service: "aihub-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/skill.v1.SkillService/DeleteSkillShare"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
		},
	}
}

// SkillServiceGatewayBindCreateSkill binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/CreateSkill.
func SkillServiceGatewayBindCreateSkill(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*CreateSkillRequest, error) {
	out := &CreateSkillRequest{}
	if v, ok := req.Body.(*CreateSkillRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(CreateSkillRequest); ok {
		out = &v
	}
	return out, nil
}

// SkillServiceGatewayBindUpdateSkill binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/UpdateSkill.
func SkillServiceGatewayBindUpdateSkill(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UpdateSkillRequest, error) {
	out := &UpdateSkillRequest{}
	if v, ok := req.Body.(*UpdateSkillRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UpdateSkillRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

// SkillServiceGatewayBindUpdateSkillVisibility binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/UpdateSkillVisibility.
func SkillServiceGatewayBindUpdateSkillVisibility(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UpdateSkillVisibilityRequest, error) {
	out := &UpdateSkillVisibilityRequest{}
	if v, ok := req.Body.(*UpdateSkillVisibilityRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UpdateSkillVisibilityRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

// SkillServiceGatewayBindListSkills binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/ListSkills.
func SkillServiceGatewayBindListSkills(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListSkillsRequest, error) {
	out := &ListSkillsRequest{}
	if v, ok := req.Body.(*ListSkillsRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListSkillsRequest); ok {
		out = &v
	}
	return out, nil
}

// SkillServiceGatewayBindGetSkill binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/GetSkill.
func SkillServiceGatewayBindGetSkill(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetSkillRequest, error) {
	out := &GetSkillRequest{}
	if v, ok := req.Body.(*GetSkillRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetSkillRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

// SkillServiceGatewayBindDeleteSkill binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/DeleteSkill.
func SkillServiceGatewayBindDeleteSkill(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*DeleteSkillRequest, error) {
	out := &DeleteSkillRequest{}
	if v, ok := req.Body.(*DeleteSkillRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(DeleteSkillRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

// SkillServiceGatewayBindUploadSkillPackage binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/UploadSkillPackage.
func SkillServiceGatewayBindUploadSkillPackage(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UploadSkillPackageRequest, error) {
	out := &UploadSkillPackageRequest{}
	if v, ok := req.Body.(*UploadSkillPackageRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UploadSkillPackageRequest); ok {
		out = &v
	}
	return out, nil
}

// SkillServiceGatewayBindListSkillVersions binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/ListSkillVersions.
func SkillServiceGatewayBindListSkillVersions(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListSkillVersionsRequest, error) {
	out := &ListSkillVersionsRequest{}
	if v, ok := req.Body.(*ListSkillVersionsRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListSkillVersionsRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

// SkillServiceGatewayBindGetSkillVersion binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/GetSkillVersion.
func SkillServiceGatewayBindGetSkillVersion(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetSkillVersionRequest, error) {
	out := &GetSkillVersionRequest{}
	if v, ok := req.Body.(*GetSkillVersionRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetSkillVersionRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["version"]; v != "" {
		out.Version = v
	}
	return out, nil
}

// SkillServiceGatewayBindSubmitSkillVersion binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/SubmitSkillVersion.
func SkillServiceGatewayBindSubmitSkillVersion(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*SubmitSkillVersionRequest, error) {
	out := &SubmitSkillVersionRequest{}
	if v, ok := req.Body.(*SubmitSkillVersionRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(SubmitSkillVersionRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["version"]; v != "" {
		out.Version = v
	}
	return out, nil
}

// SkillServiceGatewayBindPublishSkillVersion binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/PublishSkillVersion.
func SkillServiceGatewayBindPublishSkillVersion(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*PublishSkillVersionRequest, error) {
	out := &PublishSkillVersionRequest{}
	if v, ok := req.Body.(*PublishSkillVersionRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(PublishSkillVersionRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["version"]; v != "" {
		out.Version = v
	}
	return out, nil
}

// SkillServiceGatewayBindOnlineSkillVersion binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/OnlineSkillVersion.
func SkillServiceGatewayBindOnlineSkillVersion(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*OnlineSkillVersionRequest, error) {
	out := &OnlineSkillVersionRequest{}
	if v, ok := req.Body.(*OnlineSkillVersionRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(OnlineSkillVersionRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["version"]; v != "" {
		out.Version = v
	}
	return out, nil
}

// SkillServiceGatewayBindOfflineSkillVersion binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/OfflineSkillVersion.
func SkillServiceGatewayBindOfflineSkillVersion(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*OfflineSkillVersionRequest, error) {
	out := &OfflineSkillVersionRequest{}
	if v, ok := req.Body.(*OfflineSkillVersionRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(OfflineSkillVersionRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["version"]; v != "" {
		out.Version = v
	}
	return out, nil
}

// SkillServiceGatewayBindDownloadSkillVersion binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/DownloadSkillVersion.
func SkillServiceGatewayBindDownloadSkillVersion(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*DownloadSkillVersionRequest, error) {
	out := &DownloadSkillVersionRequest{}
	if v, ok := req.Body.(*DownloadSkillVersionRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(DownloadSkillVersionRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["version"]; v != "" {
		out.Version = v
	}
	return out, nil
}

// SkillServiceGatewayBindListSkillVersionFiles binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/ListSkillVersionFiles.
func SkillServiceGatewayBindListSkillVersionFiles(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListSkillVersionFilesRequest, error) {
	out := &ListSkillVersionFilesRequest{}
	if v, ok := req.Body.(*ListSkillVersionFilesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListSkillVersionFilesRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["version"]; v != "" {
		out.Version = v
	}
	return out, nil
}

// SkillServiceGatewayBindGetSkillVersionFile binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/GetSkillVersionFile.
func SkillServiceGatewayBindGetSkillVersionFile(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetSkillVersionFileRequest, error) {
	out := &GetSkillVersionFileRequest{}
	if v, ok := req.Body.(*GetSkillVersionFileRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetSkillVersionFileRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["version"]; v != "" {
		out.Version = v
	}
	return out, nil
}

// SkillServiceGatewayBindListSkillShares binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/ListSkillShares.
func SkillServiceGatewayBindListSkillShares(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListSkillSharesRequest, error) {
	out := &ListSkillSharesRequest{}
	if v, ok := req.Body.(*ListSkillSharesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListSkillSharesRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

// SkillServiceGatewayBindCreateSkillShare binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/CreateSkillShare.
func SkillServiceGatewayBindCreateSkillShare(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*CreateSkillShareRequest, error) {
	out := &CreateSkillShareRequest{}
	if v, ok := req.Body.(*CreateSkillShareRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(CreateSkillShareRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	return out, nil
}

// SkillServiceGatewayBindDeleteSkillShare binds the matched HTTP Gateway request to the gRPC request for /skill.v1.SkillService/DeleteSkillShare.
func SkillServiceGatewayBindDeleteSkillShare(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*DeleteSkillShareRequest, error) {
	out := &DeleteSkillShareRequest{}
	if v, ok := req.Body.(*DeleteSkillShareRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(DeleteSkillShareRequest); ok {
		out = &v
	}
	if v := match.Params["name"]; v != "" {
		out.Name = v
	}
	if v := match.Params["subject_type"]; v != "" {
		out.SubjectType = v
	}
	if v := match.Params["subject_id"]; v != "" {
		out.SubjectId = v
	}
	return out, nil
}

// RegisterSkillServiceGatewayInvokers registers generated Gateway -> gRPC operation invokers for skill.v1.SkillService.
func RegisterSkillServiceGatewayInvokers(registry *gatewayx.InvokerRegistry, client SkillServiceClient) error {
	if err := registry.Register("/skill.v1.SkillService/CreateSkill", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindCreateSkill, client.CreateSkill)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/UpdateSkill", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindUpdateSkill, client.UpdateSkill)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/UpdateSkillVisibility", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindUpdateSkillVisibility, client.UpdateSkillVisibility)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ListSkills", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindListSkills, client.ListSkills)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/GetSkill", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindGetSkill, client.GetSkill)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/DeleteSkill", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindDeleteSkill, client.DeleteSkill)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/UploadSkillPackage", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindUploadSkillPackage, client.UploadSkillPackage)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ListSkillVersions", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindListSkillVersions, client.ListSkillVersions)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/GetSkillVersion", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindGetSkillVersion, client.GetSkillVersion)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/SubmitSkillVersion", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindSubmitSkillVersion, client.SubmitSkillVersion)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/PublishSkillVersion", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindPublishSkillVersion, client.PublishSkillVersion)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/OnlineSkillVersion", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindOnlineSkillVersion, client.OnlineSkillVersion)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/OfflineSkillVersion", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindOfflineSkillVersion, client.OfflineSkillVersion)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/DownloadSkillVersion", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindDownloadSkillVersion, client.DownloadSkillVersion)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ListSkillVersionFiles", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindListSkillVersionFiles, client.ListSkillVersionFiles)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/GetSkillVersionFile", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindGetSkillVersionFile, client.GetSkillVersionFile)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/ListSkillShares", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindListSkillShares, client.ListSkillShares)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/CreateSkillShare", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindCreateSkillShare, client.CreateSkillShare)); err != nil {
		return err
	}
	if err := registry.Register("/skill.v1.SkillService/DeleteSkillShare", gatewayx.GRPCUnaryInvoker(SkillServiceGatewayBindDeleteSkillShare, client.DeleteSkillShare)); err != nil {
		return err
	}
	return nil
}
