// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.1
// source: skill/v1/skill.proto

package skillv1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// SkillServiceKernelModule returns the generated Kernel service module for skill.v1.SkillService.
func SkillServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "skill-service",
		GatewayManifest:     SkillServiceGatewayManifest(),
		RequestInfoResolver: SkillServiceKernelRequestInfoResolver,
		AccessResolver:      SkillServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(SkillServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for skill.v1.SkillService must implement SkillServiceServer, got %T", impl)
			}
			RegisterSkillServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(SkillServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for skill.v1.SkillService must implement SkillServiceHTTPServer, got %T", impl)
			}
			RegisterSkillServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(SkillServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for skill.v1.SkillService must implement SkillServiceClient, got %T", client)
			}
			return RegisterSkillServiceGatewayInvokers(r, typed)
		},
	}
}

var SkillServiceKernelAuthzRules = authz.Rules{
	"/skill.v1.SkillService/UpdateSkill": {
		Service:    "skill.v1.SkillService",
		Method:     "UpdateSkill",
		FullMethod: "/skill.v1.SkillService/UpdateSkill",
		Action:     "edit",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill.update",
		AuditRisk:  "medium",
	},
	"/skill.v1.SkillService/UpdateSkillVisibility": {
		Service:    "skill.v1.SkillService",
		Method:     "UpdateSkillVisibility",
		FullMethod: "/skill.v1.SkillService/UpdateSkillVisibility",
		Action:     "manage",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill.visibility.update",
		AuditRisk:  "high",
	},
	"/skill.v1.SkillService/DeleteSkill": {
		Service:    "skill.v1.SkillService",
		Method:     "DeleteSkill",
		FullMethod: "/skill.v1.SkillService/DeleteSkill",
		Action:     "manage",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill.delete",
		AuditRisk:  "high",
	},
	"/skill.v1.SkillService/SubmitSkillVersion": {
		Service:    "skill.v1.SkillService",
		Method:     "SubmitSkillVersion",
		FullMethod: "/skill.v1.SkillService/SubmitSkillVersion",
		Action:     "edit",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_version.submit",
		AuditRisk:  "medium",
	},
	"/skill.v1.SkillService/PublishSkillVersion": {
		Service:    "skill.v1.SkillService",
		Method:     "PublishSkillVersion",
		FullMethod: "/skill.v1.SkillService/PublishSkillVersion",
		Action:     "publish",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_version.publish",
		AuditRisk:  "high",
	},
	"/skill.v1.SkillService/OnlineSkillVersion": {
		Service:    "skill.v1.SkillService",
		Method:     "OnlineSkillVersion",
		FullMethod: "/skill.v1.SkillService/OnlineSkillVersion",
		Action:     "publish",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_version.online",
		AuditRisk:  "high",
	},
	"/skill.v1.SkillService/OfflineSkillVersion": {
		Service:    "skill.v1.SkillService",
		Method:     "OfflineSkillVersion",
		FullMethod: "/skill.v1.SkillService/OfflineSkillVersion",
		Action:     "publish",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_version.offline",
		AuditRisk:  "high",
	},
	"/skill.v1.SkillService/UpsertSkillDraftFile": {
		Service:    "skill.v1.SkillService",
		Method:     "UpsertSkillDraftFile",
		FullMethod: "/skill.v1.SkillService/UpsertSkillDraftFile",
		Action:     "edit",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_draft_file.write",
		AuditRisk:  "medium",
	},
	"/skill.v1.SkillService/UpsertSkillDraftDirectory": {
		Service:    "skill.v1.SkillService",
		Method:     "UpsertSkillDraftDirectory",
		FullMethod: "/skill.v1.SkillService/UpsertSkillDraftDirectory",
		Action:     "edit",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_draft_dir.write",
		AuditRisk:  "medium",
	},
	"/skill.v1.SkillService/DeleteSkillDraftPath": {
		Service:    "skill.v1.SkillService",
		Method:     "DeleteSkillDraftPath",
		FullMethod: "/skill.v1.SkillService/DeleteSkillDraftPath",
		Action:     "edit",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_draft_path.delete",
		AuditRisk:  "medium",
	},
	"/skill.v1.SkillService/MoveSkillDraftPath": {
		Service:    "skill.v1.SkillService",
		Method:     "MoveSkillDraftPath",
		FullMethod: "/skill.v1.SkillService/MoveSkillDraftPath",
		Action:     "edit",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_draft_path.move",
		AuditRisk:  "medium",
	},
	"/skill.v1.SkillService/CommitSkillDraft": {
		Service:    "skill.v1.SkillService",
		Method:     "CommitSkillDraft",
		FullMethod: "/skill.v1.SkillService/CommitSkillDraft",
		Action:     "edit",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_draft.commit",
		AuditRisk:  "medium",
	},
	"/skill.v1.SkillService/ListSkillShares": {
		Service:    "skill.v1.SkillService",
		Method:     "ListSkillShares",
		FullMethod: "/skill.v1.SkillService/ListSkillShares",
		Action:     "manage",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_share.list",
		AuditRisk:  "medium",
	},
	"/skill.v1.SkillService/CreateSkillShare": {
		Service:    "skill.v1.SkillService",
		Method:     "CreateSkillShare",
		FullMethod: "/skill.v1.SkillService/CreateSkillShare",
		Action:     "manage",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_share.create",
		AuditRisk:  "high",
	},
	"/skill.v1.SkillService/DeleteSkillShare": {
		Service:    "skill.v1.SkillService",
		Method:     "DeleteSkillShare",
		FullMethod: "/skill.v1.SkillService/DeleteSkillShare",
		Action:     "manage",
		Resource:   "skill:{name}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "aihub.skill_share.delete",
		AuditRisk:  "high",
	},
}

// SkillServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func SkillServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _SkillServiceKernelNormalizeOperation(operation) {
	case "/skill.v1.SkillService/CreateSkill":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "CreateSkill",
			Operation: "/skill.v1.SkillService/CreateSkill",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill.create"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/UpdateSkill":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "UpdateSkill",
			Operation:     "/skill.v1.SkillService/UpdateSkill",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill.update"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/UpdateSkillVisibility":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "UpdateSkillVisibility",
			Operation:     "/skill.v1.SkillService/UpdateSkillVisibility",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill.visibility.update"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/ListSkills":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "ListSkills",
			Operation: "/skill.v1.SkillService/ListSkills",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/GetSkill":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "GetSkill",
			Operation: "/skill.v1.SkillService/GetSkill",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/DeleteSkill":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "DeleteSkill",
			Operation:     "/skill.v1.SkillService/DeleteSkill",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill.delete"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/UploadSkillPackage":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "UploadSkillPackage",
			Operation: "/skill.v1.SkillService/UploadSkillPackage",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill.upload"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/ListSkillVersions":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "ListSkillVersions",
			Operation: "/skill.v1.SkillService/ListSkillVersions",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill_version.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/GetSkillVersion":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "GetSkillVersion",
			Operation: "/skill.v1.SkillService/GetSkillVersion",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill_version.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/SubmitSkillVersion":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "SubmitSkillVersion",
			Operation:     "/skill.v1.SkillService/SubmitSkillVersion",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_version.submit"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/PublishSkillVersion":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "PublishSkillVersion",
			Operation:     "/skill.v1.SkillService/PublishSkillVersion",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "publish",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_version.publish"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/OnlineSkillVersion":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "OnlineSkillVersion",
			Operation:     "/skill.v1.SkillService/OnlineSkillVersion",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "publish",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_version.online"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/OfflineSkillVersion":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "OfflineSkillVersion",
			Operation:     "/skill.v1.SkillService/OfflineSkillVersion",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "publish",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_version.offline"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/DownloadSkillVersion":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "DownloadSkillVersion",
			Operation: "/skill.v1.SkillService/DownloadSkillVersion",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill_version.download"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/ListSkillVersionFiles":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "ListSkillVersionFiles",
			Operation: "/skill.v1.SkillService/ListSkillVersionFiles",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill_file.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/GetSkillVersionFile":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "GetSkillVersionFile",
			Operation: "/skill.v1.SkillService/GetSkillVersionFile",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill_file.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/ListSkillDraftFiles":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "ListSkillDraftFiles",
			Operation: "/skill.v1.SkillService/ListSkillDraftFiles",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill_draft_file.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/GetSkillDraftFile":
		info := requestx.Info{
			Service:   "skill.v1.SkillService",
			Method:    "GetSkillDraftFile",
			Operation: "/skill.v1.SkillService/GetSkillDraftFile",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "aihub.skill_draft_file.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/UpsertSkillDraftFile":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "UpsertSkillDraftFile",
			Operation:     "/skill.v1.SkillService/UpsertSkillDraftFile",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_draft_file.write"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/UpsertSkillDraftDirectory":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "UpsertSkillDraftDirectory",
			Operation:     "/skill.v1.SkillService/UpsertSkillDraftDirectory",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_draft_dir.write"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/DeleteSkillDraftPath":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "DeleteSkillDraftPath",
			Operation:     "/skill.v1.SkillService/DeleteSkillDraftPath",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_draft_path.delete"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/MoveSkillDraftPath":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "MoveSkillDraftPath",
			Operation:     "/skill.v1.SkillService/MoveSkillDraftPath",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_draft_path.move"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/CommitSkillDraft":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "CommitSkillDraft",
			Operation:     "/skill.v1.SkillService/CommitSkillDraft",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_draft.commit"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/ListSkillShares":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "ListSkillShares",
			Operation:     "/skill.v1.SkillService/ListSkillShares",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_share.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/CreateSkillShare":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "CreateSkillShare",
			Operation:     "/skill.v1.SkillService/CreateSkillShare",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_share.create"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/skill.v1.SkillService/DeleteSkillShare":
		info := requestx.Info{
			Service:       "skill.v1.SkillService",
			Method:        "DeleteSkillShare",
			Operation:     "/skill.v1.SkillService/DeleteSkillShare",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "skill:{name}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "aihub.skill_share.delete"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// SkillServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func SkillServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := SkillServiceKernelAuthzRules[_SkillServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _SkillServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "CreateSkill", "skill.v1.SkillService/CreateSkill":
		return "/skill.v1.SkillService/CreateSkill"
	case "UpdateSkill", "skill.v1.SkillService/UpdateSkill":
		return "/skill.v1.SkillService/UpdateSkill"
	case "UpdateSkillVisibility", "skill.v1.SkillService/UpdateSkillVisibility":
		return "/skill.v1.SkillService/UpdateSkillVisibility"
	case "ListSkills", "skill.v1.SkillService/ListSkills":
		return "/skill.v1.SkillService/ListSkills"
	case "GetSkill", "skill.v1.SkillService/GetSkill":
		return "/skill.v1.SkillService/GetSkill"
	case "DeleteSkill", "skill.v1.SkillService/DeleteSkill":
		return "/skill.v1.SkillService/DeleteSkill"
	case "UploadSkillPackage", "skill.v1.SkillService/UploadSkillPackage":
		return "/skill.v1.SkillService/UploadSkillPackage"
	case "ListSkillVersions", "skill.v1.SkillService/ListSkillVersions":
		return "/skill.v1.SkillService/ListSkillVersions"
	case "GetSkillVersion", "skill.v1.SkillService/GetSkillVersion":
		return "/skill.v1.SkillService/GetSkillVersion"
	case "SubmitSkillVersion", "skill.v1.SkillService/SubmitSkillVersion":
		return "/skill.v1.SkillService/SubmitSkillVersion"
	case "PublishSkillVersion", "skill.v1.SkillService/PublishSkillVersion":
		return "/skill.v1.SkillService/PublishSkillVersion"
	case "OnlineSkillVersion", "skill.v1.SkillService/OnlineSkillVersion":
		return "/skill.v1.SkillService/OnlineSkillVersion"
	case "OfflineSkillVersion", "skill.v1.SkillService/OfflineSkillVersion":
		return "/skill.v1.SkillService/OfflineSkillVersion"
	case "DownloadSkillVersion", "skill.v1.SkillService/DownloadSkillVersion":
		return "/skill.v1.SkillService/DownloadSkillVersion"
	case "ListSkillVersionFiles", "skill.v1.SkillService/ListSkillVersionFiles":
		return "/skill.v1.SkillService/ListSkillVersionFiles"
	case "GetSkillVersionFile", "skill.v1.SkillService/GetSkillVersionFile":
		return "/skill.v1.SkillService/GetSkillVersionFile"
	case "ListSkillDraftFiles", "skill.v1.SkillService/ListSkillDraftFiles":
		return "/skill.v1.SkillService/ListSkillDraftFiles"
	case "GetSkillDraftFile", "skill.v1.SkillService/GetSkillDraftFile":
		return "/skill.v1.SkillService/GetSkillDraftFile"
	case "UpsertSkillDraftFile", "skill.v1.SkillService/UpsertSkillDraftFile":
		return "/skill.v1.SkillService/UpsertSkillDraftFile"
	case "UpsertSkillDraftDirectory", "skill.v1.SkillService/UpsertSkillDraftDirectory":
		return "/skill.v1.SkillService/UpsertSkillDraftDirectory"
	case "DeleteSkillDraftPath", "skill.v1.SkillService/DeleteSkillDraftPath":
		return "/skill.v1.SkillService/DeleteSkillDraftPath"
	case "MoveSkillDraftPath", "skill.v1.SkillService/MoveSkillDraftPath":
		return "/skill.v1.SkillService/MoveSkillDraftPath"
	case "CommitSkillDraft", "skill.v1.SkillService/CommitSkillDraft":
		return "/skill.v1.SkillService/CommitSkillDraft"
	case "ListSkillShares", "skill.v1.SkillService/ListSkillShares":
		return "/skill.v1.SkillService/ListSkillShares"
	case "CreateSkillShare", "skill.v1.SkillService/CreateSkillShare":
		return "/skill.v1.SkillService/CreateSkillShare"
	case "DeleteSkillShare", "skill.v1.SkillService/DeleteSkillShare":
		return "/skill.v1.SkillService/DeleteSkillShare"
	default:
		return operation
	}
}
