// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.4.16-0.20260719002535-c484be58cfef
// - protoc             (unknown)
// source: authn/v1/authn.proto

package authnv1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAuthnServiceExchange = "/authn.v1.AuthnService/Exchange"
const OperationAuthnServiceIntrospect = "/authn.v1.AuthnService/Introspect"
const OperationAuthnServiceLoginURL = "/authn.v1.AuthnService/LoginURL"
const OperationAuthnServiceLogoutURL = "/authn.v1.AuthnService/LogoutURL"
const OperationAuthnServiceMe = "/authn.v1.AuthnService/Me"
const OperationAuthnServiceRefresh = "/authn.v1.AuthnService/Refresh"
const OperationAuthnServiceRevoke = "/authn.v1.AuthnService/Revoke"

type AuthnServiceHTTPServer interface {
	// Exchange Exchange exchanges an OAuth authorization code for IdP tokens.
	//
	// Supports PKCE via the optional `code_verifier` field for public clients
	// (SPAs, mobile apps) that cannot safely store a client secret. When the
	// authorization request was made with a `code_challenge`, the same
	// `code_verifier` MUST be supplied here.
	//
	// NOTE: kernel authn exposes CodeVerifier on AuthCodeExchangeRequest, but
	// the current Casdoor SDK adapter (kernel/authn/casdoor/token.go) does not
	// yet forward it to GetOAuthToken. The field is accepted on the wire for
	// forward compatibility; verify the kernel version before relying on PKCE
	// enforcement server-side.
	Exchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error)
	// Introspect Introspect validates a token and returns the principal it represents.
	//
	// Useful for debug tools, third-party integrations, and service-to-service
	// calls that need to verify a token's validity and identity without going
	// through the full request middleware chain. Mirrors RFC 7662 token
	// introspection semantics (active=false when the token is invalid,
	// expired, or revoked).
	Introspect(context.Context, *IntrospectRequest) (*IntrospectResponse, error)
	// LoginURL LoginURL returns the IdP authorization URL as JSON for SPA/debug usage.
	//
	// Browser users should prefer GET /v1/authn/login, which is registered as a
	// direct HTTP 302 route by the service implementation. See the service
	// comment above.
	LoginURL(context.Context, *LoginURLRequest) (*LoginURLResponse, error)
	// LogoutURL LogoutURL returns the IdP logout URL as JSON for SPA/debug usage.
	//
	// Browser users can also call GET /v1/authn/logout for a direct HTTP 302.
	//
	// Side effect: token revocation. When the request carries an
	// `Authorization: Bearer <access_token>` header, OR an explicit
	// `access_token` field is supplied in the request body, the implementation
	// calls Revoke on that access token before returning the IdP logout URL.
	// This adds the token to the local session blacklist so subsequent API
	// calls with the same token are rejected even before the IdP session
	// expires. The `access_token` field makes this previously-implicit side
	// effect visible in the API contract.
	//
	//
	// The logout URL is built by kernel authn.LogoutService (implemented by
	// the Casdoor adapter in kernel/authn/casdoor). The hub data layer
	// delegates to Resources.LogoutService.BuildLogoutURL().
	LogoutURL(context.Context, *LogoutURLRequest) (*LogoutURLResponse, error)
	// Me Me returns the current authenticated principal.
	//
	// Requires `Authorization: Bearer <access_token>`. The returned Principal
	// includes `expires_at` so frontends can schedule proactive token refreshes
	// before the token expires, rather than waiting for a 401 to trigger a
	// reactive refresh.
	Me(context.Context, *MeRequest) (*MeResponse, error)
	// Refresh Refresh refreshes an IdP access token using a refresh token.
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	// Revoke Revoke explicitly revokes an access or refresh token.
	//
	// Use this for multi-device session management (e.g. "sign out everywhere"
	// flows) where the caller wants to invalidate a token without navigating
	// the IdP logout page.
	//
	// IdP-side revocation is best-effort; the local session blacklist is
	// always updated so the token is rejected at the next API call regardless
	// of whether the IdP actually revokes it.
	//
	// NOTE: the current Casdoor SDK adapter (kernel/authn/casdoor/token.go)
	// returns ErrIdentityBackendFailed("casdoor sdk does not expose token
	// revocation"). Until the kernel adapter is updated, this RPC will only
	// update the local blacklist and return a warning. Callers that need
	// full IdP-side revocation should use LogoutURL with id_token_hint.
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
}

func RegisterAuthnServiceHTTPServer(s *http.Server, srv AuthnServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/authn/login-url", _AuthnService_LoginURL0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/authn/logout-url", _AuthnService_LogoutURL0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/authn/me", _AuthnService_Me0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/authn/exchange", _AuthnService_Exchange0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/authn/introspect", _AuthnService_Introspect0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/authn/refresh", _AuthnService_Refresh0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/authn/revoke", _AuthnService_Revoke0_HTTP_Handler(srv))
}

func _AuthnService_LoginURL0_HTTP_Handler(srv AuthnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginURLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthnServiceLoginURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginURL(ctx, req.(*LoginURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginURLResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthnService_LogoutURL0_HTTP_Handler(srv AuthnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutURLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthnServiceLogoutURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LogoutURL(ctx, req.(*LogoutURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutURLResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthnService_Me0_HTTP_Handler(srv AuthnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthnServiceMe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Me(ctx, req.(*MeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MeResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthnService_Exchange0_HTTP_Handler(srv AuthnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExchangeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthnServiceExchange)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Exchange(ctx, req.(*ExchangeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExchangeResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthnService_Introspect0_HTTP_Handler(srv AuthnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IntrospectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthnServiceIntrospect)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Introspect(ctx, req.(*IntrospectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*IntrospectResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthnService_Refresh0_HTTP_Handler(srv AuthnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthnServiceRefresh)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Refresh(ctx, req.(*RefreshRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RefreshResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthnService_Revoke0_HTTP_Handler(srv AuthnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthnServiceRevoke)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Revoke(ctx, req.(*RevokeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RevokeResponse)
		return ctx.Result(200, reply)
	}
}

type AuthnServiceHTTPClient interface {
	// Exchange Exchange exchanges an OAuth authorization code for IdP tokens.
	//
	// Supports PKCE via the optional `code_verifier` field for public clients
	// (SPAs, mobile apps) that cannot safely store a client secret. When the
	// authorization request was made with a `code_challenge`, the same
	// `code_verifier` MUST be supplied here.
	//
	// NOTE: kernel authn exposes CodeVerifier on AuthCodeExchangeRequest, but
	// the current Casdoor SDK adapter (kernel/authn/casdoor/token.go) does not
	// yet forward it to GetOAuthToken. The field is accepted on the wire for
	// forward compatibility; verify the kernel version before relying on PKCE
	// enforcement server-side.
	Exchange(ctx context.Context, req *ExchangeRequest, opts ...http.CallOption) (rsp *ExchangeResponse, err error)
	// Introspect Introspect validates a token and returns the principal it represents.
	//
	// Useful for debug tools, third-party integrations, and service-to-service
	// calls that need to verify a token's validity and identity without going
	// through the full request middleware chain. Mirrors RFC 7662 token
	// introspection semantics (active=false when the token is invalid,
	// expired, or revoked).
	Introspect(ctx context.Context, req *IntrospectRequest, opts ...http.CallOption) (rsp *IntrospectResponse, err error)
	// LoginURL LoginURL returns the IdP authorization URL as JSON for SPA/debug usage.
	//
	// Browser users should prefer GET /v1/authn/login, which is registered as a
	// direct HTTP 302 route by the service implementation. See the service
	// comment above.
	LoginURL(ctx context.Context, req *LoginURLRequest, opts ...http.CallOption) (rsp *LoginURLResponse, err error)
	// LogoutURL LogoutURL returns the IdP logout URL as JSON for SPA/debug usage.
	//
	// Browser users can also call GET /v1/authn/logout for a direct HTTP 302.
	//
	// Side effect: token revocation. When the request carries an
	// `Authorization: Bearer <access_token>` header, OR an explicit
	// `access_token` field is supplied in the request body, the implementation
	// calls Revoke on that access token before returning the IdP logout URL.
	// This adds the token to the local session blacklist so subsequent API
	// calls with the same token are rejected even before the IdP session
	// expires. The `access_token` field makes this previously-implicit side
	// effect visible in the API contract.
	//
	//
	// The logout URL is built by kernel authn.LogoutService (implemented by
	// the Casdoor adapter in kernel/authn/casdoor). The hub data layer
	// delegates to Resources.LogoutService.BuildLogoutURL().
	LogoutURL(ctx context.Context, req *LogoutURLRequest, opts ...http.CallOption) (rsp *LogoutURLResponse, err error)
	// Me Me returns the current authenticated principal.
	//
	// Requires `Authorization: Bearer <access_token>`. The returned Principal
	// includes `expires_at` so frontends can schedule proactive token refreshes
	// before the token expires, rather than waiting for a 401 to trigger a
	// reactive refresh.
	Me(ctx context.Context, req *MeRequest, opts ...http.CallOption) (rsp *MeResponse, err error)
	// Refresh Refresh refreshes an IdP access token using a refresh token.
	Refresh(ctx context.Context, req *RefreshRequest, opts ...http.CallOption) (rsp *RefreshResponse, err error)
	// Revoke Revoke explicitly revokes an access or refresh token.
	//
	// Use this for multi-device session management (e.g. "sign out everywhere"
	// flows) where the caller wants to invalidate a token without navigating
	// the IdP logout page.
	//
	// IdP-side revocation is best-effort; the local session blacklist is
	// always updated so the token is rejected at the next API call regardless
	// of whether the IdP actually revokes it.
	//
	// NOTE: the current Casdoor SDK adapter (kernel/authn/casdoor/token.go)
	// returns ErrIdentityBackendFailed("casdoor sdk does not expose token
	// revocation"). Until the kernel adapter is updated, this RPC will only
	// update the local blacklist and return a warning. Callers that need
	// full IdP-side revocation should use LogoutURL with id_token_hint.
	Revoke(ctx context.Context, req *RevokeRequest, opts ...http.CallOption) (rsp *RevokeResponse, err error)
}

type AuthnServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAuthnServiceHTTPClient(client *http.Client) AuthnServiceHTTPClient {
	return &AuthnServiceHTTPClientImpl{client}
}

// Exchange Exchange exchanges an OAuth authorization code for IdP tokens.
//
// Supports PKCE via the optional `code_verifier` field for public clients
// (SPAs, mobile apps) that cannot safely store a client secret. When the
// authorization request was made with a `code_challenge`, the same
// `code_verifier` MUST be supplied here.
//
// NOTE: kernel authn exposes CodeVerifier on AuthCodeExchangeRequest, but
// the current Casdoor SDK adapter (kernel/authn/casdoor/token.go) does not
// yet forward it to GetOAuthToken. The field is accepted on the wire for
// forward compatibility; verify the kernel version before relying on PKCE
// enforcement server-side.
func (c *AuthnServiceHTTPClientImpl) Exchange(ctx context.Context, in *ExchangeRequest, opts ...http.CallOption) (*ExchangeResponse, error) {
	var out ExchangeResponse
	pattern := "/v1/authn/exchange"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAuthnServiceExchange),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Introspect Introspect validates a token and returns the principal it represents.
//
// Useful for debug tools, third-party integrations, and service-to-service
// calls that need to verify a token's validity and identity without going
// through the full request middleware chain. Mirrors RFC 7662 token
// introspection semantics (active=false when the token is invalid,
// expired, or revoked).
func (c *AuthnServiceHTTPClientImpl) Introspect(ctx context.Context, in *IntrospectRequest, opts ...http.CallOption) (*IntrospectResponse, error) {
	var out IntrospectResponse
	pattern := "/v1/authn/introspect"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAuthnServiceIntrospect),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginURL LoginURL returns the IdP authorization URL as JSON for SPA/debug usage.
//
// Browser users should prefer GET /v1/authn/login, which is registered as a
// direct HTTP 302 route by the service implementation. See the service
// comment above.
func (c *AuthnServiceHTTPClientImpl) LoginURL(ctx context.Context, in *LoginURLRequest, opts ...http.CallOption) (*LoginURLResponse, error) {
	var out LoginURLResponse
	pattern := "/v1/authn/login-url"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAuthnServiceLoginURL),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LogoutURL LogoutURL returns the IdP logout URL as JSON for SPA/debug usage.
//
// Browser users can also call GET /v1/authn/logout for a direct HTTP 302.
//
// Side effect: token revocation. When the request carries an
// `Authorization: Bearer <access_token>` header, OR an explicit
// `access_token` field is supplied in the request body, the implementation
// calls Revoke on that access token before returning the IdP logout URL.
// This adds the token to the local session blacklist so subsequent API
// calls with the same token are rejected even before the IdP session
// expires. The `access_token` field makes this previously-implicit side
// effect visible in the API contract.
//
//
// The logout URL is built by kernel authn.LogoutService (implemented by
// the Casdoor adapter in kernel/authn/casdoor). The hub data layer
// delegates to Resources.LogoutService.BuildLogoutURL().
func (c *AuthnServiceHTTPClientImpl) LogoutURL(ctx context.Context, in *LogoutURLRequest, opts ...http.CallOption) (*LogoutURLResponse, error) {
	var out LogoutURLResponse
	pattern := "/v1/authn/logout-url"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAuthnServiceLogoutURL),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Me Me returns the current authenticated principal.
//
// Requires `Authorization: Bearer <access_token>`. The returned Principal
// includes `expires_at` so frontends can schedule proactive token refreshes
// before the token expires, rather than waiting for a 401 to trigger a
// reactive refresh.
func (c *AuthnServiceHTTPClientImpl) Me(ctx context.Context, in *MeRequest, opts ...http.CallOption) (*MeResponse, error) {
	var out MeResponse
	pattern := "/v1/authn/me"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAuthnServiceMe),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Refresh Refresh refreshes an IdP access token using a refresh token.
func (c *AuthnServiceHTTPClientImpl) Refresh(ctx context.Context, in *RefreshRequest, opts ...http.CallOption) (*RefreshResponse, error) {
	var out RefreshResponse
	pattern := "/v1/authn/refresh"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAuthnServiceRefresh),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Revoke Revoke explicitly revokes an access or refresh token.
//
// Use this for multi-device session management (e.g. "sign out everywhere"
// flows) where the caller wants to invalidate a token without navigating
// the IdP logout page.
//
// IdP-side revocation is best-effort; the local session blacklist is
// always updated so the token is rejected at the next API call regardless
// of whether the IdP actually revokes it.
//
// NOTE: the current Casdoor SDK adapter (kernel/authn/casdoor/token.go)
// returns ErrIdentityBackendFailed("casdoor sdk does not expose token
// revocation"). Until the kernel adapter is updated, this RPC will only
// update the local blacklist and return a warning. Callers that need
// full IdP-side revocation should use LogoutURL with id_token_hint.
func (c *AuthnServiceHTTPClientImpl) Revoke(ctx context.Context, in *RevokeRequest, opts ...http.CallOption) (*RevokeResponse, error) {
	var out RevokeResponse
	pattern := "/v1/authn/revoke"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAuthnServiceRevoke),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
