// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.16-0.20260719002535-c484be58cfef
// source: kubernetes/v1/cluster.proto

package kubernetesv1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// ClusterServiceKernelModule returns the generated Kernel service module for kubernetes.v1.ClusterService.
func ClusterServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "cluster-service",
		GatewayManifest:     ClusterServiceGatewayManifest(),
		RequestInfoResolver: ClusterServiceKernelRequestInfoResolver,
		AccessResolver:      ClusterServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(ClusterServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for kubernetes.v1.ClusterService must implement ClusterServiceServer, got %T", impl)
			}
			RegisterClusterServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(ClusterServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for kubernetes.v1.ClusterService must implement ClusterServiceHTTPServer, got %T", impl)
			}
			RegisterClusterServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(ClusterServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for kubernetes.v1.ClusterService must implement ClusterServiceClient, got %T", client)
			}
			return RegisterClusterServiceGatewayInvokers(r, typed)
		},
	}
}

var ClusterServiceKernelAuthzRules = authz.Rules{
	"/kubernetes.v1.ClusterService/CreateCluster": {
		Service:    "kubernetes.v1.ClusterService",
		Method:     "CreateCluster",
		FullMethod: "/kubernetes.v1.ClusterService/CreateCluster",
		Action:     "create_cluster",
		Resource:   "zone:{org_id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.cluster.create",
		AuditRisk:  "high",
	},
	"/kubernetes.v1.ClusterService/GetCluster": {
		Service:    "kubernetes.v1.ClusterService",
		Method:     "GetCluster",
		FullMethod: "/kubernetes.v1.ClusterService/GetCluster",
		Action:     "view",
		Resource:   "k8s_cluster:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.cluster.get",
		AuditRisk:  "low",
	},
	"/kubernetes.v1.ClusterService/UpdateCluster": {
		Service:    "kubernetes.v1.ClusterService",
		Method:     "UpdateCluster",
		FullMethod: "/kubernetes.v1.ClusterService/UpdateCluster",
		Action:     "manage",
		Resource:   "k8s_cluster:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.cluster.update",
		AuditRisk:  "medium",
	},
	"/kubernetes.v1.ClusterService/DeleteCluster": {
		Service:    "kubernetes.v1.ClusterService",
		Method:     "DeleteCluster",
		FullMethod: "/kubernetes.v1.ClusterService/DeleteCluster",
		Action:     "manage",
		Resource:   "k8s_cluster:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.cluster.delete",
		AuditRisk:  "high",
	},
	"/kubernetes.v1.ClusterService/ProbeCluster": {
		Service:    "kubernetes.v1.ClusterService",
		Method:     "ProbeCluster",
		FullMethod: "/kubernetes.v1.ClusterService/ProbeCluster",
		Action:     "operate",
		Resource:   "k8s_cluster:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.cluster.probe",
		AuditRisk:  "medium",
	},
	"/kubernetes.v1.ClusterService/RotateCredential": {
		Service:    "kubernetes.v1.ClusterService",
		Method:     "RotateCredential",
		FullMethod: "/kubernetes.v1.ClusterService/RotateCredential",
		Action:     "manage",
		Resource:   "k8s_cluster:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.cluster.rotate_credential",
		AuditRisk:  "high",
	},
}

// ClusterServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func ClusterServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _ClusterServiceKernelNormalizeOperation(operation) {
	case "/kubernetes.v1.ClusterService/CreateCluster":
		info := requestx.Info{
			Service:       "kubernetes.v1.ClusterService",
			Method:        "CreateCluster",
			Operation:     "/kubernetes.v1.ClusterService/CreateCluster",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "create_cluster",
			Resource:      "zone:{org_id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.cluster.create"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/kubernetes.v1.ClusterService/ListClusters":
		info := requestx.Info{
			Service:   "kubernetes.v1.ClusterService",
			Method:    "ListClusters",
			Operation: "/kubernetes.v1.ClusterService/ListClusters",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "hub.cluster.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/kubernetes.v1.ClusterService/GetCluster":
		info := requestx.Info{
			Service:       "kubernetes.v1.ClusterService",
			Method:        "GetCluster",
			Operation:     "/kubernetes.v1.ClusterService/GetCluster",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view",
			Resource:      "k8s_cluster:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.cluster.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/kubernetes.v1.ClusterService/UpdateCluster":
		info := requestx.Info{
			Service:       "kubernetes.v1.ClusterService",
			Method:        "UpdateCluster",
			Operation:     "/kubernetes.v1.ClusterService/UpdateCluster",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "k8s_cluster:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.cluster.update"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/kubernetes.v1.ClusterService/DeleteCluster":
		info := requestx.Info{
			Service:       "kubernetes.v1.ClusterService",
			Method:        "DeleteCluster",
			Operation:     "/kubernetes.v1.ClusterService/DeleteCluster",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "k8s_cluster:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.cluster.delete"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/kubernetes.v1.ClusterService/ProbeCluster":
		info := requestx.Info{
			Service:       "kubernetes.v1.ClusterService",
			Method:        "ProbeCluster",
			Operation:     "/kubernetes.v1.ClusterService/ProbeCluster",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "operate",
			Resource:      "k8s_cluster:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.cluster.probe"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/kubernetes.v1.ClusterService/RotateCredential":
		info := requestx.Info{
			Service:       "kubernetes.v1.ClusterService",
			Method:        "RotateCredential",
			Operation:     "/kubernetes.v1.ClusterService/RotateCredential",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "k8s_cluster:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.cluster.rotate_credential"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// ClusterServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func ClusterServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := ClusterServiceKernelAuthzRules[_ClusterServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _ClusterServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "CreateCluster", "kubernetes.v1.ClusterService/CreateCluster":
		return "/kubernetes.v1.ClusterService/CreateCluster"
	case "ListClusters", "kubernetes.v1.ClusterService/ListClusters":
		return "/kubernetes.v1.ClusterService/ListClusters"
	case "GetCluster", "kubernetes.v1.ClusterService/GetCluster":
		return "/kubernetes.v1.ClusterService/GetCluster"
	case "UpdateCluster", "kubernetes.v1.ClusterService/UpdateCluster":
		return "/kubernetes.v1.ClusterService/UpdateCluster"
	case "DeleteCluster", "kubernetes.v1.ClusterService/DeleteCluster":
		return "/kubernetes.v1.ClusterService/DeleteCluster"
	case "ProbeCluster", "kubernetes.v1.ClusterService/ProbeCluster":
		return "/kubernetes.v1.ClusterService/ProbeCluster"
	case "RotateCredential", "kubernetes.v1.ClusterService/RotateCredential":
		return "/kubernetes.v1.ClusterService/RotateCredential"
	default:
		return operation
	}
}
