// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubernetes/v1/cluster.proto

package kubernetesv1

import (
	_ "github.com/aisphereio/kernel/api/aisphere/access/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterStatus mirrors the lifecycle state machine in design §5.7.1.
type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_STATUS_UNSPECIFIED ClusterStatus = 0
	ClusterStatus_CLUSTER_STATUS_CREATING    ClusterStatus = 1
	ClusterStatus_CLUSTER_STATUS_READY       ClusterStatus = 2
	ClusterStatus_CLUSTER_STATUS_PROBING     ClusterStatus = 3
	ClusterStatus_CLUSTER_STATUS_DEGRADED    ClusterStatus = 4
	ClusterStatus_CLUSTER_STATUS_DELETING    ClusterStatus = 5
	ClusterStatus_CLUSTER_STATUS_DELETED     ClusterStatus = 6
	ClusterStatus_CLUSTER_STATUS_FAILED      ClusterStatus = 7
)

// Enum value maps for ClusterStatus.
var (
	ClusterStatus_name = map[int32]string{
		0: "CLUSTER_STATUS_UNSPECIFIED",
		1: "CLUSTER_STATUS_CREATING",
		2: "CLUSTER_STATUS_READY",
		3: "CLUSTER_STATUS_PROBING",
		4: "CLUSTER_STATUS_DEGRADED",
		5: "CLUSTER_STATUS_DELETING",
		6: "CLUSTER_STATUS_DELETED",
		7: "CLUSTER_STATUS_FAILED",
	}
	ClusterStatus_value = map[string]int32{
		"CLUSTER_STATUS_UNSPECIFIED": 0,
		"CLUSTER_STATUS_CREATING":    1,
		"CLUSTER_STATUS_READY":       2,
		"CLUSTER_STATUS_PROBING":     3,
		"CLUSTER_STATUS_DEGRADED":    4,
		"CLUSTER_STATUS_DELETING":    5,
		"CLUSTER_STATUS_DELETED":     6,
		"CLUSTER_STATUS_FAILED":      7,
	}
)

func (x ClusterStatus) Enum() *ClusterStatus {
	p := new(ClusterStatus)
	*p = x
	return p
}

func (x ClusterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kubernetes_v1_cluster_proto_enumTypes[0].Descriptor()
}

func (ClusterStatus) Type() protoreflect.EnumType {
	return &file_kubernetes_v1_cluster_proto_enumTypes[0]
}

func (x ClusterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus.Descriptor instead.
func (ClusterStatus) EnumDescriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{0}
}

// DeletePolicy controls Namespace cleanup when a Cluster is deleted
// (design §5.7.5). DETACH_ONLY keeps remote Namespaces; CASCADE removes
// AISphere-managed Namespaces too.
type DeletePolicy int32

const (
	DeletePolicy_DELETE_POLICY_UNSPECIFIED DeletePolicy = 0
	DeletePolicy_DELETE_POLICY_DETACH_ONLY DeletePolicy = 1
	DeletePolicy_DELETE_POLICY_CASCADE     DeletePolicy = 2
)

// Enum value maps for DeletePolicy.
var (
	DeletePolicy_name = map[int32]string{
		0: "DELETE_POLICY_UNSPECIFIED",
		1: "DELETE_POLICY_DETACH_ONLY",
		2: "DELETE_POLICY_CASCADE",
	}
	DeletePolicy_value = map[string]int32{
		"DELETE_POLICY_UNSPECIFIED": 0,
		"DELETE_POLICY_DETACH_ONLY": 1,
		"DELETE_POLICY_CASCADE":     2,
	}
)

func (x DeletePolicy) Enum() *DeletePolicy {
	p := new(DeletePolicy)
	*p = x
	return p
}

func (x DeletePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeletePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_kubernetes_v1_cluster_proto_enumTypes[1].Descriptor()
}

func (DeletePolicy) Type() protoreflect.EnumType {
	return &file_kubernetes_v1_cluster_proto_enumTypes[1]
}

func (x DeletePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeletePolicy.Descriptor instead.
func (DeletePolicy) EnumDescriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{1}
}

// Cluster is the AISphere control-plane resource for a registered Kubernetes
// cluster. It is NOT the kubeconfig file. Credential material is never
// returned by any RPC (design §5.2).
type Cluster struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName       string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	OrgId             string                 `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ServerUrl         string                 `protobuf:"bytes,6,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Distribution      string                 `protobuf:"bytes,7,opt,name=distribution,proto3" json:"distribution,omitempty"`
	KubernetesVersion string                 `protobuf:"bytes,8,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	Status            ClusterStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=kubernetes.v1.ClusterStatus" json:"status,omitempty"`
	HealthMessage     string                 `protobuf:"bytes,10,opt,name=health_message,json=healthMessage,proto3" json:"health_message,omitempty"`
	LastProbeTime     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_probe_time,json=lastProbeTime,proto3" json:"last_probe_time,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Permissions       *ClusterPermissions    `protobuf:"bytes,13,opt,name=permissions,proto3" json:"permissions,omitempty"`
	CreateTime        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Revision          int64                  `protobuf:"varint,16,opt,name=revision,proto3" json:"revision,omitempty"`
	OwnerType         string                 `protobuf:"bytes,17,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId           string                 `protobuf:"bytes,18,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Cluster) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cluster) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Cluster) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *Cluster) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

func (x *Cluster) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *Cluster) GetStatus() ClusterStatus {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_UNSPECIFIED
}

func (x *Cluster) GetHealthMessage() string {
	if x != nil {
		return x.HealthMessage
	}
	return ""
}

func (x *Cluster) GetLastProbeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastProbeTime
	}
	return nil
}

func (x *Cluster) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Cluster) GetPermissions() *ClusterPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Cluster) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Cluster) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Cluster) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Cluster) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *Cluster) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// ClusterPermissions is derived from SpiceDB BatchCheck at read time
// (design §7.6.2). can_delete is derived from can_manage. Cluster V1 has no
// share API, so can_share is intentionally omitted (design §5.2).
type ClusterPermissions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CanView            bool                   `protobuf:"varint,1,opt,name=can_view,json=canView,proto3" json:"can_view,omitempty"`
	CanOperate         bool                   `protobuf:"varint,2,opt,name=can_operate,json=canOperate,proto3" json:"can_operate,omitempty"`
	CanManage          bool                   `protobuf:"varint,3,opt,name=can_manage,json=canManage,proto3" json:"can_manage,omitempty"`
	CanCreateNamespace bool                   `protobuf:"varint,4,opt,name=can_create_namespace,json=canCreateNamespace,proto3" json:"can_create_namespace,omitempty"`
	CanDelete          bool                   `protobuf:"varint,5,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClusterPermissions) Reset() {
	*x = ClusterPermissions{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterPermissions) ProtoMessage() {}

func (x *ClusterPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterPermissions.ProtoReflect.Descriptor instead.
func (*ClusterPermissions) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterPermissions) GetCanView() bool {
	if x != nil {
		return x.CanView
	}
	return false
}

func (x *ClusterPermissions) GetCanOperate() bool {
	if x != nil {
		return x.CanOperate
	}
	return false
}

func (x *ClusterPermissions) GetCanManage() bool {
	if x != nil {
		return x.CanManage
	}
	return false
}

func (x *ClusterPermissions) GetCanCreateNamespace() bool {
	if x != nil {
		return x.CanCreateNamespace
	}
	return false
}

func (x *ClusterPermissions) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

// ClusterCredentialInput carries the credential supplied by the caller on
// create/rotate. Hub never persists plaintext; this message only flows into
// CredentialStore.Put. Logs must redact every field (design §5.4).
type ClusterCredentialInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ClusterCredentialInput_Kubeconfig
	//	*ClusterCredentialInput_InCluster
	//	*ClusterCredentialInput_ServiceAccount
	Source        isClusterCredentialInput_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterCredentialInput) Reset() {
	*x = ClusterCredentialInput{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCredentialInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCredentialInput) ProtoMessage() {}

func (x *ClusterCredentialInput) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterCredentialInput.ProtoReflect.Descriptor instead.
func (*ClusterCredentialInput) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterCredentialInput) GetSource() isClusterCredentialInput_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ClusterCredentialInput) GetKubeconfig() []byte {
	if x != nil {
		if x, ok := x.Source.(*ClusterCredentialInput_Kubeconfig); ok {
			return x.Kubeconfig
		}
	}
	return nil
}

func (x *ClusterCredentialInput) GetInCluster() *InClusterCredential {
	if x != nil {
		if x, ok := x.Source.(*ClusterCredentialInput_InCluster); ok {
			return x.InCluster
		}
	}
	return nil
}

func (x *ClusterCredentialInput) GetServiceAccount() *ServiceAccountCredential {
	if x != nil {
		if x, ok := x.Source.(*ClusterCredentialInput_ServiceAccount); ok {
			return x.ServiceAccount
		}
	}
	return nil
}

type isClusterCredentialInput_Source interface {
	isClusterCredentialInput_Source()
}

type ClusterCredentialInput_Kubeconfig struct {
	Kubeconfig []byte `protobuf:"bytes,1,opt,name=kubeconfig,proto3,oneof"`
}

type ClusterCredentialInput_InCluster struct {
	InCluster *InClusterCredential `protobuf:"bytes,2,opt,name=in_cluster,json=inCluster,proto3,oneof"`
}

type ClusterCredentialInput_ServiceAccount struct {
	ServiceAccount *ServiceAccountCredential `protobuf:"bytes,3,opt,name=service_account,json=serviceAccount,proto3,oneof"`
}

func (*ClusterCredentialInput_Kubeconfig) isClusterCredentialInput_Source() {}

func (*ClusterCredentialInput_InCluster) isClusterCredentialInput_Source() {}

func (*ClusterCredentialInput_ServiceAccount) isClusterCredentialInput_Source() {}

type InClusterCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InClusterCredential) Reset() {
	*x = InClusterCredential{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InClusterCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InClusterCredential) ProtoMessage() {}

func (x *InClusterCredential) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InClusterCredential.ProtoReflect.Descriptor instead.
func (*InClusterCredential) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{3}
}

type ServiceAccountCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bearer token. Hub stores it AEAD-encrypted; never returned.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// PEM-encoded CA bundle. Optional; when empty, system roots are used.
	CaCert        []byte `protobuf:"bytes,2,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAccountCredential) Reset() {
	*x = ServiceAccountCredential{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccountCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountCredential) ProtoMessage() {}

func (x *ServiceAccountCredential) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountCredential.ProtoReflect.Descriptor instead.
func (*ServiceAccountCredential) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceAccountCredential) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ServiceAccountCredential) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

type CreateClusterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrgId         string                  `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ServerUrl     string                  `protobuf:"bytes,3,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Credential    *ClusterCredentialInput `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	DisplayName   string                  `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                  `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Distribution  string                  `protobuf:"bytes,7,opt,name=distribution,proto3" json:"distribution,omitempty"`
	Labels        map[string]string       `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OwnerType     string                  `protobuf:"bytes,9,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId       string                  `protobuf:"bytes,10,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *CreateClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateClusterRequest) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *CreateClusterRequest) GetCredential() *ClusterCredentialInput {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CreateClusterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateClusterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateClusterRequest) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

func (x *CreateClusterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateClusterRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *CreateClusterRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterResponse) Reset() {
	*x = CreateClusterResponse{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterResponse) ProtoMessage() {}

func (x *CreateClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterResponse.ProtoReflect.Descriptor instead.
func (*CreateClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *CreateClusterResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type ListClustersRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// org_id overrides the principal's zone. Requires view_zone in that zone
	// (design §7.6.4). V1 does not provide cross-zone aggregation; there is
	// no all_orgs parameter.
	OrgId         string `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersRequest.ProtoReflect.Descriptor instead.
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *ListClustersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClustersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListClustersRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *ListClustersResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ListClustersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterRequest) Reset() {
	*x = GetClusterRequest{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterRequest) ProtoMessage() {}

func (x *GetClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterRequest.ProtoReflect.Descriptor instead.
func (*GetClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *GetClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterResponse) Reset() {
	*x = GetClusterResponse{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterResponse) ProtoMessage() {}

func (x *GetClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterResponse.ProtoReflect.Descriptor instead.
func (*GetClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *GetClusterResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

// UpdateClusterRequest uses FieldMask to avoid PUT clearing unset fields
// (design §5.3.2/§5.7.4). expected_revision is the CAS guard; mismatch
// returns REVISION_CONFLICT. Immutable fields in update_mask return
// INVALID_ARGUMENT.
type UpdateClusterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	UpdateMask       *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Cluster          *Cluster               `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateClusterRequest) Reset() {
	*x = UpdateClusterRequest{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterRequest) ProtoMessage() {}

func (x *UpdateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateClusterRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *UpdateClusterRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateClusterRequest) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type UpdateClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterResponse) Reset() {
	*x = UpdateClusterResponse{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterResponse) ProtoMessage() {}

func (x *UpdateClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterResponse.ProtoReflect.Descriptor instead.
func (*UpdateClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateClusterResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type DeleteClusterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	DeletePolicy     DeletePolicy           `protobuf:"varint,3,opt,name=delete_policy,json=deletePolicy,proto3,enum=kubernetes.v1.DeletePolicy" json:"delete_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteClusterRequest) Reset() {
	*x = DeleteClusterRequest{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterRequest) ProtoMessage() {}

func (x *DeleteClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteClusterRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *DeleteClusterRequest) GetDeletePolicy() DeletePolicy {
	if x != nil {
		return x.DeletePolicy
	}
	return DeletePolicy_DELETE_POLICY_UNSPECIFIED
}

type DeleteClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterResponse) Reset() {
	*x = DeleteClusterResponse{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterResponse) ProtoMessage() {}

func (x *DeleteClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteClusterResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type ProbeClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeClusterRequest) Reset() {
	*x = ProbeClusterRequest{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeClusterRequest) ProtoMessage() {}

func (x *ProbeClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeClusterRequest.ProtoReflect.Descriptor instead.
func (*ProbeClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *ProbeClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProbeClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeClusterResponse) Reset() {
	*x = ProbeClusterResponse{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeClusterResponse) ProtoMessage() {}

func (x *ProbeClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeClusterResponse.ProtoReflect.Descriptor instead.
func (*ProbeClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *ProbeClusterResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

// RotateCredentialRequest follows the six-step protocol in design §5.7.3:
// Put new credential -> probe with temp client -> CAS switch -> invalidate
// pool -> delayed old_ref cleanup. expected_revision guards CAS.
type RotateCredentialRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision int64                   `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Credential       *ClusterCredentialInput `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RotateCredentialRequest) Reset() {
	*x = RotateCredentialRequest{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCredentialRequest) ProtoMessage() {}

func (x *RotateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCredentialRequest.ProtoReflect.Descriptor instead.
func (*RotateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *RotateCredentialRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RotateCredentialRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *RotateCredentialRequest) GetCredential() *ClusterCredentialInput {
	if x != nil {
		return x.Credential
	}
	return nil
}

type RotateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateCredentialResponse) Reset() {
	*x = RotateCredentialResponse{}
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCredentialResponse) ProtoMessage() {}

func (x *RotateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_v1_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCredentialResponse.ProtoReflect.Descriptor instead.
func (*RotateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_v1_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *RotateCredentialResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

var File_kubernetes_v1_cluster_proto protoreflect.FileDescriptor

const file_kubernetes_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1bkubernetes/v1/cluster.proto\x12\rkubernetes.v1\x1a\x1faisphere/access/v1/access.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x06\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"server_url\x18\x06 \x01(\tR\tserverUrl\x12\"\n" +
	"\fdistribution\x18\a \x01(\tR\fdistribution\x12-\n" +
	"\x12kubernetes_version\x18\b \x01(\tR\x11kubernetesVersion\x124\n" +
	"\x06status\x18\t \x01(\x0e2\x1c.kubernetes.v1.ClusterStatusR\x06status\x12%\n" +
	"\x0ehealth_message\x18\n" +
	" \x01(\tR\rhealthMessage\x12B\n" +
	"\x0flast_probe_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rlastProbeTime\x12:\n" +
	"\x06labels\x18\f \x03(\v2\".kubernetes.v1.Cluster.LabelsEntryR\x06labels\x12C\n" +
	"\vpermissions\x18\r \x01(\v2!.kubernetes.v1.ClusterPermissionsR\vpermissions\x12;\n" +
	"\vcreate_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x1a\n" +
	"\brevision\x18\x10 \x01(\x03R\brevision\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x11 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x12 \x01(\tR\aownerId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x12ClusterPermissions\x12\x19\n" +
	"\bcan_view\x18\x01 \x01(\bR\acanView\x12\x1f\n" +
	"\vcan_operate\x18\x02 \x01(\bR\n" +
	"canOperate\x12\x1d\n" +
	"\n" +
	"can_manage\x18\x03 \x01(\bR\tcanManage\x120\n" +
	"\x14can_create_namespace\x18\x04 \x01(\bR\x12canCreateNamespace\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x05 \x01(\bR\tcanDelete\"\xdd\x01\n" +
	"\x16ClusterCredentialInput\x12 \n" +
	"\n" +
	"kubeconfig\x18\x01 \x01(\fH\x00R\n" +
	"kubeconfig\x12C\n" +
	"\n" +
	"in_cluster\x18\x02 \x01(\v2\".kubernetes.v1.InClusterCredentialH\x00R\tinCluster\x12R\n" +
	"\x0fservice_account\x18\x03 \x01(\v2'.kubernetes.v1.ServiceAccountCredentialH\x00R\x0eserviceAccountB\b\n" +
	"\x06source\"\x15\n" +
	"\x13InClusterCredential\"I\n" +
	"\x18ServiceAccountCredential\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aca_cert\x18\x02 \x01(\fR\x06caCert\"\xe2\x03\n" +
	"\x14CreateClusterRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1a\n" +
	"\x06org_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x05orgId\x12\"\n" +
	"\n" +
	"server_url\x18\x03 \x01(\tB\x03\xe0A\x02R\tserverUrl\x12J\n" +
	"\n" +
	"credential\x18\x04 \x01(\v2%.kubernetes.v1.ClusterCredentialInputB\x03\xe0A\x02R\n" +
	"credential\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\"\n" +
	"\fdistribution\x18\a \x01(\tR\fdistribution\x12G\n" +
	"\x06labels\x18\b \x03(\v2/.kubernetes.v1.CreateClusterRequest.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"owner_type\x18\t \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\n" +
	" \x01(\tR\aownerId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x15CreateClusterResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.kubernetes.v1.ClusterR\acluster\"h\n" +
	"\x13ListClustersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\"r\n" +
	"\x14ListClustersResponse\x122\n" +
	"\bclusters\x18\x01 \x03(\v2\x16.kubernetes.v1.ClusterR\bclusters\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"(\n" +
	"\x11GetClusterRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"F\n" +
	"\x12GetClusterResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.kubernetes.v1.ClusterR\acluster\"\xd1\x01\n" +
	"\x14UpdateClusterRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x120\n" +
	"\x11expected_revision\x18\x02 \x01(\x03B\x03\xe0A\x02R\x10expectedRevision\x12@\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\x120\n" +
	"\acluster\x18\x04 \x01(\v2\x16.kubernetes.v1.ClusterR\acluster\"I\n" +
	"\x15UpdateClusterResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.kubernetes.v1.ClusterR\acluster\"\x9f\x01\n" +
	"\x14DeleteClusterRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x120\n" +
	"\x11expected_revision\x18\x02 \x01(\x03B\x03\xe0A\x02R\x10expectedRevision\x12@\n" +
	"\rdelete_policy\x18\x03 \x01(\x0e2\x1b.kubernetes.v1.DeletePolicyR\fdeletePolicy\"I\n" +
	"\x15DeleteClusterResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.kubernetes.v1.ClusterR\acluster\"*\n" +
	"\x13ProbeClusterRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"H\n" +
	"\x14ProbeClusterResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.kubernetes.v1.ClusterR\acluster\"\xac\x01\n" +
	"\x17RotateCredentialRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x120\n" +
	"\x11expected_revision\x18\x02 \x01(\x03B\x03\xe0A\x02R\x10expectedRevision\x12J\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2%.kubernetes.v1.ClusterCredentialInputB\x03\xe0A\x02R\n" +
	"credential\"L\n" +
	"\x18RotateCredentialResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.kubernetes.v1.ClusterR\acluster*\xf3\x01\n" +
	"\rClusterStatus\x12\x1e\n" +
	"\x1aCLUSTER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CLUSTER_STATUS_CREATING\x10\x01\x12\x18\n" +
	"\x14CLUSTER_STATUS_READY\x10\x02\x12\x1a\n" +
	"\x16CLUSTER_STATUS_PROBING\x10\x03\x12\x1b\n" +
	"\x17CLUSTER_STATUS_DEGRADED\x10\x04\x12\x1b\n" +
	"\x17CLUSTER_STATUS_DELETING\x10\x05\x12\x1a\n" +
	"\x16CLUSTER_STATUS_DELETED\x10\x06\x12\x19\n" +
	"\x15CLUSTER_STATUS_FAILED\x10\a*g\n" +
	"\fDeletePolicy\x12\x1d\n" +
	"\x19DELETE_POLICY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DELETE_POLICY_DETACH_ONLY\x10\x01\x12\x19\n" +
	"\x15DELETE_POLICY_CASCADE\x10\x022\xf1\v\n" +
	"\x0eClusterService\x12\xd0\x01\n" +
	"\rCreateCluster\x12#.kubernetes.v1.CreateClusterRequest\x1a$.kubernetes.v1.CreateClusterResponse\"t\x92\xf4\x18P\b\x03\x12.\n" +
	"\x0ecreate_cluster\x12\rzone:{org_id}\x1a\vhub-service \x01\x1a\x1c\b\x01\x12\x12hub.cluster.create\x1a\x04high\x82\xd3\xe4\x93\x02\x1a:\x01*b\acluster\"\f/v1/clusters\x12\xdf\x01\n" +
	"\fListClusters\x12\".kubernetes.v1.ListClustersRequest\x1a#.kubernetes.v1.ListClustersResponse\"\x85\x01\x92\xf4\x18m\b\x02\x1a\x19\b\x01\x12\x10hub.cluster.list\x1a\x03low2?handler batch-checks view permission for every concrete cluster:\r\"\vhub-service\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/clusters\x12\xbe\x01\n" +
	"\n" +
	"GetCluster\x12 .kubernetes.v1.GetClusterRequest\x1a!.kubernetes.v1.GetClusterResponse\"k\x92\xf4\x18E\b\x03\x12'\n" +
	"\x04view\x12\x10k8s_cluster:{id}\x1a\vhub-service \x01\x1a\x18\b\x01\x12\x0fhub.cluster.get\x1a\x03low\x82\xd3\xe4\x93\x02\x1cb\acluster\x12\x11/v1/clusters/{id}\x12\xd2\x01\n" +
	"\rUpdateCluster\x12#.kubernetes.v1.UpdateClusterRequest\x1a$.kubernetes.v1.UpdateClusterResponse\"v\x92\xf4\x18M\b\x03\x12)\n" +
	"\x06manage\x12\x10k8s_cluster:{id}\x1a\vhub-service \x01\x1a\x1e\b\x01\x12\x12hub.cluster.update\x1a\x06medium\x82\xd3\xe4\x93\x02\x1f:\x01*b\acluster\x1a\x11/v1/clusters/{id}\x12\xc4\x01\n" +
	"\rDeleteCluster\x12#.kubernetes.v1.DeleteClusterRequest\x1a$.kubernetes.v1.DeleteClusterResponse\"h\x92\xf4\x18K\b\x03\x12)\n" +
	"\x06manage\x12\x10k8s_cluster:{id}\x1a\vhub-service \x01\x1a\x1c\b\x01\x12\x12hub.cluster.delete\x1a\x04high\x82\xd3\xe4\x93\x02\x13*\x11/v1/clusters/{id}\x12\xd2\x01\n" +
	"\fProbeCluster\x12\".kubernetes.v1.ProbeClusterRequest\x1a#.kubernetes.v1.ProbeClusterResponse\"y\x92\xf4\x18M\b\x03\x12*\n" +
	"\aoperate\x12\x10k8s_cluster:{id}\x1a\vhub-service \x01\x1a\x1d\b\x01\x12\x11hub.cluster.probe\x1a\x06medium\x82\xd3\xe4\x93\x02\"b\acluster\"\x17/v1/clusters/{id}:probe\x12\xf7\x01\n" +
	"\x10RotateCredential\x12&.kubernetes.v1.RotateCredentialRequest\x1a'.kubernetes.v1.RotateCredentialResponse\"\x91\x01\x92\xf4\x18V\b\x03\x12)\n" +
	"\x06manage\x12\x10k8s_cluster:{id}\x1a\vhub-service \x01\x1a'\b\x01\x12\x1dhub.cluster.rotate_credential\x1a\x04high\x82\xd3\xe4\x93\x021:\x01*b\acluster\"#/v1/clusters/{id}:rotate-credentialBCZAgithub.com/aisphereio/aisphere-hub/api/kubernetes/v1;kubernetesv1b\x06proto3"

var (
	file_kubernetes_v1_cluster_proto_rawDescOnce sync.Once
	file_kubernetes_v1_cluster_proto_rawDescData []byte
)

func file_kubernetes_v1_cluster_proto_rawDescGZIP() []byte {
	file_kubernetes_v1_cluster_proto_rawDescOnce.Do(func() {
		file_kubernetes_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubernetes_v1_cluster_proto_rawDesc), len(file_kubernetes_v1_cluster_proto_rawDesc)))
	})
	return file_kubernetes_v1_cluster_proto_rawDescData
}

var file_kubernetes_v1_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kubernetes_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_kubernetes_v1_cluster_proto_goTypes = []any{
	(ClusterStatus)(0),               // 0: kubernetes.v1.ClusterStatus
	(DeletePolicy)(0),                // 1: kubernetes.v1.DeletePolicy
	(*Cluster)(nil),                  // 2: kubernetes.v1.Cluster
	(*ClusterPermissions)(nil),       // 3: kubernetes.v1.ClusterPermissions
	(*ClusterCredentialInput)(nil),   // 4: kubernetes.v1.ClusterCredentialInput
	(*InClusterCredential)(nil),      // 5: kubernetes.v1.InClusterCredential
	(*ServiceAccountCredential)(nil), // 6: kubernetes.v1.ServiceAccountCredential
	(*CreateClusterRequest)(nil),     // 7: kubernetes.v1.CreateClusterRequest
	(*CreateClusterResponse)(nil),    // 8: kubernetes.v1.CreateClusterResponse
	(*ListClustersRequest)(nil),      // 9: kubernetes.v1.ListClustersRequest
	(*ListClustersResponse)(nil),     // 10: kubernetes.v1.ListClustersResponse
	(*GetClusterRequest)(nil),        // 11: kubernetes.v1.GetClusterRequest
	(*GetClusterResponse)(nil),       // 12: kubernetes.v1.GetClusterResponse
	(*UpdateClusterRequest)(nil),     // 13: kubernetes.v1.UpdateClusterRequest
	(*UpdateClusterResponse)(nil),    // 14: kubernetes.v1.UpdateClusterResponse
	(*DeleteClusterRequest)(nil),     // 15: kubernetes.v1.DeleteClusterRequest
	(*DeleteClusterResponse)(nil),    // 16: kubernetes.v1.DeleteClusterResponse
	(*ProbeClusterRequest)(nil),      // 17: kubernetes.v1.ProbeClusterRequest
	(*ProbeClusterResponse)(nil),     // 18: kubernetes.v1.ProbeClusterResponse
	(*RotateCredentialRequest)(nil),  // 19: kubernetes.v1.RotateCredentialRequest
	(*RotateCredentialResponse)(nil), // 20: kubernetes.v1.RotateCredentialResponse
	nil,                              // 21: kubernetes.v1.Cluster.LabelsEntry
	nil,                              // 22: kubernetes.v1.CreateClusterRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil),    // 23: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),    // 24: google.protobuf.FieldMask
}
var file_kubernetes_v1_cluster_proto_depIdxs = []int32{
	0,  // 0: kubernetes.v1.Cluster.status:type_name -> kubernetes.v1.ClusterStatus
	23, // 1: kubernetes.v1.Cluster.last_probe_time:type_name -> google.protobuf.Timestamp
	21, // 2: kubernetes.v1.Cluster.labels:type_name -> kubernetes.v1.Cluster.LabelsEntry
	3,  // 3: kubernetes.v1.Cluster.permissions:type_name -> kubernetes.v1.ClusterPermissions
	23, // 4: kubernetes.v1.Cluster.create_time:type_name -> google.protobuf.Timestamp
	23, // 5: kubernetes.v1.Cluster.update_time:type_name -> google.protobuf.Timestamp
	5,  // 6: kubernetes.v1.ClusterCredentialInput.in_cluster:type_name -> kubernetes.v1.InClusterCredential
	6,  // 7: kubernetes.v1.ClusterCredentialInput.service_account:type_name -> kubernetes.v1.ServiceAccountCredential
	4,  // 8: kubernetes.v1.CreateClusterRequest.credential:type_name -> kubernetes.v1.ClusterCredentialInput
	22, // 9: kubernetes.v1.CreateClusterRequest.labels:type_name -> kubernetes.v1.CreateClusterRequest.LabelsEntry
	2,  // 10: kubernetes.v1.CreateClusterResponse.cluster:type_name -> kubernetes.v1.Cluster
	2,  // 11: kubernetes.v1.ListClustersResponse.clusters:type_name -> kubernetes.v1.Cluster
	2,  // 12: kubernetes.v1.GetClusterResponse.cluster:type_name -> kubernetes.v1.Cluster
	24, // 13: kubernetes.v1.UpdateClusterRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 14: kubernetes.v1.UpdateClusterRequest.cluster:type_name -> kubernetes.v1.Cluster
	2,  // 15: kubernetes.v1.UpdateClusterResponse.cluster:type_name -> kubernetes.v1.Cluster
	1,  // 16: kubernetes.v1.DeleteClusterRequest.delete_policy:type_name -> kubernetes.v1.DeletePolicy
	2,  // 17: kubernetes.v1.DeleteClusterResponse.cluster:type_name -> kubernetes.v1.Cluster
	2,  // 18: kubernetes.v1.ProbeClusterResponse.cluster:type_name -> kubernetes.v1.Cluster
	4,  // 19: kubernetes.v1.RotateCredentialRequest.credential:type_name -> kubernetes.v1.ClusterCredentialInput
	2,  // 20: kubernetes.v1.RotateCredentialResponse.cluster:type_name -> kubernetes.v1.Cluster
	7,  // 21: kubernetes.v1.ClusterService.CreateCluster:input_type -> kubernetes.v1.CreateClusterRequest
	9,  // 22: kubernetes.v1.ClusterService.ListClusters:input_type -> kubernetes.v1.ListClustersRequest
	11, // 23: kubernetes.v1.ClusterService.GetCluster:input_type -> kubernetes.v1.GetClusterRequest
	13, // 24: kubernetes.v1.ClusterService.UpdateCluster:input_type -> kubernetes.v1.UpdateClusterRequest
	15, // 25: kubernetes.v1.ClusterService.DeleteCluster:input_type -> kubernetes.v1.DeleteClusterRequest
	17, // 26: kubernetes.v1.ClusterService.ProbeCluster:input_type -> kubernetes.v1.ProbeClusterRequest
	19, // 27: kubernetes.v1.ClusterService.RotateCredential:input_type -> kubernetes.v1.RotateCredentialRequest
	8,  // 28: kubernetes.v1.ClusterService.CreateCluster:output_type -> kubernetes.v1.CreateClusterResponse
	10, // 29: kubernetes.v1.ClusterService.ListClusters:output_type -> kubernetes.v1.ListClustersResponse
	12, // 30: kubernetes.v1.ClusterService.GetCluster:output_type -> kubernetes.v1.GetClusterResponse
	14, // 31: kubernetes.v1.ClusterService.UpdateCluster:output_type -> kubernetes.v1.UpdateClusterResponse
	16, // 32: kubernetes.v1.ClusterService.DeleteCluster:output_type -> kubernetes.v1.DeleteClusterResponse
	18, // 33: kubernetes.v1.ClusterService.ProbeCluster:output_type -> kubernetes.v1.ProbeClusterResponse
	20, // 34: kubernetes.v1.ClusterService.RotateCredential:output_type -> kubernetes.v1.RotateCredentialResponse
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_kubernetes_v1_cluster_proto_init() }
func file_kubernetes_v1_cluster_proto_init() {
	if File_kubernetes_v1_cluster_proto != nil {
		return
	}
	file_kubernetes_v1_cluster_proto_msgTypes[2].OneofWrappers = []any{
		(*ClusterCredentialInput_Kubeconfig)(nil),
		(*ClusterCredentialInput_InCluster)(nil),
		(*ClusterCredentialInput_ServiceAccount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubernetes_v1_cluster_proto_rawDesc), len(file_kubernetes_v1_cluster_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubernetes_v1_cluster_proto_goTypes,
		DependencyIndexes: file_kubernetes_v1_cluster_proto_depIdxs,
		EnumInfos:         file_kubernetes_v1_cluster_proto_enumTypes,
		MessageInfos:      file_kubernetes_v1_cluster_proto_msgTypes,
	}.Build()
	File_kubernetes_v1_cluster_proto = out.File
	file_kubernetes_v1_cluster_proto_goTypes = nil
	file_kubernetes_v1_cluster_proto_depIdxs = nil
}
