// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.4.18
// - protoc             (unknown)
// source: kubernetes/v1/cluster.proto

package kubernetesv1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationClusterServiceCreateCluster = "/kubernetes.v1.ClusterService/CreateCluster"
const OperationClusterServiceDeleteCluster = "/kubernetes.v1.ClusterService/DeleteCluster"
const OperationClusterServiceGetCluster = "/kubernetes.v1.ClusterService/GetCluster"
const OperationClusterServiceListClusters = "/kubernetes.v1.ClusterService/ListClusters"
const OperationClusterServiceProbeCluster = "/kubernetes.v1.ClusterService/ProbeCluster"
const OperationClusterServiceRotateCredential = "/kubernetes.v1.ClusterService/RotateCredential"
const OperationClusterServiceUpdateCluster = "/kubernetes.v1.ClusterService/UpdateCluster"

type ClusterServiceHTTPServer interface {
	CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error)
	DeleteCluster(context.Context, *DeleteClusterRequest) (*DeleteClusterResponse, error)
	GetCluster(context.Context, *GetClusterRequest) (*GetClusterResponse, error)
	ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error)
	ProbeCluster(context.Context, *ProbeClusterRequest) (*ProbeClusterResponse, error)
	RotateCredential(context.Context, *RotateCredentialRequest) (*RotateCredentialResponse, error)
	UpdateCluster(context.Context, *UpdateClusterRequest) (*UpdateClusterResponse, error)
}

func RegisterClusterServiceHTTPServer(s *http.Server, srv ClusterServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("DELETE", "/v1/clusters/{id}", _ClusterService_DeleteCluster0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/clusters", _ClusterService_ListClusters0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/clusters/{id}", _ClusterService_GetCluster0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/clusters", _ClusterService_CreateCluster0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/clusters/{id}:probe", _ClusterService_ProbeCluster0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/clusters/{id}:rotate-credential", _ClusterService_RotateCredential0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/clusters/{id}", _ClusterService_UpdateCluster0_HTTP_Handler(srv))
}

func _ClusterService_DeleteCluster0_HTTP_Handler(srv ClusterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteClusterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClusterServiceDeleteCluster)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCluster(ctx, req.(*DeleteClusterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteClusterResponse)
		return ctx.Result(200, reply)
	}
}

func _ClusterService_ListClusters0_HTTP_Handler(srv ClusterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListClustersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClusterServiceListClusters)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListClusters(ctx, req.(*ListClustersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListClustersResponse)
		return ctx.Result(200, reply)
	}
}

func _ClusterService_GetCluster0_HTTP_Handler(srv ClusterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetClusterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClusterServiceGetCluster)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCluster(ctx, req.(*GetClusterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetClusterResponse)
		return ctx.Result(200, reply.Cluster)
	}
}

func _ClusterService_CreateCluster0_HTTP_Handler(srv ClusterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateClusterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClusterServiceCreateCluster)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCluster(ctx, req.(*CreateClusterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateClusterResponse)
		return ctx.Result(200, reply.Cluster)
	}
}

func _ClusterService_ProbeCluster0_HTTP_Handler(srv ClusterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProbeClusterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClusterServiceProbeCluster)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ProbeCluster(ctx, req.(*ProbeClusterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProbeClusterResponse)
		return ctx.Result(200, reply.Cluster)
	}
}

func _ClusterService_RotateCredential0_HTTP_Handler(srv ClusterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RotateCredentialRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClusterServiceRotateCredential)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RotateCredential(ctx, req.(*RotateCredentialRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RotateCredentialResponse)
		return ctx.Result(200, reply.Cluster)
	}
}

func _ClusterService_UpdateCluster0_HTTP_Handler(srv ClusterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateClusterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClusterServiceUpdateCluster)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCluster(ctx, req.(*UpdateClusterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateClusterResponse)
		return ctx.Result(200, reply.Cluster)
	}
}

type ClusterServiceHTTPClient interface {
	CreateCluster(ctx context.Context, req *CreateClusterRequest, opts ...http.CallOption) (rsp *CreateClusterResponse, err error)
	DeleteCluster(ctx context.Context, req *DeleteClusterRequest, opts ...http.CallOption) (rsp *DeleteClusterResponse, err error)
	GetCluster(ctx context.Context, req *GetClusterRequest, opts ...http.CallOption) (rsp *GetClusterResponse, err error)
	ListClusters(ctx context.Context, req *ListClustersRequest, opts ...http.CallOption) (rsp *ListClustersResponse, err error)
	ProbeCluster(ctx context.Context, req *ProbeClusterRequest, opts ...http.CallOption) (rsp *ProbeClusterResponse, err error)
	RotateCredential(ctx context.Context, req *RotateCredentialRequest, opts ...http.CallOption) (rsp *RotateCredentialResponse, err error)
	UpdateCluster(ctx context.Context, req *UpdateClusterRequest, opts ...http.CallOption) (rsp *UpdateClusterResponse, err error)
}

type ClusterServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewClusterServiceHTTPClient(client *http.Client) ClusterServiceHTTPClient {
	return &ClusterServiceHTTPClientImpl{client}
}

func (c *ClusterServiceHTTPClientImpl) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...http.CallOption) (*CreateClusterResponse, error) {
	var out CreateClusterResponse
	pattern := "/v1/clusters"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationClusterServiceCreateCluster),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Cluster, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ClusterServiceHTTPClientImpl) DeleteCluster(ctx context.Context, in *DeleteClusterRequest, opts ...http.CallOption) (*DeleteClusterResponse, error) {
	var out DeleteClusterResponse
	pattern := "/v1/clusters/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationClusterServiceDeleteCluster),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ClusterServiceHTTPClientImpl) GetCluster(ctx context.Context, in *GetClusterRequest, opts ...http.CallOption) (*GetClusterResponse, error) {
	var out GetClusterResponse
	pattern := "/v1/clusters/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationClusterServiceGetCluster),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out.Cluster, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ClusterServiceHTTPClientImpl) ListClusters(ctx context.Context, in *ListClustersRequest, opts ...http.CallOption) (*ListClustersResponse, error) {
	var out ListClustersResponse
	pattern := "/v1/clusters"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationClusterServiceListClusters),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ClusterServiceHTTPClientImpl) ProbeCluster(ctx context.Context, in *ProbeClusterRequest, opts ...http.CallOption) (*ProbeClusterResponse, error) {
	var out ProbeClusterResponse
	pattern := "/v1/clusters/{id}:probe"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationClusterServiceProbeCluster),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, nil, &out.Cluster, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ClusterServiceHTTPClientImpl) RotateCredential(ctx context.Context, in *RotateCredentialRequest, opts ...http.CallOption) (*RotateCredentialResponse, error) {
	var out RotateCredentialResponse
	pattern := "/v1/clusters/{id}:rotate-credential"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationClusterServiceRotateCredential),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.Cluster, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ClusterServiceHTTPClientImpl) UpdateCluster(ctx context.Context, in *UpdateClusterRequest, opts ...http.CallOption) (*UpdateClusterResponse, error) {
	var out UpdateClusterResponse
	pattern := "/v1/clusters/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationClusterServiceUpdateCluster),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out.Cluster, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
