// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: kubernetes/v1/sandbox.proto

package kubernetesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_CreateSandboxTemplate_FullMethodName = "/kubernetes.v1.SandboxService/CreateSandboxTemplate"
	SandboxService_ListSandboxTemplates_FullMethodName  = "/kubernetes.v1.SandboxService/ListSandboxTemplates"
	SandboxService_GetSandboxTemplate_FullMethodName    = "/kubernetes.v1.SandboxService/GetSandboxTemplate"
	SandboxService_DeleteSandboxTemplate_FullMethodName = "/kubernetes.v1.SandboxService/DeleteSandboxTemplate"
	SandboxService_CreateSandbox_FullMethodName         = "/kubernetes.v1.SandboxService/CreateSandbox"
	SandboxService_ListSandboxes_FullMethodName         = "/kubernetes.v1.SandboxService/ListSandboxes"
	SandboxService_GetSandbox_FullMethodName            = "/kubernetes.v1.SandboxService/GetSandbox"
	SandboxService_DeleteSandbox_FullMethodName         = "/kubernetes.v1.SandboxService/DeleteSandbox"
	SandboxService_SyncSandboxes_FullMethodName         = "/kubernetes.v1.SandboxService/SyncSandboxes"
	SandboxService_CreateWarmPool_FullMethodName        = "/kubernetes.v1.SandboxService/CreateWarmPool"
	SandboxService_ListWarmPools_FullMethodName         = "/kubernetes.v1.SandboxService/ListWarmPools"
	SandboxService_DeleteWarmPool_FullMethodName        = "/kubernetes.v1.SandboxService/DeleteWarmPool"
	SandboxService_SyncWarmPools_FullMethodName         = "/kubernetes.v1.SandboxService/SyncWarmPools"
	SandboxService_CreateSandboxClaim_FullMethodName    = "/kubernetes.v1.SandboxService/CreateSandboxClaim"
	SandboxService_ListSandboxClaims_FullMethodName     = "/kubernetes.v1.SandboxService/ListSandboxClaims"
	SandboxService_DeleteSandboxClaim_FullMethodName    = "/kubernetes.v1.SandboxService/DeleteSandboxClaim"
	SandboxService_SyncSandboxClaims_FullMethodName     = "/kubernetes.v1.SandboxService/SyncSandboxClaims"
	SandboxService_ListSandboxTools_FullMethodName      = "/kubernetes.v1.SandboxService/ListSandboxTools"
	SandboxService_CallSandboxTool_FullMethodName       = "/kubernetes.v1.SandboxService/CallSandboxTool"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxService manages AISphere Agent Sandbox records backed by the upstream
// agent-sandbox operator (CRDs: Sandbox, SandboxTemplate, SandboxWarmPool,
// SandboxClaim — group agents.x-k8s.io, design §11). The resource hierarchy is
// Cluster → Namespace → Sandbox. Namespace `use` permission is the base
// authorization boundary for creating Sandboxes (design §11).
type SandboxServiceClient interface {
	CreateSandboxTemplate(ctx context.Context, in *CreateSandboxTemplateRequest, opts ...grpc.CallOption) (*CreateSandboxTemplateResponse, error)
	ListSandboxTemplates(ctx context.Context, in *ListSandboxTemplatesRequest, opts ...grpc.CallOption) (*ListSandboxTemplatesResponse, error)
	GetSandboxTemplate(ctx context.Context, in *GetSandboxTemplateRequest, opts ...grpc.CallOption) (*GetSandboxTemplateResponse, error)
	DeleteSandboxTemplate(ctx context.Context, in *DeleteSandboxTemplateRequest, opts ...grpc.CallOption) (*DeleteSandboxTemplateResponse, error)
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error)
	DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error)
	SyncSandboxes(ctx context.Context, in *SyncSandboxesRequest, opts ...grpc.CallOption) (*SyncSandboxesResponse, error)
	CreateWarmPool(ctx context.Context, in *CreateWarmPoolRequest, opts ...grpc.CallOption) (*CreateWarmPoolResponse, error)
	ListWarmPools(ctx context.Context, in *ListWarmPoolsRequest, opts ...grpc.CallOption) (*ListWarmPoolsResponse, error)
	DeleteWarmPool(ctx context.Context, in *DeleteWarmPoolRequest, opts ...grpc.CallOption) (*DeleteWarmPoolResponse, error)
	SyncWarmPools(ctx context.Context, in *SyncWarmPoolsRequest, opts ...grpc.CallOption) (*SyncWarmPoolsResponse, error)
	CreateSandboxClaim(ctx context.Context, in *CreateSandboxClaimRequest, opts ...grpc.CallOption) (*CreateSandboxClaimResponse, error)
	ListSandboxClaims(ctx context.Context, in *ListSandboxClaimsRequest, opts ...grpc.CallOption) (*ListSandboxClaimsResponse, error)
	DeleteSandboxClaim(ctx context.Context, in *DeleteSandboxClaimRequest, opts ...grpc.CallOption) (*DeleteSandboxClaimResponse, error)
	SyncSandboxClaims(ctx context.Context, in *SyncSandboxClaimsRequest, opts ...grpc.CallOption) (*SyncSandboxClaimsResponse, error)
	ListSandboxTools(ctx context.Context, in *ListSandboxToolsRequest, opts ...grpc.CallOption) (*ListSandboxToolsResponse, error)
	CallSandboxTool(ctx context.Context, in *CallSandboxToolRequest, opts ...grpc.CallOption) (*CallSandboxToolResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) CreateSandboxTemplate(ctx context.Context, in *CreateSandboxTemplateRequest, opts ...grpc.CallOption) (*CreateSandboxTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxTemplateResponse)
	err := c.cc.Invoke(ctx, SandboxService_CreateSandboxTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListSandboxTemplates(ctx context.Context, in *ListSandboxTemplatesRequest, opts ...grpc.CallOption) (*ListSandboxTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxTemplatesResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListSandboxTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSandboxTemplate(ctx context.Context, in *GetSandboxTemplateRequest, opts ...grpc.CallOption) (*GetSandboxTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxTemplateResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetSandboxTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteSandboxTemplate(ctx context.Context, in *DeleteSandboxTemplateRequest, opts ...grpc.CallOption) (*DeleteSandboxTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSandboxTemplateResponse)
	err := c.cc.Invoke(ctx, SandboxService_DeleteSandboxTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_DeleteSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SyncSandboxes(ctx context.Context, in *SyncSandboxesRequest, opts ...grpc.CallOption) (*SyncSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncSandboxesResponse)
	err := c.cc.Invoke(ctx, SandboxService_SyncSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CreateWarmPool(ctx context.Context, in *CreateWarmPoolRequest, opts ...grpc.CallOption) (*CreateWarmPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWarmPoolResponse)
	err := c.cc.Invoke(ctx, SandboxService_CreateWarmPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListWarmPools(ctx context.Context, in *ListWarmPoolsRequest, opts ...grpc.CallOption) (*ListWarmPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWarmPoolsResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListWarmPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteWarmPool(ctx context.Context, in *DeleteWarmPoolRequest, opts ...grpc.CallOption) (*DeleteWarmPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWarmPoolResponse)
	err := c.cc.Invoke(ctx, SandboxService_DeleteWarmPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SyncWarmPools(ctx context.Context, in *SyncWarmPoolsRequest, opts ...grpc.CallOption) (*SyncWarmPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncWarmPoolsResponse)
	err := c.cc.Invoke(ctx, SandboxService_SyncWarmPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CreateSandboxClaim(ctx context.Context, in *CreateSandboxClaimRequest, opts ...grpc.CallOption) (*CreateSandboxClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxClaimResponse)
	err := c.cc.Invoke(ctx, SandboxService_CreateSandboxClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListSandboxClaims(ctx context.Context, in *ListSandboxClaimsRequest, opts ...grpc.CallOption) (*ListSandboxClaimsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxClaimsResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListSandboxClaims_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteSandboxClaim(ctx context.Context, in *DeleteSandboxClaimRequest, opts ...grpc.CallOption) (*DeleteSandboxClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSandboxClaimResponse)
	err := c.cc.Invoke(ctx, SandboxService_DeleteSandboxClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SyncSandboxClaims(ctx context.Context, in *SyncSandboxClaimsRequest, opts ...grpc.CallOption) (*SyncSandboxClaimsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncSandboxClaimsResponse)
	err := c.cc.Invoke(ctx, SandboxService_SyncSandboxClaims_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListSandboxTools(ctx context.Context, in *ListSandboxToolsRequest, opts ...grpc.CallOption) (*ListSandboxToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxToolsResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListSandboxTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CallSandboxTool(ctx context.Context, in *CallSandboxToolRequest, opts ...grpc.CallOption) (*CallSandboxToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallSandboxToolResponse)
	err := c.cc.Invoke(ctx, SandboxService_CallSandboxTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
//
// SandboxService manages AISphere Agent Sandbox records backed by the upstream
// agent-sandbox operator (CRDs: Sandbox, SandboxTemplate, SandboxWarmPool,
// SandboxClaim — group agents.x-k8s.io, design §11). The resource hierarchy is
// Cluster → Namespace → Sandbox. Namespace `use` permission is the base
// authorization boundary for creating Sandboxes (design §11).
type SandboxServiceServer interface {
	CreateSandboxTemplate(context.Context, *CreateSandboxTemplateRequest) (*CreateSandboxTemplateResponse, error)
	ListSandboxTemplates(context.Context, *ListSandboxTemplatesRequest) (*ListSandboxTemplatesResponse, error)
	GetSandboxTemplate(context.Context, *GetSandboxTemplateRequest) (*GetSandboxTemplateResponse, error)
	DeleteSandboxTemplate(context.Context, *DeleteSandboxTemplateRequest) (*DeleteSandboxTemplateResponse, error)
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	GetSandbox(context.Context, *GetSandboxRequest) (*GetSandboxResponse, error)
	DeleteSandbox(context.Context, *DeleteSandboxRequest) (*DeleteSandboxResponse, error)
	SyncSandboxes(context.Context, *SyncSandboxesRequest) (*SyncSandboxesResponse, error)
	CreateWarmPool(context.Context, *CreateWarmPoolRequest) (*CreateWarmPoolResponse, error)
	ListWarmPools(context.Context, *ListWarmPoolsRequest) (*ListWarmPoolsResponse, error)
	DeleteWarmPool(context.Context, *DeleteWarmPoolRequest) (*DeleteWarmPoolResponse, error)
	SyncWarmPools(context.Context, *SyncWarmPoolsRequest) (*SyncWarmPoolsResponse, error)
	CreateSandboxClaim(context.Context, *CreateSandboxClaimRequest) (*CreateSandboxClaimResponse, error)
	ListSandboxClaims(context.Context, *ListSandboxClaimsRequest) (*ListSandboxClaimsResponse, error)
	DeleteSandboxClaim(context.Context, *DeleteSandboxClaimRequest) (*DeleteSandboxClaimResponse, error)
	SyncSandboxClaims(context.Context, *SyncSandboxClaimsRequest) (*SyncSandboxClaimsResponse, error)
	ListSandboxTools(context.Context, *ListSandboxToolsRequest) (*ListSandboxToolsResponse, error)
	CallSandboxTool(context.Context, *CallSandboxToolRequest) (*CallSandboxToolResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) CreateSandboxTemplate(context.Context, *CreateSandboxTemplateRequest) (*CreateSandboxTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSandboxTemplate not implemented")
}
func (UnimplementedSandboxServiceServer) ListSandboxTemplates(context.Context, *ListSandboxTemplatesRequest) (*ListSandboxTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSandboxTemplates not implemented")
}
func (UnimplementedSandboxServiceServer) GetSandboxTemplate(context.Context, *GetSandboxTemplateRequest) (*GetSandboxTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxTemplate not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteSandboxTemplate(context.Context, *DeleteSandboxTemplateRequest) (*DeleteSandboxTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSandboxTemplate not implemented")
}
func (UnimplementedSandboxServiceServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedSandboxServiceServer) GetSandbox(context.Context, *GetSandboxRequest) (*GetSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteSandbox(context.Context, *DeleteSandboxRequest) (*DeleteSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) SyncSandboxes(context.Context, *SyncSandboxesRequest) (*SyncSandboxesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncSandboxes not implemented")
}
func (UnimplementedSandboxServiceServer) CreateWarmPool(context.Context, *CreateWarmPoolRequest) (*CreateWarmPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWarmPool not implemented")
}
func (UnimplementedSandboxServiceServer) ListWarmPools(context.Context, *ListWarmPoolsRequest) (*ListWarmPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWarmPools not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteWarmPool(context.Context, *DeleteWarmPoolRequest) (*DeleteWarmPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWarmPool not implemented")
}
func (UnimplementedSandboxServiceServer) SyncWarmPools(context.Context, *SyncWarmPoolsRequest) (*SyncWarmPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncWarmPools not implemented")
}
func (UnimplementedSandboxServiceServer) CreateSandboxClaim(context.Context, *CreateSandboxClaimRequest) (*CreateSandboxClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSandboxClaim not implemented")
}
func (UnimplementedSandboxServiceServer) ListSandboxClaims(context.Context, *ListSandboxClaimsRequest) (*ListSandboxClaimsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSandboxClaims not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteSandboxClaim(context.Context, *DeleteSandboxClaimRequest) (*DeleteSandboxClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSandboxClaim not implemented")
}
func (UnimplementedSandboxServiceServer) SyncSandboxClaims(context.Context, *SyncSandboxClaimsRequest) (*SyncSandboxClaimsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncSandboxClaims not implemented")
}
func (UnimplementedSandboxServiceServer) ListSandboxTools(context.Context, *ListSandboxToolsRequest) (*ListSandboxToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSandboxTools not implemented")
}
func (UnimplementedSandboxServiceServer) CallSandboxTool(context.Context, *CallSandboxToolRequest) (*CallSandboxToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallSandboxTool not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call pancis, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_CreateSandboxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CreateSandboxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CreateSandboxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CreateSandboxTemplate(ctx, req.(*CreateSandboxTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListSandboxTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListSandboxTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListSandboxTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListSandboxTemplates(ctx, req.(*ListSandboxTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSandboxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSandboxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSandboxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSandboxTemplate(ctx, req.(*GetSandboxTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteSandboxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteSandboxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteSandboxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteSandboxTemplate(ctx, req.(*DeleteSandboxTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSandbox(ctx, req.(*GetSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteSandbox(ctx, req.(*DeleteSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SyncSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SyncSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SyncSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SyncSandboxes(ctx, req.(*SyncSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CreateWarmPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWarmPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CreateWarmPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CreateWarmPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CreateWarmPool(ctx, req.(*CreateWarmPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListWarmPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWarmPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListWarmPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListWarmPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListWarmPools(ctx, req.(*ListWarmPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteWarmPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWarmPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteWarmPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteWarmPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteWarmPool(ctx, req.(*DeleteWarmPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SyncWarmPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncWarmPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SyncWarmPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SyncWarmPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SyncWarmPools(ctx, req.(*SyncWarmPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CreateSandboxClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CreateSandboxClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CreateSandboxClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CreateSandboxClaim(ctx, req.(*CreateSandboxClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListSandboxClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListSandboxClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListSandboxClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListSandboxClaims(ctx, req.(*ListSandboxClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteSandboxClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteSandboxClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteSandboxClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteSandboxClaim(ctx, req.(*DeleteSandboxClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SyncSandboxClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSandboxClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SyncSandboxClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SyncSandboxClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SyncSandboxClaims(ctx, req.(*SyncSandboxClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListSandboxTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListSandboxTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListSandboxTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListSandboxTools(ctx, req.(*ListSandboxToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CallSandboxTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallSandboxToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CallSandboxTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CallSandboxTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CallSandboxTool(ctx, req.(*CallSandboxToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubernetes.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandboxTemplate",
			Handler:    _SandboxService_CreateSandboxTemplate_Handler,
		},
		{
			MethodName: "ListSandboxTemplates",
			Handler:    _SandboxService_ListSandboxTemplates_Handler,
		},
		{
			MethodName: "GetSandboxTemplate",
			Handler:    _SandboxService_GetSandboxTemplate_Handler,
		},
		{
			MethodName: "DeleteSandboxTemplate",
			Handler:    _SandboxService_DeleteSandboxTemplate_Handler,
		},
		{
			MethodName: "CreateSandbox",
			Handler:    _SandboxService_CreateSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _SandboxService_ListSandboxes_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _SandboxService_GetSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _SandboxService_DeleteSandbox_Handler,
		},
		{
			MethodName: "SyncSandboxes",
			Handler:    _SandboxService_SyncSandboxes_Handler,
		},
		{
			MethodName: "CreateWarmPool",
			Handler:    _SandboxService_CreateWarmPool_Handler,
		},
		{
			MethodName: "ListWarmPools",
			Handler:    _SandboxService_ListWarmPools_Handler,
		},
		{
			MethodName: "DeleteWarmPool",
			Handler:    _SandboxService_DeleteWarmPool_Handler,
		},
		{
			MethodName: "SyncWarmPools",
			Handler:    _SandboxService_SyncWarmPools_Handler,
		},
		{
			MethodName: "CreateSandboxClaim",
			Handler:    _SandboxService_CreateSandboxClaim_Handler,
		},
		{
			MethodName: "ListSandboxClaims",
			Handler:    _SandboxService_ListSandboxClaims_Handler,
		},
		{
			MethodName: "DeleteSandboxClaim",
			Handler:    _SandboxService_DeleteSandboxClaim_Handler,
		},
		{
			MethodName: "SyncSandboxClaims",
			Handler:    _SandboxService_SyncSandboxClaims_Handler,
		},
		{
			MethodName: "ListSandboxTools",
			Handler:    _SandboxService_ListSandboxTools_Handler,
		},
		{
			MethodName: "CallSandboxTool",
			Handler:    _SandboxService_CallSandboxTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kubernetes/v1/sandbox.proto",
}
