// Code generated by protoc-gen-go-authz. DO NOT EDIT.
// versions:
// - protoc-gen-go-authz v0.4.1
// source: authz/v1/authz.proto

package authzv1

import (
	context "context"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	contextx "github.com/aisphereio/kernel/contextx"
	requestx "github.com/aisphereio/kernel/requestx"
	grpc "google.golang.org/grpc"
	strings "strings"
)

var _ = grpc.EmptyCallOption{}

var AuthzServiceAuthzRules = authz.Rules{
	"/authz.v1.AuthzService/WriteRelationships": {
		Service:    "authz.v1.AuthzService",
		Method:     "WriteRelationships",
		FullMethod: "/authz.v1.AuthzService/WriteRelationships",
		Action:     "write",
		Resource:   "aihub:authz:relationship:*",
		Audience:   "aihub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "authz.relationship.write",
		AuditRisk:  "high",
	},
	"/authz.v1.AuthzService/DeleteRelationships": {
		Service:    "authz.v1.AuthzService",
		Method:     "DeleteRelationships",
		FullMethod: "/authz.v1.AuthzService/DeleteRelationships",
		Action:     "delete",
		Resource:   "aihub:authz:relationship:*",
		Audience:   "aihub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "authz.relationship.delete",
		AuditRisk:  "high",
	},
	"/authz.v1.AuthzService/ReadSchema": {
		Service:    "authz.v1.AuthzService",
		Method:     "ReadSchema",
		FullMethod: "/authz.v1.AuthzService/ReadSchema",
		Action:     "read",
		Resource:   "aihub:authz:schema",
		Audience:   "aihub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "authz.schema.read",
		AuditRisk:  "medium",
	},
	"/authz.v1.AuthzService/WriteSchema": {
		Service:    "authz.v1.AuthzService",
		Method:     "WriteSchema",
		FullMethod: "/authz.v1.AuthzService/WriteSchema",
		Action:     "write",
		Resource:   "aihub:authz:schema",
		Audience:   "aihub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "authz.schema.write",
		AuditRisk:  "critical",
	},
}

const AuthzServiceAuthzManifestJSON = `{
  "methods": [
    {
      "service": "authz.v1.AuthzService",
      "method": "WriteRelationships",
      "full_method": "/authz.v1.AuthzService/WriteRelationships",
      "action": "write",
      "resource": "aihub:authz:relationship:*",
      "audience": "aihub-service",
      "mode": "CHECK_ONLY",
      "audit_event": "authz.relationship.write",
      "audit_risk": "high"
    },
    {
      "service": "authz.v1.AuthzService",
      "method": "DeleteRelationships",
      "full_method": "/authz.v1.AuthzService/DeleteRelationships",
      "action": "delete",
      "resource": "aihub:authz:relationship:*",
      "audience": "aihub-service",
      "mode": "CHECK_ONLY",
      "audit_event": "authz.relationship.delete",
      "audit_risk": "high"
    },
    {
      "service": "authz.v1.AuthzService",
      "method": "ReadSchema",
      "full_method": "/authz.v1.AuthzService/ReadSchema",
      "action": "read",
      "resource": "aihub:authz:schema",
      "audience": "aihub-service",
      "mode": "CHECK_ONLY",
      "audit_event": "authz.schema.read",
      "audit_risk": "medium"
    },
    {
      "service": "authz.v1.AuthzService",
      "method": "WriteSchema",
      "full_method": "/authz.v1.AuthzService/WriteSchema",
      "action": "write",
      "resource": "aihub:authz:schema",
      "audience": "aihub-service",
      "mode": "CHECK_ONLY",
      "audit_event": "authz.schema.write",
      "audit_risk": "critical"
    }
  ],
  "service": "authz.v1.AuthzService"
}`

// AuthzServiceRequestInfoResolver maps generated proto access policy into requestx.Info.
// It should be passed to autowire.WithRequestInfoResolver / WithClientRequestInfoResolver.
func AuthzServiceRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	rule, ok := AuthzServiceAuthzRules[operation]
	if !ok && operation != "" {
		rule, ok = AuthzServiceAuthzRules[_AuthzServiceNormalizeOperation(operation)]
	}
	if !ok {
		return requestx.Info{}, false, nil
	}
	info := requestx.Info{
		Service:       rule.Service,
		Method:        rule.Method,
		Operation:     rule.FullMethod,
		Exposure:      v1.Exposure_AUTHORIZED,
		Action:        rule.Action,
		Resource:      rule.Resource,
		TargetService: rule.Audience,
		Labels:        map[string]string{"authz_mode": string(rule.Mode)},
	}
	if rule.AuditEvent != "" {
		info.Labels["audit_event"] = rule.AuditEvent
	}
	if rule.AuditRisk != "" {
		info.Labels["audit_risk"] = rule.AuditRisk
	}
	if rule.Capability != "" {
		info.Labels["capability"] = rule.Capability
	}
	return info.Normalize(), true, nil
}

// AuthzServiceAccessResolver maps generated proto authz rules into accessx.Check.
// It matches middleware/access.Resolver, so services can pass it directly to autowire.WithAccess.
func AuthzServiceAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := AuthzServiceAuthzRules[operation]
	if !ok && operation != "" {
		rule, ok = AuthzServiceAuthzRules[_AuthzServiceNormalizeOperation(operation)]
	}
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _AuthzServiceNormalizeOperation(operation string) string {
	switch operation {
	case "WriteRelationships", "authz.v1.AuthzService/WriteRelationships":
		return "/authz.v1.AuthzService/WriteRelationships"
	case "DeleteRelationships", "authz.v1.AuthzService/DeleteRelationships":
		return "/authz.v1.AuthzService/DeleteRelationships"
	case "ReadSchema", "authz.v1.AuthzService/ReadSchema":
		return "/authz.v1.AuthzService/ReadSchema"
	case "WriteSchema", "authz.v1.AuthzService/WriteSchema":
		return "/authz.v1.AuthzService/WriteSchema"
	default:
		return operation
	}
}

type AuthzServiceSecureClient struct {
	raw      AuthzServiceClient
	guard    authz.Guard
	resolver authz.RuleResolver
}

func NewAuthzServiceSecureClient(raw AuthzServiceClient, guard authz.Guard) *AuthzServiceSecureClient {
	return &AuthzServiceSecureClient{raw: raw, guard: guard, resolver: authz.RuleResolver{}}
}

var _ AuthzServiceClient = (*AuthzServiceSecureClient)(nil)

func (c *AuthzServiceSecureClient) CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error) {
	return c.raw.CheckPermission(ctx, in, opts...)
}

func (c *AuthzServiceSecureClient) BatchCheckPermissions(ctx context.Context, in *BatchCheckPermissionsRequest, opts ...grpc.CallOption) (*BatchCheckPermissionsResponse, error) {
	return c.raw.BatchCheckPermissions(ctx, in, opts...)
}

func (c *AuthzServiceSecureClient) WriteRelationships(ctx context.Context, in *WriteRelationshipsRequest, opts ...grpc.CallOption) (*WriteRelationshipsResponse, error) {
	if c != nil && c.guard != nil {
		rule := AuthzServiceAuthzRules["/authz.v1.AuthzService/WriteRelationships"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _AuthzServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.WriteRelationships(ctx, in, opts...)
}

func (c *AuthzServiceSecureClient) DeleteRelationships(ctx context.Context, in *DeleteRelationshipsRequest, opts ...grpc.CallOption) (*DeleteRelationshipsResponse, error) {
	if c != nil && c.guard != nil {
		rule := AuthzServiceAuthzRules["/authz.v1.AuthzService/DeleteRelationships"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _AuthzServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.DeleteRelationships(ctx, in, opts...)
}

func (c *AuthzServiceSecureClient) ReadRelationships(ctx context.Context, in *ReadRelationshipsRequest, opts ...grpc.CallOption) (*ReadRelationshipsResponse, error) {
	return c.raw.ReadRelationships(ctx, in, opts...)
}

func (c *AuthzServiceSecureClient) LookupResources(ctx context.Context, in *LookupResourcesRequest, opts ...grpc.CallOption) (*LookupResourcesResponse, error) {
	return c.raw.LookupResources(ctx, in, opts...)
}

func (c *AuthzServiceSecureClient) LookupSubjects(ctx context.Context, in *LookupSubjectsRequest, opts ...grpc.CallOption) (*LookupSubjectsResponse, error) {
	return c.raw.LookupSubjects(ctx, in, opts...)
}

func (c *AuthzServiceSecureClient) ReadSchema(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error) {
	if c != nil && c.guard != nil {
		rule := AuthzServiceAuthzRules["/authz.v1.AuthzService/ReadSchema"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _AuthzServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.ReadSchema(ctx, in, opts...)
}

func (c *AuthzServiceSecureClient) WriteSchema(ctx context.Context, in *WriteSchemaRequest, opts ...grpc.CallOption) (*WriteSchemaResponse, error) {
	if c != nil && c.guard != nil {
		rule := AuthzServiceAuthzRules["/authz.v1.AuthzService/WriteSchema"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _AuthzServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.WriteSchema(ctx, in, opts...)
}

func _AuthzServiceAuthzSubjectFromContext(ctx context.Context) authz.SubjectRef {
	p := contextx.PrincipalFromContext(ctx)
	if p == nil {
		return authz.SubjectRef{}
	}
	typ := authz.SubjectTypeUser
	if strings.HasPrefix(p.SubjectID, "svc:") {
		typ = authz.SubjectTypeService
	}
	return authz.SubjectRef{Type: typ, ID: p.SubjectID}
}
