// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tool/v1/tool.proto

package toolv1

import (
	_ "github.com/aisphereio/kernel/api/aisphere/access/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tool is the catalog record for an invocable agent capability. Tool content
// is versioned (ToolVersionRecord); latest_version points at the active one.
type Tool struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                        `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // active | disabled | builtin
	Scope         string                        `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`   // system | project | private
	Labels        map[string]string             `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Object        string                        `protobuf:"bytes,7,opt,name=object,proto3" json:"object,omitempty"`                                 // "tool:{id}" SpiceDB object ref
	OwnerSubject  string                        `protobuf:"bytes,8,opt,name=owner_subject,json=ownerSubject,proto3" json:"owner_subject,omitempty"` // "{type}:{id}" of the owner
	LatestVersion string                        `protobuf:"bytes,9,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	Versions      map[string]*ToolVersionRecord `protobuf:"bytes,10,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreateTime    *timestamppb.Timestamp        `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp        `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_tool_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{0}
}

func (x *Tool) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tool) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tool) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Tool) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Tool) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *Tool) GetOwnerSubject() string {
	if x != nil {
		return x.OwnerSubject
	}
	return ""
}

func (x *Tool) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *Tool) GetVersions() map[string]*ToolVersionRecord {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *Tool) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Tool) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// ToolVersionRecord is an immutable snapshot of a Tool definition at a version.
type ToolVersionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	CommitMsg     string                 `protobuf:"bytes,5,opt,name=commit_msg,json=commitMsg,proto3" json:"commit_msg,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Definition    *ToolDefinition        `protobuf:"bytes,7,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolVersionRecord) Reset() {
	*x = ToolVersionRecord{}
	mi := &file_tool_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolVersionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolVersionRecord) ProtoMessage() {}

func (x *ToolVersionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolVersionRecord.ProtoReflect.Descriptor instead.
func (*ToolVersionRecord) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ToolVersionRecord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ToolVersionRecord) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ToolVersionRecord) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ToolVersionRecord) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ToolVersionRecord) GetCommitMsg() string {
	if x != nil {
		return x.CommitMsg
	}
	return ""
}

func (x *ToolVersionRecord) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ToolVersionRecord) GetDefinition() *ToolDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

// ToolDefinition is the full specification a Runtime reads to register and
// enforce a tool. Complex/nested structures (input_schema, output_schema,
// config, metadata, headers, env) are carried as JSON strings because proto
// cannot express arbitrary JSON Schema; the service layer marshals/unmarshals.
type ToolDefinition struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Runtime       *ToolRuntimeDefinition   `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Execution     *ToolExecutionDefinition `protobuf:"bytes,2,opt,name=execution,proto3" json:"execution,omitempty"`
	InputSchema   string                   `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`    // JSON Schema (string)
	OutputSchema  string                   `protobuf:"bytes,4,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"` // JSON Schema (string)
	TimeoutMillis int32                    `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	Retry         *ToolRetryPolicy         `protobuf:"bytes,6,opt,name=retry,proto3" json:"retry,omitempty"`
	Metadata      string                   `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"` // arbitrary JSON (string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_tool_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDefinition) GetRuntime() *ToolRuntimeDefinition {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *ToolDefinition) GetExecution() *ToolExecutionDefinition {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *ToolDefinition) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *ToolDefinition) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

func (x *ToolDefinition) GetTimeoutMillis() int32 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *ToolDefinition) GetRetry() *ToolRetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *ToolDefinition) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// ToolRuntimeDefinition describes how the tool is invoked at the protocol level.
type ToolRuntimeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                               // builtin | mcp | openapi | http | function
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`                           // MCP server name (type=mcp)
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                               // function/tool name on the runtime
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                                 // endpoint (type=http|openapi)
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`                           // HTTP method (type=http|openapi)
	Package       string                 `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`                         // package path (type=function)
	EntryPoint    string                 `protobuf:"bytes,7,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"` // entry symbol (type=function)
	Headers       map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Config        string                 `protobuf:"bytes,9,opt,name=config,proto3" json:"config,omitempty"`                                     // arbitrary JSON (string)
	CredentialRef string                 `protobuf:"bytes,10,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"` // secret:// ref for outbound auth
	Description   string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRuntimeDefinition) Reset() {
	*x = ToolRuntimeDefinition{}
	mi := &file_tool_v1_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRuntimeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRuntimeDefinition) ProtoMessage() {}

func (x *ToolRuntimeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRuntimeDefinition.ProtoReflect.Descriptor instead.
func (*ToolRuntimeDefinition) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{3}
}

func (x *ToolRuntimeDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ToolRuntimeDefinition) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetCredentialRef() string {
	if x != nil {
		return x.CredentialRef
	}
	return ""
}

func (x *ToolRuntimeDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ToolExecutionDefinition describes where and how the tool executes, plus the
// sandboxing policy (filesystem/network/resources/capabilities). placement
// determines the governance path: "runtime" tools go through the Runtime MCP
// server (authz + credential托管); "sandbox" tools execute locally in the
// agent pod (no privileged access).
type ToolExecutionDefinition struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Placement  string                 `protobuf:"bytes,1,opt,name=placement,proto3" json:"placement,omitempty"` // sandbox | runtime | remote | hub
	Runner     string                 `protobuf:"bytes,2,opt,name=runner,proto3" json:"runner,omitempty"`       // builtin | mcp | stdio | http | container | wasm | python | binary
	Image      string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Command    string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args       []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDir string                 `protobuf:"bytes,6,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Filesystem string                 `protobuf:"bytes,7,opt,name=filesystem,proto3" json:"filesystem,omitempty"` // none | readonly | workspace
	Network    string                 `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`       // none | restricted | egress
	Mounts     []*ToolMount           `protobuf:"bytes,9,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Env        map[string]string      `protobuf:"bytes,10,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SecretRefs []string               `protobuf:"bytes,11,rep,name=secret_refs,json=secretRefs,proto3" json:"secret_refs,omitempty"`
	AllowHosts []string               `protobuf:"bytes,12,rep,name=allow_hosts,json=allowHosts,proto3" json:"allow_hosts,omitempty"`
	DenyHosts  []string               `protobuf:"bytes,13,rep,name=deny_hosts,json=denyHosts,proto3" json:"deny_hosts,omitempty"`
	Resources  *ToolResources         `protobuf:"bytes,14,opt,name=resources,proto3" json:"resources,omitempty"`
	// capabilities map this tool to SpiceDB permissions on its target resource
	// (e.g. ["skill.view"] for git.pull). The Runtime uses these to run the
	// Tool-level authz gate (agent-identity-delegation-design §3.1).
	Capabilities  []string `protobuf:"bytes,15,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionDefinition) Reset() {
	*x = ToolExecutionDefinition{}
	mi := &file_tool_v1_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionDefinition) ProtoMessage() {}

func (x *ToolExecutionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionDefinition.ProtoReflect.Descriptor instead.
func (*ToolExecutionDefinition) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{4}
}

func (x *ToolExecutionDefinition) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

func (x *ToolExecutionDefinition) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *ToolExecutionDefinition) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ToolExecutionDefinition) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ToolExecutionDefinition) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ToolExecutionDefinition) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ToolExecutionDefinition) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *ToolExecutionDefinition) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ToolExecutionDefinition) GetMounts() []*ToolMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ToolExecutionDefinition) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ToolExecutionDefinition) GetSecretRefs() []string {
	if x != nil {
		return x.SecretRefs
	}
	return nil
}

func (x *ToolExecutionDefinition) GetAllowHosts() []string {
	if x != nil {
		return x.AllowHosts
	}
	return nil
}

func (x *ToolExecutionDefinition) GetDenyHosts() []string {
	if x != nil {
		return x.DenyHosts
	}
	return nil
}

func (x *ToolExecutionDefinition) GetResources() *ToolResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ToolExecutionDefinition) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ToolMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	MountPath     string                 `protobuf:"bytes,3,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"` // ro | rw
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolMount) Reset() {
	*x = ToolMount{}
	mi := &file_tool_v1_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolMount) ProtoMessage() {}

func (x *ToolMount) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolMount.ProtoReflect.Descriptor instead.
func (*ToolMount) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{5}
}

func (x *ToolMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolMount) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ToolMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *ToolMount) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ToolResources struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cpu            string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory         string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	TimeoutMillis  int32                  `protobuf:"varint,3,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	MaxOutputBytes int32                  `protobuf:"varint,4,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolResources) Reset() {
	*x = ToolResources{}
	mi := &file_tool_v1_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResources) ProtoMessage() {}

func (x *ToolResources) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResources.ProtoReflect.Descriptor instead.
func (*ToolResources) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{6}
}

func (x *ToolResources) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ToolResources) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ToolResources) GetTimeoutMillis() int32 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *ToolResources) GetMaxOutputBytes() int32 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

type ToolRetryPolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts       int32                  `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	BackoffMillis     int32                  `protobuf:"varint,2,opt,name=backoff_millis,json=backoffMillis,proto3" json:"backoff_millis,omitempty"`
	RetryOnErrorCodes []string               `protobuf:"bytes,3,rep,name=retry_on_error_codes,json=retryOnErrorCodes,proto3" json:"retry_on_error_codes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolRetryPolicy) Reset() {
	*x = ToolRetryPolicy{}
	mi := &file_tool_v1_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRetryPolicy) ProtoMessage() {}

func (x *ToolRetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRetryPolicy.ProtoReflect.Descriptor instead.
func (*ToolRetryPolicy) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{7}
}

func (x *ToolRetryPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *ToolRetryPolicy) GetBackoffMillis() int32 {
	if x != nil {
		return x.BackoffMillis
	}
	return 0
}

func (x *ToolRetryPolicy) GetRetryOnErrorCodes() []string {
	if x != nil {
		return x.RetryOnErrorCodes
	}
	return nil
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`                                // filter by scope
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                              // filter by status
	RuntimeType   string                 `protobuf:"bytes,6,opt,name=runtime_type,json=runtimeType,proto3" json:"runtime_type,omitempty"` // filter by runtime.type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{8}
}

func (x *ListToolsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListToolsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListToolsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListToolsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListToolsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListToolsRequest) GetRuntimeType() string {
	if x != nil {
		return x.RuntimeType
	}
	return ""
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_tool_v1_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{9}
}

func (x *ListToolsResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ListToolsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // optional; defaults to latest_version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolRequest) Reset() {
	*x = GetToolRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolRequest) ProtoMessage() {}

func (x *GetToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolRequest.ProtoReflect.Descriptor instead.
func (*GetToolRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{10}
}

func (x *GetToolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetToolRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          *Tool                  `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolResponse) Reset() {
	*x = GetToolResponse{}
	mi := &file_tool_v1_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolResponse) ProtoMessage() {}

func (x *GetToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolResponse.ProtoReflect.Descriptor instead.
func (*GetToolResponse) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{11}
}

func (x *GetToolResponse) GetTool() *Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

type CreateToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"` // initial version label
	CommitMsg     string                 `protobuf:"bytes,8,opt,name=commit_msg,json=commitMsg,proto3" json:"commit_msg,omitempty"`
	Definition    *ToolDefinition        `protobuf:"bytes,9,opt,name=definition,proto3" json:"definition,omitempty"`
	OrgId         string                 `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,11,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToolRequest) Reset() {
	*x = CreateToolRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolRequest) ProtoMessage() {}

func (x *CreateToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolRequest.ProtoReflect.Descriptor instead.
func (*CreateToolRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{12}
}

func (x *CreateToolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateToolRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateToolRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateToolRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateToolRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreateToolRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateToolRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateToolRequest) GetCommitMsg() string {
	if x != nil {
		return x.CommitMsg
	}
	return ""
}

func (x *CreateToolRequest) GetDefinition() *ToolDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *CreateToolRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateToolRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CreateToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          *Tool                  `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToolResponse) Reset() {
	*x = CreateToolResponse{}
	mi := &file_tool_v1_tool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolResponse) ProtoMessage() {}

func (x *CreateToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolResponse.ProtoReflect.Descriptor instead.
func (*CreateToolResponse) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{13}
}

func (x *CreateToolResponse) GetTool() *Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

type UpdateToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"` // new version label for this update
	CommitMsg     string                 `protobuf:"bytes,8,opt,name=commit_msg,json=commitMsg,proto3" json:"commit_msg,omitempty"`
	Definition    *ToolDefinition        `protobuf:"bytes,9,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateToolRequest) Reset() {
	*x = UpdateToolRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToolRequest) ProtoMessage() {}

func (x *UpdateToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToolRequest.ProtoReflect.Descriptor instead.
func (*UpdateToolRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateToolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateToolRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateToolRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateToolRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateToolRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *UpdateToolRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UpdateToolRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateToolRequest) GetCommitMsg() string {
	if x != nil {
		return x.CommitMsg
	}
	return ""
}

func (x *UpdateToolRequest) GetDefinition() *ToolDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type UpdateToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          *Tool                  `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateToolResponse) Reset() {
	*x = UpdateToolResponse{}
	mi := &file_tool_v1_tool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToolResponse) ProtoMessage() {}

func (x *UpdateToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToolResponse.ProtoReflect.Descriptor instead.
func (*UpdateToolResponse) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateToolResponse) GetTool() *Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

type DeleteToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteToolRequest) Reset() {
	*x = DeleteToolRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteToolRequest) ProtoMessage() {}

func (x *DeleteToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteToolRequest.ProtoReflect.Descriptor instead.
func (*DeleteToolRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteToolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          *Tool                  `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteToolResponse) Reset() {
	*x = DeleteToolResponse{}
	mi := &file_tool_v1_tool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteToolResponse) ProtoMessage() {}

func (x *DeleteToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteToolResponse.ProtoReflect.Descriptor instead.
func (*DeleteToolResponse) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteToolResponse) GetTool() *Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

type ResolveToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuntimeId     string                 `protobuf:"bytes,2,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveToolRequest) Reset() {
	*x = ResolveToolRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveToolRequest) ProtoMessage() {}

func (x *ResolveToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveToolRequest.ProtoReflect.Descriptor instead.
func (*ResolveToolRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{18}
}

func (x *ResolveToolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveToolRequest) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ResolveToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResolveToolRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolveToolRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ResolveToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	RuntimeId     string                 `protobuf:"bytes,2,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Tool          *ToolVersionRecord     `protobuf:"bytes,5,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveToolResponse) Reset() {
	*x = ResolveToolResponse{}
	mi := &file_tool_v1_tool_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveToolResponse) ProtoMessage() {}

func (x *ResolveToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveToolResponse.ProtoReflect.Descriptor instead.
func (*ResolveToolResponse) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{19}
}

func (x *ResolveToolResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ResolveToolResponse) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ResolveToolResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResolveToolResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ResolveToolResponse) GetTool() *ToolVersionRecord {
	if x != nil {
		return x.Tool
	}
	return nil
}

type ListToolFailuresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolFailuresRequest) Reset() {
	*x = ListToolFailuresRequest{}
	mi := &file_tool_v1_tool_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolFailuresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolFailuresRequest) ProtoMessage() {}

func (x *ListToolFailuresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolFailuresRequest.ProtoReflect.Descriptor instead.
func (*ListToolFailuresRequest) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{20}
}

func (x *ListToolFailuresRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListToolFailuresRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListToolFailuresRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ToolFailureRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToolId        string                 `protobuf:"bytes,2,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolVersion   string                 `protobuf:"bytes,3,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RuntimeId     string                 `protobuf:"bytes,5,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,9,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolFailureRecord) Reset() {
	*x = ToolFailureRecord{}
	mi := &file_tool_v1_tool_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFailureRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFailureRecord) ProtoMessage() {}

func (x *ToolFailureRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFailureRecord.ProtoReflect.Descriptor instead.
func (*ToolFailureRecord) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{21}
}

func (x *ToolFailureRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolFailureRecord) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolFailureRecord) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *ToolFailureRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ToolFailureRecord) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ToolFailureRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ToolFailureRecord) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ToolFailureRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ToolFailureRecord) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ToolFailureRecord) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ToolFailureRecord) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type ListToolFailuresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failures      []*ToolFailureRecord   `protobuf:"bytes,1,rep,name=failures,proto3" json:"failures,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolFailuresResponse) Reset() {
	*x = ListToolFailuresResponse{}
	mi := &file_tool_v1_tool_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolFailuresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolFailuresResponse) ProtoMessage() {}

func (x *ListToolFailuresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_v1_tool_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolFailuresResponse.ProtoReflect.Descriptor instead.
func (*ListToolFailuresResponse) Descriptor() ([]byte, []int) {
	return file_tool_v1_tool_proto_rawDescGZIP(), []int{22}
}

func (x *ListToolFailuresResponse) GetFailures() []*ToolFailureRecord {
	if x != nil {
		return x.Failures
	}
	return nil
}

func (x *ListToolFailuresResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_tool_v1_tool_proto protoreflect.FileDescriptor

const file_tool_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x12tool/v1/tool.proto\x12\atool.v1\x1a\x1faisphere/access/v1/access.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x04\n" +
	"\x04Tool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x121\n" +
	"\x06labels\x18\x06 \x03(\v2\x19.tool.v1.Tool.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06object\x18\a \x01(\tR\x06object\x12#\n" +
	"\rowner_subject\x18\b \x01(\tR\fownerSubject\x12%\n" +
	"\x0elatest_version\x18\t \x01(\tR\rlatestVersion\x127\n" +
	"\bversions\x18\n" +
	" \x03(\v2\x1b.tool.v1.Tool.VersionsEntryR\bversions\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aW\n" +
	"\rVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.tool.v1.ToolVersionRecordR\x05value:\x028\x01\"\x8e\x02\n" +
	"\x11ToolVersionRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"commit_msg\x18\x05 \x01(\tR\tcommitMsg\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x127\n" +
	"\n" +
	"definition\x18\a \x01(\v2\x17.tool.v1.ToolDefinitionR\n" +
	"definition\"\xc5\x02\n" +
	"\x0eToolDefinition\x128\n" +
	"\aruntime\x18\x01 \x01(\v2\x1e.tool.v1.ToolRuntimeDefinitionR\aruntime\x12>\n" +
	"\texecution\x18\x02 \x01(\v2 .tool.v1.ToolExecutionDefinitionR\texecution\x12!\n" +
	"\finput_schema\x18\x03 \x01(\tR\vinputSchema\x12#\n" +
	"\routput_schema\x18\x04 \x01(\tR\foutputSchema\x12%\n" +
	"\x0etimeout_millis\x18\x05 \x01(\x05R\rtimeoutMillis\x12.\n" +
	"\x05retry\x18\x06 \x01(\v2\x18.tool.v1.ToolRetryPolicyR\x05retry\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"\xa0\x03\n" +
	"\x15ToolRuntimeDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x18\n" +
	"\apackage\x18\x06 \x01(\tR\apackage\x12\x1f\n" +
	"\ventry_point\x18\a \x01(\tR\n" +
	"entryPoint\x12E\n" +
	"\aheaders\x18\b \x03(\v2+.tool.v1.ToolRuntimeDefinition.HeadersEntryR\aheaders\x12\x16\n" +
	"\x06config\x18\t \x01(\tR\x06config\x12%\n" +
	"\x0ecredential_ref\x18\n" +
	" \x01(\tR\rcredentialRef\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x04\n" +
	"\x17ToolExecutionDefinition\x12\x1c\n" +
	"\tplacement\x18\x01 \x01(\tR\tplacement\x12\x16\n" +
	"\x06runner\x18\x02 \x01(\tR\x06runner\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x06 \x01(\tR\n" +
	"workingDir\x12\x1e\n" +
	"\n" +
	"filesystem\x18\a \x01(\tR\n" +
	"filesystem\x12\x18\n" +
	"\anetwork\x18\b \x01(\tR\anetwork\x12*\n" +
	"\x06mounts\x18\t \x03(\v2\x12.tool.v1.ToolMountR\x06mounts\x12;\n" +
	"\x03env\x18\n" +
	" \x03(\v2).tool.v1.ToolExecutionDefinition.EnvEntryR\x03env\x12\x1f\n" +
	"\vsecret_refs\x18\v \x03(\tR\n" +
	"secretRefs\x12\x1f\n" +
	"\vallow_hosts\x18\f \x03(\tR\n" +
	"allowHosts\x12\x1d\n" +
	"\n" +
	"deny_hosts\x18\r \x03(\tR\tdenyHosts\x124\n" +
	"\tresources\x18\x0e \x01(\v2\x16.tool.v1.ToolResourcesR\tresources\x12\"\n" +
	"\fcapabilities\x18\x0f \x03(\tR\fcapabilities\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\tToolMount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x03 \x01(\tR\tmountPath\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\x8a\x01\n" +
	"\rToolResources\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x12%\n" +
	"\x0etimeout_millis\x18\x03 \x01(\x05R\rtimeoutMillis\x12(\n" +
	"\x10max_output_bytes\x18\x04 \x01(\x05R\x0emaxOutputBytes\"\x8c\x01\n" +
	"\x0fToolRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x12%\n" +
	"\x0ebackoff_millis\x18\x02 \x01(\x05R\rbackoffMillis\x12/\n" +
	"\x14retry_on_error_codes\x18\x03 \x03(\tR\x11retryOnErrorCodes\"\xb5\x01\n" +
	"\x10ListToolsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fruntime_type\x18\x06 \x01(\tR\vruntimeType\"`\n" +
	"\x11ListToolsResponse\x12#\n" +
	"\x05tools\x18\x01 \x03(\v2\r.tool.v1.ToolR\x05tools\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"?\n" +
	"\x0eGetToolRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"4\n" +
	"\x0fGetToolResponse\x12!\n" +
	"\x04tool\x18\x01 \x01(\v2\r.tool.v1.ToolR\x04tool\"\xbe\x03\n" +
	"\x11CreateToolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12>\n" +
	"\x06labels\x18\x06 \x03(\v2&.tool.v1.CreateToolRequest.LabelsEntryR\x06labels\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"commit_msg\x18\b \x01(\tR\tcommitMsg\x12<\n" +
	"\n" +
	"definition\x18\t \x01(\v2\x17.tool.v1.ToolDefinitionB\x03\xe0A\x02R\n" +
	"definition\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"project_id\x18\v \x01(\tR\tprojectId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x12CreateToolResponse\x12!\n" +
	"\x04tool\x18\x01 \x01(\v2\r.tool.v1.ToolR\x04tool\"\x8d\x03\n" +
	"\x11UpdateToolRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12>\n" +
	"\x06labels\x18\x06 \x03(\v2&.tool.v1.UpdateToolRequest.LabelsEntryR\x06labels\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"commit_msg\x18\b \x01(\tR\tcommitMsg\x12<\n" +
	"\n" +
	"definition\x18\t \x01(\v2\x17.tool.v1.ToolDefinitionB\x03\xe0A\x02R\n" +
	"definition\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x12UpdateToolResponse\x12!\n" +
	"\x04tool\x18\x01 \x01(\v2\r.tool.v1.ToolR\x04tool\"(\n" +
	"\x11DeleteToolRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"7\n" +
	"\x12DeleteToolResponse\x12!\n" +
	"\x04tool\x18\x01 \x01(\v2\r.tool.v1.ToolR\x04tool\"\x97\x01\n" +
	"\x12ResolveToolRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x02 \x01(\tR\truntimeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\"\xe3\x01\n" +
	"\x13ResolveToolResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x02 \x01(\tR\truntimeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12=\n" +
	"\fgenerated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12.\n" +
	"\x04tool\x18\x05 \x01(\v2\x1a.tool.v1.ToolVersionRecordR\x04tool\"j\n" +
	"\x17ListToolFailuresRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xeb\x02\n" +
	"\x11ToolFailureRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atool_id\x18\x02 \x01(\tR\x06toolId\x12!\n" +
	"\ftool_version\x18\x03 \x01(\tR\vtoolVersion\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x05 \x01(\tR\truntimeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"error_code\x18\t \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"z\n" +
	"\x18ListToolFailuresResponse\x126\n" +
	"\bfailures\x18\x01 \x03(\v2\x1a.tool.v1.ToolFailureRecordR\bfailures\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xec\t\n" +
	"\vToolService\x12\xc0\x01\n" +
	"\tListTools\x12\x19.tool.v1.ListToolsRequest\x1a\x1a.tool.v1.ListToolsResponse\"|\x92\xf4\x18g\b\x02\x1a\x16\b\x01\x12\rhub.tool.list\x1a\x03low2<handler batch-checks view permission for every concrete tool:\r\"\vhub-service\x82\xd3\xe4\x93\x02\v\x12\t/v1/tools\x12\x99\x01\n" +
	"\aGetTool\x12\x17.tool.v1.GetToolRequest\x1a\x18.tool.v1.GetToolResponse\"[\x92\xf4\x18;\b\x03\x12 \n" +
	"\x04view\x12\ttool:{id}\x1a\vhub-service \x01\x1a\x15\b\x01\x12\fhub.tool.get\x1a\x03low\x82\xd3\xe4\x93\x02\x16b\x04tool\x12\x0e/v1/tools/{id}\x12\xb0\x01\n" +
	"\n" +
	"CreateTool\x12\x1a.tool.v1.CreateToolRequest\x1a\x1b.tool.v1.CreateToolResponse\"i\x92\xf4\x18K\b\x03\x12*\n" +
	"\x04edit\x12\x13tool_space:{org_id}\x1a\vhub-service \x01\x1a\x1b\b\x01\x12\x0fhub.tool.create\x1a\x06medium\x82\xd3\xe4\x93\x02\x14:\x01*b\x04tool\"\t/v1/tools\x12\xab\x01\n" +
	"\n" +
	"UpdateTool\x12\x1a.tool.v1.UpdateToolRequest\x1a\x1b.tool.v1.UpdateToolResponse\"d\x92\xf4\x18A\b\x03\x12 \n" +
	"\x04edit\x12\ttool:{id}\x1a\vhub-service \x01\x1a\x1b\b\x01\x12\x0fhub.tool.update\x1a\x06medium\x82\xd3\xe4\x93\x02\x19:\x01*b\x04tool\x1a\x0e/v1/tools/{id}\x12\xa2\x01\n" +
	"\n" +
	"DeleteTool\x12\x1a.tool.v1.DeleteToolRequest\x1a\x1b.tool.v1.DeleteToolResponse\"[\x92\xf4\x18A\b\x03\x12\"\n" +
	"\x06manage\x12\ttool:{id}\x1a\vhub-service \x01\x1a\x19\b\x01\x12\x0fhub.tool.delete\x1a\x04high\x82\xd3\xe4\x93\x02\x10*\x0e/v1/tools/{id}\x12\xb1\x01\n" +
	"\vResolveTool\x12\x1b.tool.v1.ResolveToolRequest\x1a\x1c.tool.v1.ResolveToolResponse\"g\x92\xf4\x18B\b\x03\x12#\n" +
	"\aexecute\x12\ttool:{id}\x1a\vhub-service \x01\x1a\x19\b\x01\x12\x10hub.tool.resolve\x1a\x03low\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/tools/{id}:resolve\x12\xc3\x01\n" +
	"\x10ListToolFailures\x12 .tool.v1.ListToolFailuresRequest\x1a!.tool.v1.ListToolFailuresResponse\"j\x92\xf4\x18G\b\x03\x12\"\n" +
	"\x06manage\x12\ttool:{id}\x1a\vhub-service \x01\x1a\x1f\b\x01\x12\x16hub.tool.failures.list\x1a\x03low\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/tools/{id}/failuresB7Z5github.com/aisphereio/aisphere-hub/api/tool/v1;toolv1b\x06proto3"

var (
	file_tool_v1_tool_proto_rawDescOnce sync.Once
	file_tool_v1_tool_proto_rawDescData []byte
)

func file_tool_v1_tool_proto_rawDescGZIP() []byte {
	file_tool_v1_tool_proto_rawDescOnce.Do(func() {
		file_tool_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tool_v1_tool_proto_rawDesc), len(file_tool_v1_tool_proto_rawDesc)))
	})
	return file_tool_v1_tool_proto_rawDescData
}

var file_tool_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_tool_v1_tool_proto_goTypes = []any{
	(*Tool)(nil),                     // 0: tool.v1.Tool
	(*ToolVersionRecord)(nil),        // 1: tool.v1.ToolVersionRecord
	(*ToolDefinition)(nil),           // 2: tool.v1.ToolDefinition
	(*ToolRuntimeDefinition)(nil),    // 3: tool.v1.ToolRuntimeDefinition
	(*ToolExecutionDefinition)(nil),  // 4: tool.v1.ToolExecutionDefinition
	(*ToolMount)(nil),                // 5: tool.v1.ToolMount
	(*ToolResources)(nil),            // 6: tool.v1.ToolResources
	(*ToolRetryPolicy)(nil),          // 7: tool.v1.ToolRetryPolicy
	(*ListToolsRequest)(nil),         // 8: tool.v1.ListToolsRequest
	(*ListToolsResponse)(nil),        // 9: tool.v1.ListToolsResponse
	(*GetToolRequest)(nil),           // 10: tool.v1.GetToolRequest
	(*GetToolResponse)(nil),          // 11: tool.v1.GetToolResponse
	(*CreateToolRequest)(nil),        // 12: tool.v1.CreateToolRequest
	(*CreateToolResponse)(nil),       // 13: tool.v1.CreateToolResponse
	(*UpdateToolRequest)(nil),        // 14: tool.v1.UpdateToolRequest
	(*UpdateToolResponse)(nil),       // 15: tool.v1.UpdateToolResponse
	(*DeleteToolRequest)(nil),        // 16: tool.v1.DeleteToolRequest
	(*DeleteToolResponse)(nil),       // 17: tool.v1.DeleteToolResponse
	(*ResolveToolRequest)(nil),       // 18: tool.v1.ResolveToolRequest
	(*ResolveToolResponse)(nil),      // 19: tool.v1.ResolveToolResponse
	(*ListToolFailuresRequest)(nil),  // 20: tool.v1.ListToolFailuresRequest
	(*ToolFailureRecord)(nil),        // 21: tool.v1.ToolFailureRecord
	(*ListToolFailuresResponse)(nil), // 22: tool.v1.ListToolFailuresResponse
	nil,                              // 23: tool.v1.Tool.LabelsEntry
	nil,                              // 24: tool.v1.Tool.VersionsEntry
	nil,                              // 25: tool.v1.ToolRuntimeDefinition.HeadersEntry
	nil,                              // 26: tool.v1.ToolExecutionDefinition.EnvEntry
	nil,                              // 27: tool.v1.CreateToolRequest.LabelsEntry
	nil,                              // 28: tool.v1.UpdateToolRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil),    // 29: google.protobuf.Timestamp
}
var file_tool_v1_tool_proto_depIdxs = []int32{
	23, // 0: tool.v1.Tool.labels:type_name -> tool.v1.Tool.LabelsEntry
	24, // 1: tool.v1.Tool.versions:type_name -> tool.v1.Tool.VersionsEntry
	29, // 2: tool.v1.Tool.create_time:type_name -> google.protobuf.Timestamp
	29, // 3: tool.v1.Tool.update_time:type_name -> google.protobuf.Timestamp
	29, // 4: tool.v1.ToolVersionRecord.create_time:type_name -> google.protobuf.Timestamp
	2,  // 5: tool.v1.ToolVersionRecord.definition:type_name -> tool.v1.ToolDefinition
	3,  // 6: tool.v1.ToolDefinition.runtime:type_name -> tool.v1.ToolRuntimeDefinition
	4,  // 7: tool.v1.ToolDefinition.execution:type_name -> tool.v1.ToolExecutionDefinition
	7,  // 8: tool.v1.ToolDefinition.retry:type_name -> tool.v1.ToolRetryPolicy
	25, // 9: tool.v1.ToolRuntimeDefinition.headers:type_name -> tool.v1.ToolRuntimeDefinition.HeadersEntry
	5,  // 10: tool.v1.ToolExecutionDefinition.mounts:type_name -> tool.v1.ToolMount
	26, // 11: tool.v1.ToolExecutionDefinition.env:type_name -> tool.v1.ToolExecutionDefinition.EnvEntry
	6,  // 12: tool.v1.ToolExecutionDefinition.resources:type_name -> tool.v1.ToolResources
	0,  // 13: tool.v1.ListToolsResponse.tools:type_name -> tool.v1.Tool
	0,  // 14: tool.v1.GetToolResponse.tool:type_name -> tool.v1.Tool
	27, // 15: tool.v1.CreateToolRequest.labels:type_name -> tool.v1.CreateToolRequest.LabelsEntry
	2,  // 16: tool.v1.CreateToolRequest.definition:type_name -> tool.v1.ToolDefinition
	0,  // 17: tool.v1.CreateToolResponse.tool:type_name -> tool.v1.Tool
	28, // 18: tool.v1.UpdateToolRequest.labels:type_name -> tool.v1.UpdateToolRequest.LabelsEntry
	2,  // 19: tool.v1.UpdateToolRequest.definition:type_name -> tool.v1.ToolDefinition
	0,  // 20: tool.v1.UpdateToolResponse.tool:type_name -> tool.v1.Tool
	0,  // 21: tool.v1.DeleteToolResponse.tool:type_name -> tool.v1.Tool
	29, // 22: tool.v1.ResolveToolResponse.generated_at:type_name -> google.protobuf.Timestamp
	1,  // 23: tool.v1.ResolveToolResponse.tool:type_name -> tool.v1.ToolVersionRecord
	29, // 24: tool.v1.ToolFailureRecord.create_time:type_name -> google.protobuf.Timestamp
	21, // 25: tool.v1.ListToolFailuresResponse.failures:type_name -> tool.v1.ToolFailureRecord
	1,  // 26: tool.v1.Tool.VersionsEntry.value:type_name -> tool.v1.ToolVersionRecord
	8,  // 27: tool.v1.ToolService.ListTools:input_type -> tool.v1.ListToolsRequest
	10, // 28: tool.v1.ToolService.GetTool:input_type -> tool.v1.GetToolRequest
	12, // 29: tool.v1.ToolService.CreateTool:input_type -> tool.v1.CreateToolRequest
	14, // 30: tool.v1.ToolService.UpdateTool:input_type -> tool.v1.UpdateToolRequest
	16, // 31: tool.v1.ToolService.DeleteTool:input_type -> tool.v1.DeleteToolRequest
	18, // 32: tool.v1.ToolService.ResolveTool:input_type -> tool.v1.ResolveToolRequest
	20, // 33: tool.v1.ToolService.ListToolFailures:input_type -> tool.v1.ListToolFailuresRequest
	9,  // 34: tool.v1.ToolService.ListTools:output_type -> tool.v1.ListToolsResponse
	11, // 35: tool.v1.ToolService.GetTool:output_type -> tool.v1.GetToolResponse
	13, // 36: tool.v1.ToolService.CreateTool:output_type -> tool.v1.CreateToolResponse
	15, // 37: tool.v1.ToolService.UpdateTool:output_type -> tool.v1.UpdateToolResponse
	17, // 38: tool.v1.ToolService.DeleteTool:output_type -> tool.v1.DeleteToolResponse
	19, // 39: tool.v1.ToolService.ResolveTool:output_type -> tool.v1.ResolveToolResponse
	22, // 40: tool.v1.ToolService.ListToolFailures:output_type -> tool.v1.ListToolFailuresResponse
	34, // [34:41] is the sub-list for method output_type
	27, // [27:34] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_tool_v1_tool_proto_init() }
func file_tool_v1_tool_proto_init() {
	if File_tool_v1_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tool_v1_tool_proto_rawDesc), len(file_tool_v1_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tool_v1_tool_proto_goTypes,
		DependencyIndexes: file_tool_v1_tool_proto_depIdxs,
		MessageInfos:      file_tool_v1_tool_proto_msgTypes,
	}.Build()
	File_tool_v1_tool_proto = out.File
	file_tool_v1_tool_proto_goTypes = nil
	file_tool_v1_tool_proto_depIdxs = nil
}
