// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.19
// source: tool/v1/tool.proto

package toolv1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// ToolServiceKernelModule returns the generated Kernel service module for tool.v1.ToolService.
func ToolServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "tool-service",
		GatewayManifest:     ToolServiceGatewayManifest(),
		RequestInfoResolver: ToolServiceKernelRequestInfoResolver,
		AccessResolver:      ToolServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(ToolServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for tool.v1.ToolService must implement ToolServiceServer, got %T", impl)
			}
			RegisterToolServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(ToolServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for tool.v1.ToolService must implement ToolServiceHTTPServer, got %T", impl)
			}
			RegisterToolServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(ToolServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for tool.v1.ToolService must implement ToolServiceClient, got %T", client)
			}
			return RegisterToolServiceGatewayInvokers(r, typed)
		},
	}
}

var ToolServiceKernelAuthzRules = authz.Rules{
	"/tool.v1.ToolService/GetTool": {
		Service:    "tool.v1.ToolService",
		Method:     "GetTool",
		FullMethod: "/tool.v1.ToolService/GetTool",
		Action:     "view",
		Resource:   "tool:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.tool.get",
		AuditRisk:  "low",
	},
	"/tool.v1.ToolService/CreateTool": {
		Service:    "tool.v1.ToolService",
		Method:     "CreateTool",
		FullMethod: "/tool.v1.ToolService/CreateTool",
		Action:     "edit",
		Resource:   "tool_space:{org_id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.tool.create",
		AuditRisk:  "medium",
	},
	"/tool.v1.ToolService/UpdateTool": {
		Service:    "tool.v1.ToolService",
		Method:     "UpdateTool",
		FullMethod: "/tool.v1.ToolService/UpdateTool",
		Action:     "edit",
		Resource:   "tool:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.tool.update",
		AuditRisk:  "medium",
	},
	"/tool.v1.ToolService/DeleteTool": {
		Service:    "tool.v1.ToolService",
		Method:     "DeleteTool",
		FullMethod: "/tool.v1.ToolService/DeleteTool",
		Action:     "manage",
		Resource:   "tool:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.tool.delete",
		AuditRisk:  "high",
	},
	"/tool.v1.ToolService/ResolveTool": {
		Service:    "tool.v1.ToolService",
		Method:     "ResolveTool",
		FullMethod: "/tool.v1.ToolService/ResolveTool",
		Action:     "execute",
		Resource:   "tool:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.tool.resolve",
		AuditRisk:  "low",
	},
	"/tool.v1.ToolService/ListToolFailures": {
		Service:    "tool.v1.ToolService",
		Method:     "ListToolFailures",
		FullMethod: "/tool.v1.ToolService/ListToolFailures",
		Action:     "manage",
		Resource:   "tool:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.tool.failures.list",
		AuditRisk:  "low",
	},
}

// ToolServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func ToolServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _ToolServiceKernelNormalizeOperation(operation) {
	case "/tool.v1.ToolService/ListTools":
		info := requestx.Info{
			Service:   "tool.v1.ToolService",
			Method:    "ListTools",
			Operation: "/tool.v1.ToolService/ListTools",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "hub.tool.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/tool.v1.ToolService/GetTool":
		info := requestx.Info{
			Service:       "tool.v1.ToolService",
			Method:        "GetTool",
			Operation:     "/tool.v1.ToolService/GetTool",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view",
			Resource:      "tool:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.tool.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/tool.v1.ToolService/CreateTool":
		info := requestx.Info{
			Service:       "tool.v1.ToolService",
			Method:        "CreateTool",
			Operation:     "/tool.v1.ToolService/CreateTool",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "tool_space:{org_id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.tool.create"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/tool.v1.ToolService/UpdateTool":
		info := requestx.Info{
			Service:       "tool.v1.ToolService",
			Method:        "UpdateTool",
			Operation:     "/tool.v1.ToolService/UpdateTool",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "tool:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.tool.update"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/tool.v1.ToolService/DeleteTool":
		info := requestx.Info{
			Service:       "tool.v1.ToolService",
			Method:        "DeleteTool",
			Operation:     "/tool.v1.ToolService/DeleteTool",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "tool:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.tool.delete"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/tool.v1.ToolService/ResolveTool":
		info := requestx.Info{
			Service:       "tool.v1.ToolService",
			Method:        "ResolveTool",
			Operation:     "/tool.v1.ToolService/ResolveTool",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "execute",
			Resource:      "tool:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.tool.resolve"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/tool.v1.ToolService/ListToolFailures":
		info := requestx.Info{
			Service:       "tool.v1.ToolService",
			Method:        "ListToolFailures",
			Operation:     "/tool.v1.ToolService/ListToolFailures",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "tool:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.tool.failures.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// ToolServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func ToolServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := ToolServiceKernelAuthzRules[_ToolServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _ToolServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "ListTools", "tool.v1.ToolService/ListTools":
		return "/tool.v1.ToolService/ListTools"
	case "GetTool", "tool.v1.ToolService/GetTool":
		return "/tool.v1.ToolService/GetTool"
	case "CreateTool", "tool.v1.ToolService/CreateTool":
		return "/tool.v1.ToolService/CreateTool"
	case "UpdateTool", "tool.v1.ToolService/UpdateTool":
		return "/tool.v1.ToolService/UpdateTool"
	case "DeleteTool", "tool.v1.ToolService/DeleteTool":
		return "/tool.v1.ToolService/DeleteTool"
	case "ResolveTool", "tool.v1.ToolService/ResolveTool":
		return "/tool.v1.ToolService/ResolveTool"
	case "ListToolFailures", "tool.v1.ToolService/ListToolFailures":
		return "/tool.v1.ToolService/ListToolFailures"
	default:
		return operation
	}
}
