-- Kubernetes environment management control-plane tables.
-- Implements docs/ai/kubernetes-environment-management-design.md §8.
-- UUIDs are stored as VARCHAR(36) (Hub convention, GORM-compatible) and
-- generated by the Go layer via github.com/google/uuid. Status / lifecycle /
-- visibility values are stored uppercase to match the proto enums.

-- §8.1 k8s_clusters
CREATE TABLE IF NOT EXISTS k8s_clusters (
    id                  VARCHAR(36) NOT NULL,
    org_id              VARCHAR(128) NOT NULL,
    name                VARCHAR(128) NOT NULL,
    display_name        VARCHAR(256) NOT NULL DEFAULT '',
    description         TEXT NOT NULL DEFAULT '',
    server_url          TEXT NOT NULL,
    credential_ref      VARCHAR(36) NOT NULL,
    credential_revision BIGINT NOT NULL,
    distribution        VARCHAR(64) NOT NULL DEFAULT '',
    kubernetes_version  VARCHAR(64) NOT NULL DEFAULT '',
    cluster_uid         VARCHAR(128) NOT NULL DEFAULT '',
    status              VARCHAR(32) NOT NULL DEFAULT 'CREATING',
    health_message      TEXT NOT NULL DEFAULT '',
    labels_json         JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_probe_at       TIMESTAMPTZ,
    owner_type          VARCHAR(32) NOT NULL,
    owner_id            VARCHAR(128) NOT NULL,
    created_by_type     VARCHAR(32) NOT NULL,
    created_by          VARCHAR(128) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ,
    revision            BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_k8s_clusters PRIMARY KEY (id),
    CONSTRAINT chk_k8s_clusters_status
        CHECK (status IN ('CREATING','READY','PROBING','DEGRADED','DELETING','DELETED','FAILED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_k8s_clusters_org_name
    ON k8s_clusters(org_id, name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_k8s_clusters_uid
    ON k8s_clusters(cluster_uid) WHERE cluster_uid <> '' AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_k8s_clusters_org
    ON k8s_clusters(org_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_k8s_clusters_owner
    ON k8s_clusters(owner_type, owner_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_k8s_clusters_status
    ON k8s_clusters(status) WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_k8s_clusters_updated_at ON k8s_clusters;
CREATE TRIGGER trg_k8s_clusters_updated_at
BEFORE UPDATE ON k8s_clusters
FOR EACH ROW EXECUTE FUNCTION hub_set_updated_at();

-- §8.2 k8s_cluster_credentials (versioned AEAD, see §5.5).
-- ciphertext/nonce/key_version is the AEAD triple; credential_revision is the
-- credential version (bound into AAD), distinct from k8s_clusters.revision
-- (the resource optimistic-lock counter).
CREATE TABLE IF NOT EXISTS k8s_cluster_credentials (
    ref                 VARCHAR(36) NOT NULL,
    cluster_id          VARCHAR(36) NOT NULL,
    credential_revision BIGINT NOT NULL,
    ciphertext          BYTEA NOT NULL,
    nonce               BYTEA NOT NULL,
    key_version         VARCHAR(32) NOT NULL,
    credential_type     VARCHAR(32) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_k8s_cluster_credentials PRIMARY KEY (ref),
    CONSTRAINT fk_k8s_cluster_credentials_cluster
        FOREIGN KEY (cluster_id) REFERENCES k8s_clusters(id) ON DELETE CASCADE,
    CONSTRAINT uq_k8s_cluster_credentials_cluster_revision
        UNIQUE (cluster_id, credential_revision),
    CONSTRAINT chk_k8s_cluster_credentials_type
        CHECK (credential_type IN ('SERVICE_ACCOUNT','IN_CLUSTER','KUBECONFIG'))
);

CREATE INDEX IF NOT EXISTS idx_k8s_cluster_credentials_cluster
    ON k8s_cluster_credentials(cluster_id);
CREATE INDEX IF NOT EXISTS idx_k8s_cluster_credentials_key_version
    ON k8s_cluster_credentials(key_version);

DROP TRIGGER IF EXISTS trg_k8s_cluster_credentials_updated_at ON k8s_cluster_credentials;
CREATE TRIGGER trg_k8s_cluster_credentials_updated_at
BEFORE UPDATE ON k8s_cluster_credentials
FOR EACH ROW EXECUTE FUNCTION hub_set_updated_at();

-- §8.3 k8s_namespaces
-- cluster_id uses ON DELETE RESTRICT: Cluster deletion is a business-level
-- cascade (§5.7.5) that must drain Namespaces + credentials + SpiceDB tuples
-- before removing the Cluster row. A hard DB delete would orphan the remote
-- Namespace records and break the async cleanup ordering.
CREATE TABLE IF NOT EXISTS k8s_namespaces (
    id                       VARCHAR(36) NOT NULL,
    cluster_id               VARCHAR(36) NOT NULL,
    kube_name                VARCHAR(253) NOT NULL,
    display_name             VARCHAR(256) NOT NULL DEFAULT '',
    description              TEXT NOT NULL DEFAULT '',
    visibility               VARCHAR(32) NOT NULL DEFAULT 'PRIVATE',
    visibility_sync_status   VARCHAR(32) NOT NULL DEFAULT 'SYNCED',
    lifecycle                VARCHAR(32) NOT NULL DEFAULT 'CREATING',
    managed                  BOOLEAN NOT NULL DEFAULT TRUE,
    kubernetes_uid           VARCHAR(128) NOT NULL DEFAULT '',
    resource_version         VARCHAR(128) NOT NULL DEFAULT '',
    labels_json              JSONB NOT NULL DEFAULT '{}'::jsonb,
    annotations_json         JSONB NOT NULL DEFAULT '{}'::jsonb,
    owner_type               VARCHAR(32) NOT NULL,
    owner_id                 VARCHAR(128) NOT NULL,
    created_by_type          VARCHAR(32) NOT NULL,
    created_by               VARCHAR(128) NOT NULL,
    last_sync_at             TIMESTAMPTZ,
    last_error_code          VARCHAR(64) NOT NULL DEFAULT '',
    last_error_message       TEXT NOT NULL DEFAULT '',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at               TIMESTAMPTZ,
    revision                 BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_k8s_namespaces PRIMARY KEY (id),
    CONSTRAINT fk_k8s_namespaces_cluster
        FOREIGN KEY (cluster_id) REFERENCES k8s_clusters(id) ON DELETE RESTRICT,
    CONSTRAINT chk_k8s_namespaces_visibility
        CHECK (visibility IN ('PRIVATE','PUBLIC')),
    CONSTRAINT chk_k8s_namespaces_sync_status
        CHECK (visibility_sync_status IN ('SYNCED','PUBLISHING','REVOKING','SYNC_FAILED')),
    CONSTRAINT chk_k8s_namespaces_lifecycle
        CHECK (lifecycle IN ('CREATING','READY','TERMINATING','FAILED','DELETED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_k8s_namespaces_cluster_kube_name
    ON k8s_namespaces(cluster_id, kube_name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_k8s_namespaces_cluster_uid
    ON k8s_namespaces(cluster_id, kubernetes_uid) WHERE kubernetes_uid <> '' AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_k8s_namespaces_cluster_lifecycle
    ON k8s_namespaces(cluster_id, lifecycle) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_k8s_namespaces_owner
    ON k8s_namespaces(owner_type, owner_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_k8s_namespaces_sync_status
    ON k8s_namespaces(visibility_sync_status) WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_k8s_namespaces_updated_at ON k8s_namespaces;
CREATE TRIGGER trg_k8s_namespaces_updated_at
BEFORE UPDATE ON k8s_namespaces
FOR EACH ROW EXECUTE FUNCTION hub_set_updated_at();

-- §8.4 k8s_namespace_shares
-- subject_relation is NOT NULL DEFAULT '' (not nullable) so the UNIQUE
-- constraint enforces dedup even for direct user/service_account subjects
-- (PostgreSQL treats NULL as distinct, which would allow duplicate rows).
CREATE TABLE IF NOT EXISTS k8s_namespace_shares (
    id                 VARCHAR(36) NOT NULL,
    namespace_id       VARCHAR(36) NOT NULL,
    relation           VARCHAR(32) NOT NULL,
    subject_type       VARCHAR(32) NOT NULL,
    subject_id         VARCHAR(128) NOT NULL,
    subject_relation   VARCHAR(64) NOT NULL DEFAULT '',
    sync_status        VARCHAR(32) NOT NULL DEFAULT 'SYNCED',
    created_by_type    VARCHAR(32) NOT NULL,
    created_by         VARCHAR(128) NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_k8s_namespace_shares PRIMARY KEY (id),
    CONSTRAINT fk_k8s_namespace_shares_namespace
        FOREIGN KEY (namespace_id) REFERENCES k8s_namespaces(id) ON DELETE CASCADE,
    CONSTRAINT uq_k8s_namespace_shares_tuple
        UNIQUE (namespace_id, relation, subject_type, subject_id, subject_relation),
    CONSTRAINT chk_k8s_namespace_shares_relation
        CHECK (relation IN ('viewer','user','editor')),
    CONSTRAINT chk_k8s_namespace_shares_sync_status
        CHECK (sync_status IN ('SYNCED','PUBLISHING','REVOKING','SYNC_FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_k8s_namespace_shares_namespace
    ON k8s_namespace_shares(namespace_id);
CREATE INDEX IF NOT EXISTS idx_k8s_namespace_shares_subject
    ON k8s_namespace_shares(subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_k8s_namespace_shares_sync_status
    ON k8s_namespace_shares(sync_status);

DROP TRIGGER IF EXISTS trg_k8s_namespace_shares_updated_at ON k8s_namespace_shares;
CREATE TRIGGER trg_k8s_namespace_shares_updated_at
BEFORE UPDATE ON k8s_namespace_shares
FOR EACH ROW EXECUTE FUNCTION hub_set_updated_at();

-- §8.5 k8s_outbox
-- Drives reliable SpiceDB projection for visibility switches and delayed
-- credential_ref cleanup. Multiple Hub replicas claim rows safely via
-- SELECT ... FOR UPDATE SKIP LOCKED (see internal/data/outbox.go).
CREATE TABLE IF NOT EXISTS k8s_outbox (
    id              BIGSERIAL PRIMARY KEY,
    aggregate_type  VARCHAR(64) NOT NULL,
    aggregate_id    VARCHAR(128) NOT NULL,
    event_type      VARCHAR(64) NOT NULL,
    payload_json    JSONB NOT NULL DEFAULT '{}'::jsonb,
    status          VARCHAR(32) NOT NULL DEFAULT 'pending',
    retry_count     INTEGER NOT NULL DEFAULT 0,
    next_retry_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_k8s_outbox_status
        CHECK (status IN ('pending','in_progress','done','failed'))
);

CREATE INDEX IF NOT EXISTS idx_k8s_outbox_status_next_retry
    ON k8s_outbox(status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_k8s_outbox_aggregate
    ON k8s_outbox(aggregate_type, aggregate_id);

DROP TRIGGER IF EXISTS trg_k8s_outbox_updated_at ON k8s_outbox;
CREATE TRIGGER trg_k8s_outbox_updated_at
BEFORE UPDATE ON k8s_outbox
FOR EACH ROW EXECUTE FUNCTION hub_set_updated_at();

-- +goose StatementBegin
COMMENT ON TABLE k8s_clusters IS
    'AISphere control-plane record of a registered Kubernetes cluster (design §8.1).';
COMMENT ON COLUMN k8s_clusters.credential_ref IS
    'Foreign key into k8s_cluster_credentials.ref; the active credential revision.';
COMMENT ON COLUMN k8s_clusters.credential_revision IS
    'Credential version bound into the AEAD AAD; distinct from revision (resource CAS counter).';
COMMENT ON COLUMN k8s_clusters.revision IS
    'Resource optimistic-lock counter; UpdateCluster/RotateCredential/DeleteCluster CAS via WHERE revision = expected_revision.';
COMMENT ON COLUMN k8s_clusters.owner_type IS
    'Canonical SpiceDB subject type (user/service/service_account); matches the owner tuple.';
COMMENT ON COLUMN k8s_clusters.created_by IS
    'Original Principal subject_id (audit only); owner_id stores the canonical prefixed id.';
COMMENT ON TABLE k8s_cluster_credentials IS
    'Versioned AEAD credential store (design §5.5); no plaintext, no AAD persisted.';
COMMENT ON COLUMN k8s_cluster_credentials.ciphertext IS
    'AES-256-GCM ciphertext; AAD = cluster_id + ref + credential_revision (reconstructed by Store).';
COMMENT ON COLUMN k8s_cluster_credentials.key_version IS
    'Master key version; RotateKey re-encrypts rows from old version to new version.';
COMMENT ON TABLE k8s_namespaces IS
    'AISphere Namespace record (design §8.3); the remote Kubernetes Namespace is a separate resource.';
COMMENT ON COLUMN k8s_namespaces.visibility IS
    'Desired visibility (PRIVATE/PUBLIC); SpiceDB is the effective permission source, not this column.';
COMMENT ON COLUMN k8s_namespaces.visibility_sync_status IS
    'SpiceDB projection state (SYNCED/PUBLISHING/REVOKING/SYNC_FAILED); reconcile converges to SYNCED.';
COMMENT ON COLUMN k8s_namespaces.lifecycle IS
    'CREATING/READY/TERMINATING/FAILED/DELETED; TERMINATING awaits remote Namespace deletion.';
COMMENT ON TABLE k8s_namespace_shares IS
    'Control-plane fact for Namespace shares (design §8.4); used for display, audit, and drift repair.';
COMMENT ON TABLE k8s_outbox IS
    'Reliable event outbox for SpiceDB projection and delayed credential cleanup (design §8.5).';
-- +goose StatementEnd
