// Code generated by protoc-gen-go-gateway. DO NOT EDIT.
// versions:
// - protoc-gen-go-gateway v0.4.1
// source: audit/v1/audit.proto

package auditv1

import (
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
)

func AuditServiceGatewayManifest() gatewayx.Manifest {
	return gatewayx.Manifest{
		Service:   "audit-service",
		Namespace: "aisphere",
		Routes: []gatewayx.GatewayRoute{
			{
				ID:       "audit.query.audit.records",
				Method:   "GET",
				Path:     "/v1/audit/records",
				Upstream: gatewayx.UpstreamRef{Service: "audit-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/audit.v1.AuditService/QueryAuditRecords"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHENTICATED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
		},
	}
}

func AuditServiceGatewayBindQueryAuditRecords(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*QueryAuditRecordsRequest, error) {
	out := &QueryAuditRecordsRequest{}
	if v, ok := req.Body.(*QueryAuditRecordsRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(QueryAuditRecordsRequest); ok {
		out = &v
	}
	return out, nil
}

func RegisterAuditServiceGatewayInvokers(registry *gatewayx.InvokerRegistry, client AuditServiceClient) error {
	if err := registry.Register("/audit.v1.AuditService/QueryAuditRecords", gatewayx.GRPCUnaryInvoker(AuditServiceGatewayBindQueryAuditRecords, client.QueryAuditRecords)); err != nil {
		return err
	}
	return nil
}
