// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.19
// source: model/v1/model.proto

package modelv1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// ModelProfileServiceKernelModule returns the generated Kernel service module for model.v1.ModelProfileService.
func ModelProfileServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "model.profile-service",
		GatewayManifest:     ModelProfileServiceGatewayManifest(),
		RequestInfoResolver: ModelProfileServiceKernelRequestInfoResolver,
		AccessResolver:      ModelProfileServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(ModelProfileServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for model.v1.ModelProfileService must implement ModelProfileServiceServer, got %T", impl)
			}
			RegisterModelProfileServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(ModelProfileServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for model.v1.ModelProfileService must implement ModelProfileServiceHTTPServer, got %T", impl)
			}
			RegisterModelProfileServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(ModelProfileServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for model.v1.ModelProfileService must implement ModelProfileServiceClient, got %T", client)
			}
			return RegisterModelProfileServiceGatewayInvokers(r, typed)
		},
	}
}

var ModelProfileServiceKernelAuthzRules = authz.Rules{
	"/model.v1.ModelProfileService/GetModelProfile": {
		Service:    "model.v1.ModelProfileService",
		Method:     "GetModelProfile",
		FullMethod: "/model.v1.ModelProfileService/GetModelProfile",
		Action:     "view",
		Resource:   "model_profile:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.model.get",
		AuditRisk:  "low",
	},
	"/model.v1.ModelProfileService/UpdateModelProfile": {
		Service:    "model.v1.ModelProfileService",
		Method:     "UpdateModelProfile",
		FullMethod: "/model.v1.ModelProfileService/UpdateModelProfile",
		Action:     "edit",
		Resource:   "model_profile:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.model.update",
		AuditRisk:  "medium",
	},
	"/model.v1.ModelProfileService/DeleteModelProfile": {
		Service:    "model.v1.ModelProfileService",
		Method:     "DeleteModelProfile",
		FullMethod: "/model.v1.ModelProfileService/DeleteModelProfile",
		Action:     "manage",
		Resource:   "model_profile:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.model.delete",
		AuditRisk:  "high",
	},
	"/model.v1.ModelProfileService/ResolveModelProfile": {
		Service:    "model.v1.ModelProfileService",
		Method:     "ResolveModelProfile",
		FullMethod: "/model.v1.ModelProfileService/ResolveModelProfile",
		Action:     "execute",
		Resource:   "model_profile:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.model.resolve",
		AuditRisk:  "low",
	},
	"/model.v1.ModelProfileService/TestModelProfile": {
		Service:    "model.v1.ModelProfileService",
		Method:     "TestModelProfile",
		FullMethod: "/model.v1.ModelProfileService/TestModelProfile",
		Action:     "edit",
		Resource:   "model_profile:{id}",
		Audience:   "hub-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "hub.model.test",
		AuditRisk:  "medium",
	},
}

// ModelProfileServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func ModelProfileServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _ModelProfileServiceKernelNormalizeOperation(operation) {
	case "/model.v1.ModelProfileService/ListModelProfiles":
		info := requestx.Info{
			Service:   "model.v1.ModelProfileService",
			Method:    "ListModelProfiles",
			Operation: "/model.v1.ModelProfileService/ListModelProfiles",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "hub.model.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/model.v1.ModelProfileService/GetModelProfile":
		info := requestx.Info{
			Service:       "model.v1.ModelProfileService",
			Method:        "GetModelProfile",
			Operation:     "/model.v1.ModelProfileService/GetModelProfile",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view",
			Resource:      "model_profile:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.model.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/model.v1.ModelProfileService/CreateModelProfile":
		info := requestx.Info{
			Service:   "model.v1.ModelProfileService",
			Method:    "CreateModelProfile",
			Operation: "/model.v1.ModelProfileService/CreateModelProfile",
			Exposure:  v1.Exposure_AUTHENTICATED,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "hub.model.create"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/model.v1.ModelProfileService/UpdateModelProfile":
		info := requestx.Info{
			Service:       "model.v1.ModelProfileService",
			Method:        "UpdateModelProfile",
			Operation:     "/model.v1.ModelProfileService/UpdateModelProfile",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "model_profile:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.model.update"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/model.v1.ModelProfileService/DeleteModelProfile":
		info := requestx.Info{
			Service:       "model.v1.ModelProfileService",
			Method:        "DeleteModelProfile",
			Operation:     "/model.v1.ModelProfileService/DeleteModelProfile",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "model_profile:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.model.delete"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/model.v1.ModelProfileService/ResolveModelProfile":
		info := requestx.Info{
			Service:       "model.v1.ModelProfileService",
			Method:        "ResolveModelProfile",
			Operation:     "/model.v1.ModelProfileService/ResolveModelProfile",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "execute",
			Resource:      "model_profile:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.model.resolve"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/model.v1.ModelProfileService/TestModelProfile":
		info := requestx.Info{
			Service:       "model.v1.ModelProfileService",
			Method:        "TestModelProfile",
			Operation:     "/model.v1.ModelProfileService/TestModelProfile",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "edit",
			Resource:      "model_profile:{id}",
			TargetService: "hub-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "hub.model.test"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// ModelProfileServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func ModelProfileServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := ModelProfileServiceKernelAuthzRules[_ModelProfileServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _ModelProfileServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "ListModelProfiles", "model.v1.ModelProfileService/ListModelProfiles":
		return "/model.v1.ModelProfileService/ListModelProfiles"
	case "GetModelProfile", "model.v1.ModelProfileService/GetModelProfile":
		return "/model.v1.ModelProfileService/GetModelProfile"
	case "CreateModelProfile", "model.v1.ModelProfileService/CreateModelProfile":
		return "/model.v1.ModelProfileService/CreateModelProfile"
	case "UpdateModelProfile", "model.v1.ModelProfileService/UpdateModelProfile":
		return "/model.v1.ModelProfileService/UpdateModelProfile"
	case "DeleteModelProfile", "model.v1.ModelProfileService/DeleteModelProfile":
		return "/model.v1.ModelProfileService/DeleteModelProfile"
	case "ResolveModelProfile", "model.v1.ModelProfileService/ResolveModelProfile":
		return "/model.v1.ModelProfileService/ResolveModelProfile"
	case "TestModelProfile", "model.v1.ModelProfileService/TestModelProfile":
		return "/model.v1.ModelProfileService/TestModelProfile"
	default:
		return operation
	}
}
