// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.4.19
// - protoc             (unknown)
// source: model/v1/model.proto

package modelv1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationModelProfileServiceCreateModelProfile = "/model.v1.ModelProfileService/CreateModelProfile"
const OperationModelProfileServiceDeleteModelProfile = "/model.v1.ModelProfileService/DeleteModelProfile"
const OperationModelProfileServiceGetModelProfile = "/model.v1.ModelProfileService/GetModelProfile"
const OperationModelProfileServiceListModelProfiles = "/model.v1.ModelProfileService/ListModelProfiles"
const OperationModelProfileServiceResolveModelProfile = "/model.v1.ModelProfileService/ResolveModelProfile"
const OperationModelProfileServiceTestModelProfile = "/model.v1.ModelProfileService/TestModelProfile"
const OperationModelProfileServiceUpdateModelProfile = "/model.v1.ModelProfileService/UpdateModelProfile"

type ModelProfileServiceHTTPServer interface {
	// CreateModelProfile CreateModelProfile is AUTHENTICATED rather than AUTHORIZED at the gateway
	// because the authz resource (zone/project) is derived from the principal's
	// OrgID, not a path parameter. The biz layer performs the explicit
	// edit-on-project check using principal.OrgID/ProjectID.
	CreateModelProfile(context.Context, *CreateModelProfileRequest) (*CreateModelProfileResponse, error)
	DeleteModelProfile(context.Context, *DeleteModelProfileRequest) (*DeleteModelProfileResponse, error)
	GetModelProfile(context.Context, *GetModelProfileRequest) (*GetModelProfileResponse, error)
	ListModelProfiles(context.Context, *ListModelProfilesRequest) (*ListModelProfilesResponse, error)
	// ResolveModelProfile ResolveModelProfile returns an immutable runtime snapshot the AISphere
	// Runtime consumes to build an ADK model.LLM. The snapshot carries a
	// credential_ref (never a plain-text key), capabilities and limits. Runtime
	// resolves the actual credential via its CredentialProvider.
	ResolveModelProfile(context.Context, *ResolveModelProfileRequest) (*ResolveModelProfileResponse, error)
	// TestModelProfile TestModelProfile probes the upstream model endpoint with a minimal
	// request built from api_format. Hub never holds plain-text credentials:
	// only env:// secret refs are resolved locally (from the hub process
	// environment); other refs probe without auth, so a 401/403 still proves
	// reachability and is reported via http_status. The audit event is recorded
	// so test attempts are traceable.
	TestModelProfile(context.Context, *TestModelProfileRequest) (*TestModelProfileResponse, error)
	UpdateModelProfile(context.Context, *UpdateModelProfileRequest) (*UpdateModelProfileResponse, error)
}

func RegisterModelProfileServiceHTTPServer(s *http.Server, srv ModelProfileServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("DELETE", "/v1/model-profiles/{id}", _ModelProfileService_DeleteModelProfile0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/model-profiles", _ModelProfileService_ListModelProfiles0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/model-profiles/{id}", _ModelProfileService_GetModelProfile0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/model-profiles", _ModelProfileService_CreateModelProfile0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/model-profiles/{id}:resolve", _ModelProfileService_ResolveModelProfile0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/model-profiles/{id}:test", _ModelProfileService_TestModelProfile0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/model-profiles/{id}", _ModelProfileService_UpdateModelProfile0_HTTP_Handler(srv))
}

func _ModelProfileService_DeleteModelProfile0_HTTP_Handler(srv ModelProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteModelProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModelProfileServiceDeleteModelProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteModelProfile(ctx, req.(*DeleteModelProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteModelProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ModelProfileService_ListModelProfiles0_HTTP_Handler(srv ModelProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListModelProfilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModelProfileServiceListModelProfiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListModelProfiles(ctx, req.(*ListModelProfilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListModelProfilesResponse)
		return ctx.Result(200, reply)
	}
}

func _ModelProfileService_GetModelProfile0_HTTP_Handler(srv ModelProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetModelProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModelProfileServiceGetModelProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetModelProfile(ctx, req.(*GetModelProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetModelProfileResponse)
		return ctx.Result(200, reply.ModelProfile)
	}
}

func _ModelProfileService_CreateModelProfile0_HTTP_Handler(srv ModelProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateModelProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModelProfileServiceCreateModelProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateModelProfile(ctx, req.(*CreateModelProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateModelProfileResponse)
		return ctx.Result(200, reply.ModelProfile)
	}
}

func _ModelProfileService_ResolveModelProfile0_HTTP_Handler(srv ModelProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResolveModelProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModelProfileServiceResolveModelProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveModelProfile(ctx, req.(*ResolveModelProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResolveModelProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ModelProfileService_TestModelProfile0_HTTP_Handler(srv ModelProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TestModelProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModelProfileServiceTestModelProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestModelProfile(ctx, req.(*TestModelProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TestModelProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ModelProfileService_UpdateModelProfile0_HTTP_Handler(srv ModelProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateModelProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModelProfileServiceUpdateModelProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateModelProfile(ctx, req.(*UpdateModelProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateModelProfileResponse)
		return ctx.Result(200, reply.ModelProfile)
	}
}

type ModelProfileServiceHTTPClient interface {
	// CreateModelProfile CreateModelProfile is AUTHENTICATED rather than AUTHORIZED at the gateway
	// because the authz resource (zone/project) is derived from the principal's
	// OrgID, not a path parameter. The biz layer performs the explicit
	// edit-on-project check using principal.OrgID/ProjectID.
	CreateModelProfile(ctx context.Context, req *CreateModelProfileRequest, opts ...http.CallOption) (rsp *CreateModelProfileResponse, err error)
	DeleteModelProfile(ctx context.Context, req *DeleteModelProfileRequest, opts ...http.CallOption) (rsp *DeleteModelProfileResponse, err error)
	GetModelProfile(ctx context.Context, req *GetModelProfileRequest, opts ...http.CallOption) (rsp *GetModelProfileResponse, err error)
	ListModelProfiles(ctx context.Context, req *ListModelProfilesRequest, opts ...http.CallOption) (rsp *ListModelProfilesResponse, err error)
	// ResolveModelProfile ResolveModelProfile returns an immutable runtime snapshot the AISphere
	// Runtime consumes to build an ADK model.LLM. The snapshot carries a
	// credential_ref (never a plain-text key), capabilities and limits. Runtime
	// resolves the actual credential via its CredentialProvider.
	ResolveModelProfile(ctx context.Context, req *ResolveModelProfileRequest, opts ...http.CallOption) (rsp *ResolveModelProfileResponse, err error)
	// TestModelProfile TestModelProfile probes the upstream model endpoint with a minimal
	// request built from api_format. Hub never holds plain-text credentials:
	// only env:// secret refs are resolved locally (from the hub process
	// environment); other refs probe without auth, so a 401/403 still proves
	// reachability and is reported via http_status. The audit event is recorded
	// so test attempts are traceable.
	TestModelProfile(ctx context.Context, req *TestModelProfileRequest, opts ...http.CallOption) (rsp *TestModelProfileResponse, err error)
	UpdateModelProfile(ctx context.Context, req *UpdateModelProfileRequest, opts ...http.CallOption) (rsp *UpdateModelProfileResponse, err error)
}

type ModelProfileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewModelProfileServiceHTTPClient(client *http.Client) ModelProfileServiceHTTPClient {
	return &ModelProfileServiceHTTPClientImpl{client}
}

// CreateModelProfile CreateModelProfile is AUTHENTICATED rather than AUTHORIZED at the gateway
// because the authz resource (zone/project) is derived from the principal's
// OrgID, not a path parameter. The biz layer performs the explicit
// edit-on-project check using principal.OrgID/ProjectID.
func (c *ModelProfileServiceHTTPClientImpl) CreateModelProfile(ctx context.Context, in *CreateModelProfileRequest, opts ...http.CallOption) (*CreateModelProfileResponse, error) {
	var out CreateModelProfileResponse
	pattern := "/v1/model-profiles"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationModelProfileServiceCreateModelProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out.ModelProfile, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModelProfileServiceHTTPClientImpl) DeleteModelProfile(ctx context.Context, in *DeleteModelProfileRequest, opts ...http.CallOption) (*DeleteModelProfileResponse, error) {
	var out DeleteModelProfileResponse
	pattern := "/v1/model-profiles/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationModelProfileServiceDeleteModelProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModelProfileServiceHTTPClientImpl) GetModelProfile(ctx context.Context, in *GetModelProfileRequest, opts ...http.CallOption) (*GetModelProfileResponse, error) {
	var out GetModelProfileResponse
	pattern := "/v1/model-profiles/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationModelProfileServiceGetModelProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out.ModelProfile, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModelProfileServiceHTTPClientImpl) ListModelProfiles(ctx context.Context, in *ListModelProfilesRequest, opts ...http.CallOption) (*ListModelProfilesResponse, error) {
	var out ListModelProfilesResponse
	pattern := "/v1/model-profiles"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationModelProfileServiceListModelProfiles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResolveModelProfile ResolveModelProfile returns an immutable runtime snapshot the AISphere
// Runtime consumes to build an ADK model.LLM. The snapshot carries a
// credential_ref (never a plain-text key), capabilities and limits. Runtime
// resolves the actual credential via its CredentialProvider.
func (c *ModelProfileServiceHTTPClientImpl) ResolveModelProfile(ctx context.Context, in *ResolveModelProfileRequest, opts ...http.CallOption) (*ResolveModelProfileResponse, error) {
	var out ResolveModelProfileResponse
	pattern := "/v1/model-profiles/{id}:resolve"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationModelProfileServiceResolveModelProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TestModelProfile TestModelProfile probes the upstream model endpoint with a minimal
// request built from api_format. Hub never holds plain-text credentials:
// only env:// secret refs are resolved locally (from the hub process
// environment); other refs probe without auth, so a 401/403 still proves
// reachability and is reported via http_status. The audit event is recorded
// so test attempts are traceable.
func (c *ModelProfileServiceHTTPClientImpl) TestModelProfile(ctx context.Context, in *TestModelProfileRequest, opts ...http.CallOption) (*TestModelProfileResponse, error) {
	var out TestModelProfileResponse
	pattern := "/v1/model-profiles/{id}:test"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationModelProfileServiceTestModelProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModelProfileServiceHTTPClientImpl) UpdateModelProfile(ctx context.Context, in *UpdateModelProfileRequest, opts ...http.CallOption) (*UpdateModelProfileResponse, error) {
	var out UpdateModelProfileResponse
	pattern := "/v1/model-profiles/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationModelProfileServiceUpdateModelProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out.ModelProfile, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
